from stressor_templates import *
import copy

anthropogenic_plantations_stressors = {
    "Monoculture": {},
    "Land Conversion": {},
    "Pesticide Use": {},
    "Fertilizer Use": {},
    "Water Use": {},
    "Soil Erosion": {},
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Monoculture ---
anthropogenic_plantations_stressors["Monoculture"]["Metric"] = 'Area planted with a single species (ha); lack of genetic diversity within the planted species.'
anthropogenic_plantations_stressors["Monoculture"]["Data Sources"] = ['Forestry statistics (for tree plantations).', 'Agricultural statistics (for other crops).', 'Remote sensing data.', 'Company reports (for some large plantations).', '**Impact on Area:** Creates a highly simplified, homogenous ecosystem.', '**Impact on Biodiversity:**', '*Very low* biodiversity compared to natural forests or other diverse ecosystems.', 'Provides limited habitat for most native species.', 'Increased vulnerability to pests and diseases (due to lack of genetic diversity).', '**Influenced By (Stressors):**', 'Plantations - Economic Factors:  Monocultures are often more efficient to manage and harvest.', 'Plantations - Demand for Specific Products: (e.g., pulpwood, palm oil, rubber).', 'Plantations - Government Policies: (e.g., subsidies for certain crops).', '**Influences (Stressors):**', 'Plantations - Pest and Disease Outbreaks: A *major* consequence.', 'Plantations - Soil Degradation (in some cases).', 'Plantations - Reduced Resilience', '**Logic Description:** Monoculture plantations, by definition, lack biodiversity.  This makes them highly vulnerable to pests and diseases and provides limited habitat for native wildlife.']
anthropogenic_plantations_stressors["Monoculture"]["Impact on Area"] = 'Creates a highly simplified, homogenous ecosystem.'
anthropogenic_plantations_stressors["Monoculture"]["Impact on Biodiversity"] = '*Very low* biodiversity compared to natural forests or other diverse ecosystems.\nProvides limited habitat for most native species.\nIncreased vulnerability to pests and diseases (due to lack of genetic diversity).\n**Influenced By (Stressors):**\nPlantations - Economic Factors:  Monocultures are often more efficient to manage and harvest.\nPlantations - Demand for Specific Products: (e.g., pulpwood, palm oil, rubber).\nPlantations - Government Policies: (e.g., subsidies for certain crops).\n**Influences (Stressors):**\nPlantations - Pest and Disease Outbreaks: A *major* consequence.\nPlantations - Soil Degradation (in some cases).\nPlantations - Reduced Resilience\n**Logic Description:** Monoculture plantations, by definition, lack biodiversity.  This makes them highly vulnerable to pests and diseases and provides limited habitat for native wildlife.'
anthropogenic_plantations_stressors["Monoculture"]["Influenced By"] = ['Plantations - Economic Factors:  Monocultures are often more efficient to manage and harvest.', 'Plantations - Demand for Specific Products: (e.g., pulpwood, palm oil, rubber).', 'Plantations - Government Policies: (e.g., subsidies for certain crops).', '**Influences (Stressors):**', 'Plantations - Pest and Disease Outbreaks: A *major* consequence.', 'Plantations - Soil Degradation (in some cases).', 'Plantations - Reduced Resilience', '**Logic Description:** Monoculture plantations, by definition, lack biodiversity.  This makes them highly vulnerable to pests and diseases and provides limited habitat for native wildlife.']
anthropogenic_plantations_stressors["Monoculture"]["Influences"] = ['Plantations - Pest and Disease Outbreaks: A *major* consequence.', 'Plantations - Soil Degradation (in some cases).', 'Plantations - Reduced Resilience', '**Logic Description:** Monoculture plantations, by definition, lack biodiversity.  This makes them highly vulnerable to pests and diseases and provides limited habitat for native wildlife.']
anthropogenic_plantations_stressors["Monoculture"]["Logic Description"] = '---'

# --- Land Conversion ---
anthropogenic_plantations_stressors["Land Conversion"]["Metric"] = 'Area of natural forest or other ecosystems converted to plantations (ha/year).'
anthropogenic_plantations_stressors["Land Conversion"]["Data Sources"] = ['Remote sensing data.', 'Land-use change data.', 'Government statistics.', 'NGO reports.', '**Impact on Area:** Loss of natural habitats (e.g., rainforests, peatlands, grasslands).', '**Impact on Biodiversity:**', '*Major* loss of biodiversity due to habitat destruction.', 'Fragmentation of remaining natural habitats.', '**Influenced By (Stressors):**', 'Plantations - Demand for Plantation Products: (e.g., pulpwood, palm oil, rubber, timber).', 'Plantations - Economic Factors: Profitability of plantation crops.', 'Plantations - Government Policies: Land-use planning, subsidies.', 'Plantations - Land Availability.', '**Influences (Stressors):**', 'Habitat Loss (the primary impact).', 'Deforestation (if forests are cleared).', 'Peatland Degradation (if plantations are established on peatlands).', '**Logic Description:** The establishment of plantations often involves clearing natural forests or other valuable ecosystems, leading to significant biodiversity loss and habitat fragmentation. This is especially problematic in areas like Southeast Asia, where oil palm plantations have replaced vast areas of rainforest.']
anthropogenic_plantations_stressors["Land Conversion"]["Impact on Area"] = 'Loss of natural habitats (e.g., rainforests, peatlands, grasslands).'
anthropogenic_plantations_stressors["Land Conversion"]["Impact on Biodiversity"] = '*Major* loss of biodiversity due to habitat destruction.\nFragmentation of remaining natural habitats.\n**Influenced By (Stressors):**\nPlantations - Demand for Plantation Products: (e.g., pulpwood, palm oil, rubber, timber).\nPlantations - Economic Factors: Profitability of plantation crops.\nPlantations - Government Policies: Land-use planning, subsidies.\nPlantations - Land Availability.\n**Influences (Stressors):**\nHabitat Loss (the primary impact).\nDeforestation (if forests are cleared).\nPeatland Degradation (if plantations are established on peatlands).\n**Logic Description:** The establishment of plantations often involves clearing natural forests or other valuable ecosystems, leading to significant biodiversity loss and habitat fragmentation. This is especially problematic in areas like Southeast Asia, where oil palm plantations have replaced vast areas of rainforest.'
anthropogenic_plantations_stressors["Land Conversion"]["Influenced By"] = ['Plantations - Demand for Plantation Products: (e.g., pulpwood, palm oil, rubber, timber).', 'Plantations - Economic Factors: Profitability of plantation crops.', 'Plantations - Government Policies: Land-use planning, subsidies.', 'Plantations - Land Availability.', '**Influences (Stressors):**', 'Habitat Loss (the primary impact).', 'Deforestation (if forests are cleared).', 'Peatland Degradation (if plantations are established on peatlands).', '**Logic Description:** The establishment of plantations often involves clearing natural forests or other valuable ecosystems, leading to significant biodiversity loss and habitat fragmentation. This is especially problematic in areas like Southeast Asia, where oil palm plantations have replaced vast areas of rainforest.']
anthropogenic_plantations_stressors["Land Conversion"]["Influences"] = ['Habitat Loss (the primary impact).', 'Deforestation (if forests are cleared).', 'Peatland Degradation (if plantations are established on peatlands).', '**Logic Description:** The establishment of plantations often involves clearing natural forests or other valuable ecosystems, leading to significant biodiversity loss and habitat fragmentation. This is especially problematic in areas like Southeast Asia, where oil palm plantations have replaced vast areas of rainforest.']
anthropogenic_plantations_stressors["Land Conversion"]["Logic Description"] = '---'

# --- Pesticide Use ---
anthropogenic_plantations_stressors["Pesticide Use"]["Metric"] = 'Amount of pesticides applied (kg/ha/year); types of pesticides used; concentrations of pesticides in soil, water, and biota.'
anthropogenic_plantations_stressors["Pesticide Use"]["Data Sources"] = ['Agricultural statistics (often limited).', 'Company reports (some companies disclose pesticide use).', 'Research studies.', 'Water quality monitoring data.', '**Impact on Area:** Contamination of soil and water.', '**Impact on Biodiversity:**', 'Non-target effects: Pesticides can harm beneficial insects, birds, amphibians, and other wildlife.', 'Development of pesticide resistance in pest populations.', 'Water pollution, impacting aquatic ecosystems.', '**Influenced By (Stressors):**', 'Plantations - Pest Management Practices: Reliance on chemical pesticides.', 'Plantations - Monoculture: Increases vulnerability to pests.', 'Plantations - Government Regulations: (or lack thereof).', '**Influences (Stressors):**', 'Plantations - Water Pollution.', 'Plantations - Soil Contamination.', 'Non-Target Species Mortality.', '**Logic Description:** Intensive pesticide use in plantations can contaminate soil and water, harming non-target species and potentially leading to the development of pesticide resistance.']
anthropogenic_plantations_stressors["Pesticide Use"]["Impact on Area"] = 'Contamination of soil and water.'
anthropogenic_plantations_stressors["Pesticide Use"]["Impact on Biodiversity"] = 'Non-target effects: Pesticides can harm beneficial insects, birds, amphibians, and other wildlife.\nDevelopment of pesticide resistance in pest populations.\nWater pollution, impacting aquatic ecosystems.\n**Influenced By (Stressors):**\nPlantations - Pest Management Practices: Reliance on chemical pesticides.\nPlantations - Monoculture: Increases vulnerability to pests.\nPlantations - Government Regulations: (or lack thereof).\n**Influences (Stressors):**\nPlantations - Water Pollution.\nPlantations - Soil Contamination.\nNon-Target Species Mortality.\n**Logic Description:** Intensive pesticide use in plantations can contaminate soil and water, harming non-target species and potentially leading to the development of pesticide resistance.'
anthropogenic_plantations_stressors["Pesticide Use"]["Influenced By"] = ['Plantations - Pest Management Practices: Reliance on chemical pesticides.', 'Plantations - Monoculture: Increases vulnerability to pests.', 'Plantations - Government Regulations: (or lack thereof).', '**Influences (Stressors):**', 'Plantations - Water Pollution.', 'Plantations - Soil Contamination.', 'Non-Target Species Mortality.', '**Logic Description:** Intensive pesticide use in plantations can contaminate soil and water, harming non-target species and potentially leading to the development of pesticide resistance.']
anthropogenic_plantations_stressors["Pesticide Use"]["Influences"] = ['Plantations - Water Pollution.', 'Plantations - Soil Contamination.', 'Non-Target Species Mortality.', '**Logic Description:** Intensive pesticide use in plantations can contaminate soil and water, harming non-target species and potentially leading to the development of pesticide resistance.']
anthropogenic_plantations_stressors["Pesticide Use"]["Logic Description"] = '---'

# --- Fertilizer Use ---
anthropogenic_plantations_stressors["Fertilizer Use"]["Metric"] = 'Amount of fertilizers applied (kg/ha/year); types of fertilizers used; nutrient concentrations in soil and water.'
anthropogenic_plantations_stressors["Fertilizer Use"]["Data Sources"] = ['Agricultural statistics (often limited).', 'Company reports (some companies disclose fertilizer use).', 'Research studies.', 'Water quality monitoring data.', '**Impact on Area:** Soil and water pollution; eutrophication of waterways.', '**Impact on Biodiversity:**', 'Nutrient runoff can lead to algal blooms and oxygen depletion in aquatic ecosystems.', 'Changes in soil nutrient balance can impact plant communities.', '**Influenced By (Stressors):**', 'Plantations - Management Practices: Aiming for high yields.', '*  Plantations - Monoculture: Can lead to nutrient depletion in the soil, requiring higher fertilizer inputs.', 'Plantations - Government Policies: (e.g., subsidies for fertilizers).', '**Influences (Stressors):**', 'Plantations - Water Pollution.', 'Plantations - Soil Degradation (in the long term).', 'Eutrophication (in nearby water bodies).', '**Logic Description:** Intensive fertilizer use in plantations can lead to nutrient runoff, polluting waterways and causing eutrophication.']
anthropogenic_plantations_stressors["Fertilizer Use"]["Impact on Area"] = 'Soil and water pollution; eutrophication of waterways.'
anthropogenic_plantations_stressors["Fertilizer Use"]["Impact on Biodiversity"] = 'Nutrient runoff can lead to algal blooms and oxygen depletion in aquatic ecosystems.\nChanges in soil nutrient balance can impact plant communities.\n**Influenced By (Stressors):**\nPlantations - Management Practices: Aiming for high yields.\n*  Plantations - Monoculture: Can lead to nutrient depletion in the soil, requiring higher fertilizer inputs.\nPlantations - Government Policies: (e.g., subsidies for fertilizers).\n**Influences (Stressors):**\nPlantations - Water Pollution.\nPlantations - Soil Degradation (in the long term).\nEutrophication (in nearby water bodies).\n**Logic Description:** Intensive fertilizer use in plantations can lead to nutrient runoff, polluting waterways and causing eutrophication.'
anthropogenic_plantations_stressors["Fertilizer Use"]["Influenced By"] = ['Plantations - Management Practices: Aiming for high yields.', '*  Plantations - Monoculture: Can lead to nutrient depletion in the soil, requiring higher fertilizer inputs.', 'Plantations - Government Policies: (e.g., subsidies for fertilizers).', '**Influences (Stressors):**', 'Plantations - Water Pollution.', 'Plantations - Soil Degradation (in the long term).', 'Eutrophication (in nearby water bodies).', '**Logic Description:** Intensive fertilizer use in plantations can lead to nutrient runoff, polluting waterways and causing eutrophication.']
anthropogenic_plantations_stressors["Fertilizer Use"]["Influences"] = ['Plantations - Water Pollution.', 'Plantations - Soil Degradation (in the long term).', 'Eutrophication (in nearby water bodies).', '**Logic Description:** Intensive fertilizer use in plantations can lead to nutrient runoff, polluting waterways and causing eutrophication.']
anthropogenic_plantations_stressors["Fertilizer Use"]["Logic Description"] = '---'

# --- Water Use ---
anthropogenic_plantations_stressors["Water Use"]["Metric"] = 'Volume of water used for irrigation (m³/ha/year); impacts on water availability.'
anthropogenic_plantations_stressors["Water Use"]["Data Sources"] = ['* Water usage records (where available).', '* Research', '**Impact on Area:** Can deplete water resources, especially in water-scarce regions.', '**Impact on Biodiversity:**', '* Impacts on aquatic ecosystems if water is diverted from rivers or groundwater.', '**Influenced By (Stressors):**', '* Plantation crop type (some require more water than others).', '* Climate.', '* Irrigation practices', '**Influences (Stressors):**', '* Water Availability', '**Logic Description:** Plantations, particularly those in drier regions or those growing water-intensive crops, can put significant pressure on water resources.']
anthropogenic_plantations_stressors["Water Use"]["Impact on Area"] = 'Can deplete water resources, especially in water-scarce regions.'
anthropogenic_plantations_stressors["Water Use"]["Impact on Biodiversity"] = '* Impacts on aquatic ecosystems if water is diverted from rivers or groundwater.\n**Influenced By (Stressors):**\n* Plantation crop type (some require more water than others).\n* Climate.\n* Irrigation practices\n**Influences (Stressors):**\n* Water Availability\n**Logic Description:** Plantations, particularly those in drier regions or those growing water-intensive crops, can put significant pressure on water resources.'
anthropogenic_plantations_stressors["Water Use"]["Influenced By"] = ['* Plantation crop type (some require more water than others).', '* Climate.', '* Irrigation practices', '**Influences (Stressors):**', '* Water Availability', '**Logic Description:** Plantations, particularly those in drier regions or those growing water-intensive crops, can put significant pressure on water resources.']
anthropogenic_plantations_stressors["Water Use"]["Influences"] = ['* Water Availability', '**Logic Description:** Plantations, particularly those in drier regions or those growing water-intensive crops, can put significant pressure on water resources.']
anthropogenic_plantations_stressors["Water Use"]["Logic Description"] = '---'

# --- Soil Erosion ---
anthropogenic_plantations_stressors["Soil Erosion"]["Metric"] = 'Soil loss rate (tonnes/ha/year).'
anthropogenic_plantations_stressors["Soil Erosion"]["Data Sources"] = ['Field measurements.', 'Erosion models.', '**Impact on Area:** Loss of topsoil; reduced soil fertility; sedimentation of waterways.', '**Impact on Biodiversity:**', 'Impacts on soil organisms.', 'Water pollution.', '**Influenced By (Stressors):**', 'Plantations - Deforestation (removal of natural vegetation cover).', 'Plantations - Management Practices: (e.g., tillage, lack of cover crops).', 'Plantations - Slope and Soil Type.', '**Influences (Stressors):**', '* Plantations - Soil Degradation', 'Water Quality (sedimentation).', '**Logic Description:** Soil erosion can be a significant problem in plantations, particularly on slopes and where vegetation cover is removed.']
anthropogenic_plantations_stressors["Soil Erosion"]["Impact on Area"] = 'Loss of topsoil; reduced soil fertility; sedimentation of waterways.'
anthropogenic_plantations_stressors["Soil Erosion"]["Impact on Biodiversity"] = 'Impacts on soil organisms.\nWater pollution.\n**Influenced By (Stressors):**\nPlantations - Deforestation (removal of natural vegetation cover).\nPlantations - Management Practices: (e.g., tillage, lack of cover crops).\nPlantations - Slope and Soil Type.\n**Influences (Stressors):**\n* Plantations - Soil Degradation\nWater Quality (sedimentation).\n**Logic Description:** Soil erosion can be a significant problem in plantations, particularly on slopes and where vegetation cover is removed.'
anthropogenic_plantations_stressors["Soil Erosion"]["Influenced By"] = ['Plantations - Deforestation (removal of natural vegetation cover).', 'Plantations - Management Practices: (e.g., tillage, lack of cover crops).', 'Plantations - Slope and Soil Type.', '**Influences (Stressors):**', '* Plantations - Soil Degradation', 'Water Quality (sedimentation).', '**Logic Description:** Soil erosion can be a significant problem in plantations, particularly on slopes and where vegetation cover is removed.']
anthropogenic_plantations_stressors["Soil Erosion"]["Influences"] = ['* Plantations - Soil Degradation', 'Water Quality (sedimentation).', '**Logic Description:** Soil erosion can be a significant problem in plantations, particularly on slopes and where vegetation cover is removed.']
anthropogenic_plantations_stressors["Soil Erosion"]["Logic Description"] = '---'

# --- Climate Change ---
anthropogenic_plantations_stressors["Climate Change"]["Metric"] = 'Changes in temperature, precipitation, and the frequency/intensity of extreme weather events.'
anthropogenic_plantations_stressors["Climate Change"]["Data Sources"] = ['* Climate models.', '* Historical weather data.', '**Impact on Area:** Changes in growing conditions; increased risk of drought, floods, and wildfires.', '**Impact on Biodiversity:**', 'May make some areas unsuitable for certain plantation crops.', 'Increased stress on trees and crops.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions', '**Influences (Stressors):**', 'Many, Varies.', '* Plantations- Pest and Disease outbreaks', '**Logic Description:** Climate change can impact plantation productivity and increase the risk of extreme events.']
anthropogenic_plantations_stressors["Climate Change"]["Impact on Area"] = 'Changes in growing conditions; increased risk of drought, floods, and wildfires.'
anthropogenic_plantations_stressors["Climate Change"]["Impact on Biodiversity"] = 'May make some areas unsuitable for certain plantation crops.\nIncreased stress on trees and crops.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions\n**Influences (Stressors):**\nMany, Varies.\n* Plantations- Pest and Disease outbreaks\n**Logic Description:** Climate change can impact plantation productivity and increase the risk of extreme events.'
anthropogenic_plantations_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions', '**Influences (Stressors):**', 'Many, Varies.', '* Plantations- Pest and Disease outbreaks', '**Logic Description:** Climate change can impact plantation productivity and increase the risk of extreme events.']
anthropogenic_plantations_stressors["Climate Change"]["Influences"] = ['Many, Varies.', '* Plantations- Pest and Disease outbreaks', '**Logic Description:** Climate change can impact plantation productivity and increase the risk of extreme events.']
anthropogenic_plantations_stressors["Climate Change"]["Logic Description"] = '---'

