from stressor_templates import *
import copy

aquatic_lake_baikal_stressors = {
    "Climate Change": copy.deepcopy(climate_change_template),
    "Pollution": copy.deepcopy(pollution_template),
    "Poaching": {},
}

# --- Climate Change ---
aquatic_lake_baikal_stressors["Climate Change"]["Metric"] = 'Water temperature (°C); ice cover duration and thickness; changes in stratification; changes in precipitation and evaporation.'
aquatic_lake_baikal_stressors["Climate Change"]["Data Sources"] = ['Limnological Institute of the Siberian Branch of the Russian Academy of Sciences.', 'Russian Hydrometeorological Service.', 'International research collaborations.', 'Climate models.', '**Impact on Area:** Warming waters; reduced ice cover; changes in mixing patterns.', '**Impact on Biodiversity:**', 'Potential impacts on endemic species (e.g., the Baikal seal, omul fish, and numerous invertebrate species).', 'Shifts in species distributions.', 'Increased risk of algal blooms.', 'Changes in the food web.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Ice Cover (major impact).', 'Water Temperature.', 'Ecosystem Functioning.', "**Logic Description:** Climate change is a *major* threat to Lake Baikal, with warming waters, reduced ice cover, and potential impacts on the lake's unique and endemic biodiversity. The lake's deep waters are warming, which is a significant concern."]
aquatic_lake_baikal_stressors["Climate Change"]["Impact on Area"] = 'Warming waters; reduced ice cover; changes in mixing patterns.'
aquatic_lake_baikal_stressors["Climate Change"]["Impact on Biodiversity"] = "Potential impacts on endemic species (e.g., the Baikal seal, omul fish, and numerous invertebrate species).\nShifts in species distributions.\nIncreased risk of algal blooms.\nChanges in the food web.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nIce Cover (major impact).\nWater Temperature.\nEcosystem Functioning.\n**Logic Description:** Climate change is a *major* threat to Lake Baikal, with warming waters, reduced ice cover, and potential impacts on the lake's unique and endemic biodiversity. The lake's deep waters are warming, which is a significant concern."
aquatic_lake_baikal_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Ice Cover (major impact).', 'Water Temperature.', 'Ecosystem Functioning.', "**Logic Description:** Climate change is a *major* threat to Lake Baikal, with warming waters, reduced ice cover, and potential impacts on the lake's unique and endemic biodiversity. The lake's deep waters are warming, which is a significant concern."]
aquatic_lake_baikal_stressors["Climate Change"]["Influences"] = ['Ice Cover (major impact).', 'Water Temperature.', 'Ecosystem Functioning.', "**Logic Description:** Climate change is a *major* threat to Lake Baikal, with warming waters, reduced ice cover, and potential impacts on the lake's unique and endemic biodiversity. The lake's deep waters are warming, which is a significant concern."]
aquatic_lake_baikal_stressors["Climate Change"]["Logic Description"] = '---'
aquatic_lake_baikal_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_aquatic_lake_baikal"

# --- Pollution ---
aquatic_lake_baikal_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., nutrients, heavy metals, organic pollutants) in water and sediments.'
aquatic_lake_baikal_stressors["Pollution"]["Data Sources"] = ['Limnological Institute of the Siberian Branch of the Russian Academy of Sciences.', 'Russian environmental monitoring agencies.', 'Research studies.', '**Impact on Area:** Localized pollution hotspots, particularly near industrial areas.', '**Impact on Biodiversity:**', 'Potential toxic effects on organisms.', 'Impacts on endemic species.', '**Influenced By (Stressors):**', 'Industrial Discharge: From pulp and paper mills and other industries (historically a major source, though regulations have improved).', 'Atmospheric Deposition.', 'Wastewater from settlements around the lake.', '**Influences (Stressors):**', 'Water Quality.', 'Wildlife Health.', "**Logic Description:** Pollution from industrial sources, atmospheric deposition, and wastewater discharge poses a threat to Lake Baikal's water quality and unique biodiversity.  The Baikal Pulp and Paper Mill was a major historical source, and while it has closed, legacy pollution remains a concern."]
aquatic_lake_baikal_stressors["Pollution"]["Impact on Area"] = 'Localized pollution hotspots, particularly near industrial areas.'
aquatic_lake_baikal_stressors["Pollution"]["Impact on Biodiversity"] = "Potential toxic effects on organisms.\nImpacts on endemic species.\n**Influenced By (Stressors):**\nIndustrial Discharge: From pulp and paper mills and other industries (historically a major source, though regulations have improved).\nAtmospheric Deposition.\nWastewater from settlements around the lake.\n**Influences (Stressors):**\nWater Quality.\nWildlife Health.\n**Logic Description:** Pollution from industrial sources, atmospheric deposition, and wastewater discharge poses a threat to Lake Baikal's water quality and unique biodiversity.  The Baikal Pulp and Paper Mill was a major historical source, and while it has closed, legacy pollution remains a concern."
aquatic_lake_baikal_stressors["Pollution"]["Influenced By"] = ['Industrial Discharge: From pulp and paper mills and other industries (historically a major source, though regulations have improved).', 'Atmospheric Deposition.', 'Wastewater from settlements around the lake.', '**Influences (Stressors):**', 'Water Quality.', 'Wildlife Health.', "**Logic Description:** Pollution from industrial sources, atmospheric deposition, and wastewater discharge poses a threat to Lake Baikal's water quality and unique biodiversity.  The Baikal Pulp and Paper Mill was a major historical source, and while it has closed, legacy pollution remains a concern."]
aquatic_lake_baikal_stressors["Pollution"]["Influences"] = ['Water Quality.', 'Wildlife Health.', "**Logic Description:** Pollution from industrial sources, atmospheric deposition, and wastewater discharge poses a threat to Lake Baikal's water quality and unique biodiversity.  The Baikal Pulp and Paper Mill was a major historical source, and while it has closed, legacy pollution remains a concern."]
aquatic_lake_baikal_stressors["Pollution"]["Logic Description"] = '---'
aquatic_lake_baikal_stressors["Pollution"]["Impact Function"] = "impact_pollution_aquatic_lake_baikal"

# --- Poaching ---
aquatic_lake_baikal_stressors["Poaching"]["Data Sources"] = ['* Government reports', '**Impact on Area**: N/A', '**Impact on Biodiversity:**', '* Population decline of endemic species', '**Influenced By (Stressors):**', '* Demand for rare/valuable species.', '* Economic hardship.', '**Influences (Stressors):**', '* Population levels', '**Logic Description:** Illegal hunting, especially the endemic seal.']
aquatic_lake_baikal_stressors["Poaching"]["Impact on Biodiversity"] = '* Population decline of endemic species\n**Influenced By (Stressors):**\n* Demand for rare/valuable species.\n* Economic hardship.\n**Influences (Stressors):**\n* Population levels\n**Logic Description:** Illegal hunting, especially the endemic seal.'
aquatic_lake_baikal_stressors["Poaching"]["Influenced By"] = ['* Demand for rare/valuable species.', '* Economic hardship.', '**Influences (Stressors):**', '* Population levels', '**Logic Description:** Illegal hunting, especially the endemic seal.']
aquatic_lake_baikal_stressors["Poaching"]["Influences"] = ['* Population levels', '**Logic Description:** Illegal hunting, especially the endemic seal.']
aquatic_lake_baikal_stressors["Poaching"]["Logic Description"] = '---'
aquatic_lake_baikal_stressors["Poaching"]["Impact Function"] = "impact_poaching_aquatic_lake_baikal"

