from stressor_templates import *
import copy

aquatic_salt_marshes_north_american_atlantic_coast_stressors = {
    "Sea Level Rise": {},
    "Coastal Development": {},
    "Altered Hydrology": copy.deepcopy(altered_hydrology_template),
    "Pollution": copy.deepcopy(pollution_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
}

# --- Sea Level Rise ---
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Metric"] = 'Rate of sea level rise (mm/year); marsh elevation relative to sea level; rate of vertical accretion; frequency/duration of inundation.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Data Sources"] = ['Tide gauge records (NOAA).', 'Satellite altimetry (NASA, ESA).', 'Sediment Elevation Tables (SETs).', 'USGS data.', 'Research publications.', '**Impact on Area:**', 'Inundation and submergence of low-lying marshes.', 'Landward migration (where possible).', 'Increased erosion.', '"Coastal squeeze" where migration is blocked.', '**Impact on Biodiversity:**', 'Loss of habitat for marsh-dependent species.', 'Shifts in plant communities (towards more salt-tolerant species).', 'Reduced nesting success for birds (e.g., Saltmarsh Sparrow).', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', 'Local Subsidence: In some areas.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** Sea level rise is a *critical* threat. Many areas are experiencing high rates of *relative* sea level rise (global rise + local subsidence). "Coastal squeeze" is a major concern, as development prevents landward migration.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Impact on Area"] = ''
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Impact on Biodiversity"] = 'Loss of habitat for marsh-dependent species.\nShifts in plant communities (towards more salt-tolerant species).\nReduced nesting success for birds (e.g., Saltmarsh Sparrow).\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\nLocal Subsidence: In some areas.\n**Influences (Stressors):**\nCoastal Erosion.\nHabitat Loss (the dominant impact).\n**Logic Description:** Sea level rise is a *critical* threat. Many areas are experiencing high rates of *relative* sea level rise (global rise + local subsidence). "Coastal squeeze" is a major concern, as development prevents landward migration.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', 'Local Subsidence: In some areas.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** Sea level rise is a *critical* threat. Many areas are experiencing high rates of *relative* sea level rise (global rise + local subsidence). "Coastal squeeze" is a major concern, as development prevents landward migration.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Influences"] = ['Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** Sea level rise is a *critical* threat. Many areas are experiencing high rates of *relative* sea level rise (global rise + local subsidence). "Coastal squeeze" is a major concern, as development prevents landward migration.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Logic Description"] = '---'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Sea Level Rise"]["Impact Function"] = "impact_sea_level_rise_aquatic_salt_marshes_north_american_atlantic_coast"

# --- Coastal Development ---
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Metric"] = 'Area of salt marsh converted to development (ha/year); length of hardened shoreline.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Data Sources"] = ['Remote sensing.', 'Land-use planning records.', '**Impact on Area:** Direct loss of habitat; fragmentation; prevents landward migration.', '**Impact on Biodiversity:**', 'Loss of habitat.', 'Reduced nursery grounds for fish.', '**Influenced By (Stressors):**', 'Urbanization.', 'Infrastructure Development.', '"Coastal Squeeze."', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss.', '**Logic Description:** Development directly removes marsh habitat and *prevents landward migration* in response to sea level rise, exacerbating the impacts of sea level rise.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Impact on Area"] = 'Direct loss of habitat; fragmentation; prevents landward migration.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Impact on Biodiversity"] = 'Loss of habitat.\nReduced nursery grounds for fish.\n**Influenced By (Stressors):**\nUrbanization.\nInfrastructure Development.\n"Coastal Squeeze."\n**Influences (Stressors):**\nCoastal Erosion.\nHabitat Loss.\n**Logic Description:** Development directly removes marsh habitat and *prevents landward migration* in response to sea level rise, exacerbating the impacts of sea level rise.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Influenced By"] = ['Urbanization.', 'Infrastructure Development.', '"Coastal Squeeze."', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss.', '**Logic Description:** Development directly removes marsh habitat and *prevents landward migration* in response to sea level rise, exacerbating the impacts of sea level rise.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Influences"] = ['Coastal Erosion.', 'Habitat Loss.', '**Logic Description:** Development directly removes marsh habitat and *prevents landward migration* in response to sea level rise, exacerbating the impacts of sea level rise.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Logic Description"] = '---'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Coastal Development"]["Impact Function"] = "impact_coastal_development_aquatic_salt_marshes_north_american_atlantic_coast"

# --- Altered Hydrology ---
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Metric"] = 'Changes in freshwater inflow; presence of ditches and drainage structures.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Data Sources"] = ['River gauge data.', 'Water management records.', '**Impact on Area:**', 'Changes in salinity.', 'Altered sedimentation.', '**Impact on Biodiversity:**', 'Shifts in plant communities.', 'Impacts on invertebrates and fish.', '**Influenced By (Stressors):**', 'Ditching and Drainage (historical and ongoing).', 'Roads and Dikes.', 'Upstream Dams and Diversions.', '**Influences (Stressors):**', 'Salinity.', 'Sedimentation.', '**Logic Description:**  Altered hydrology impacts salinity, sedimentation, and habitat.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Impact on Area"] = ''
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Impact on Biodiversity"] = 'Shifts in plant communities.\nImpacts on invertebrates and fish.\n**Influenced By (Stressors):**\nDitching and Drainage (historical and ongoing).\nRoads and Dikes.\nUpstream Dams and Diversions.\n**Influences (Stressors):**\nSalinity.\nSedimentation.\n**Logic Description:**  Altered hydrology impacts salinity, sedimentation, and habitat.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Influenced By"] = ['Ditching and Drainage (historical and ongoing).', 'Roads and Dikes.', 'Upstream Dams and Diversions.', '**Influences (Stressors):**', 'Salinity.', 'Sedimentation.', '**Logic Description:**  Altered hydrology impacts salinity, sedimentation, and habitat.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Influences"] = ['Salinity.', 'Sedimentation.', '**Logic Description:**  Altered hydrology impacts salinity, sedimentation, and habitat.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Logic Description"] = '---'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Altered Hydrology"]["Impact Function"] = "impact_altered_hydrology_aquatic_salt_marshes_north_american_atlantic_coast"

# --- Pollution ---
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Metric"] = 'Concentrations of nitrogen and phosphorus in water and sediments.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Data Sources"] = ['EPA data.', 'State environmental agencies.', 'Research publications.', '**Impact on Area:** Eutrophication.', '**Impact on Biodiversity:**', 'Changes in plant communities (can favor invasive *Phragmites*).', 'Reduced oxygen levels in the water.', '**Influenced By (Stressors):**', 'Agricultural Runoff.', 'Urban Runoff.', 'Wastewater Treatment Plants.', '**Influences (Stressors):**', 'Water Quality.', 'Plant Communities.', '**Logic Description:** Nutrient pollution (primarily nitrogen) from agriculture and urban areas is a widespread problem, leading to eutrophication and changes in marsh vegetation.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Impact on Area"] = 'Eutrophication.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Impact on Biodiversity"] = 'Changes in plant communities (can favor invasive *Phragmites*).\nReduced oxygen levels in the water.\n**Influenced By (Stressors):**\nAgricultural Runoff.\nUrban Runoff.\nWastewater Treatment Plants.\n**Influences (Stressors):**\nWater Quality.\nPlant Communities.\n**Logic Description:** Nutrient pollution (primarily nitrogen) from agriculture and urban areas is a widespread problem, leading to eutrophication and changes in marsh vegetation.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Influenced By"] = ['Agricultural Runoff.', 'Urban Runoff.', 'Wastewater Treatment Plants.', '**Influences (Stressors):**', 'Water Quality.', 'Plant Communities.', '**Logic Description:** Nutrient pollution (primarily nitrogen) from agriculture and urban areas is a widespread problem, leading to eutrophication and changes in marsh vegetation.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Influences"] = ['Water Quality.', 'Plant Communities.', '**Logic Description:** Nutrient pollution (primarily nitrogen) from agriculture and urban areas is a widespread problem, leading to eutrophication and changes in marsh vegetation.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Logic Description"] = '---'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Pollution"]["Impact Function"] = "impact_pollution_aquatic_salt_marshes_north_american_atlantic_coast"

# --- Invasive Species ---
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Metric"] = 'Extent and density of *Phragmites* stands.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Data Sources"] = ['Remote sensing.', 'Field surveys.', 'Research publications.', '**Impact on Area:**  *Phragmites* can outcompete native marsh vegetation, forming dense monocultures.', '**Impact on Biodiversity:**', 'Reduced plant diversity.', 'Loss of habitat for some native marsh animals.', 'Altered ecosystem processes.', '**Influenced By (Stressors):**', 'Disturbance:  Roads, ditches, development, nutrient enrichment often create conditions favorable for *Phragmites*.', 'Altered Hydrology.', '**Influences (Stressors):**', 'Native Plant Communities.', 'Habitat Structure.', '**Logic Description:** The invasive common reed, *Phragmites australis*, is a widespread problem in North American Atlantic Coast salt marshes, outcompeting native plants and altering habitat structure.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Impact on Area"] = '*Phragmites* can outcompete native marsh vegetation, forming dense monocultures.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Reduced plant diversity.\nLoss of habitat for some native marsh animals.\nAltered ecosystem processes.\n**Influenced By (Stressors):**\nDisturbance:  Roads, ditches, development, nutrient enrichment often create conditions favorable for *Phragmites*.\nAltered Hydrology.\n**Influences (Stressors):**\nNative Plant Communities.\nHabitat Structure.\n**Logic Description:** The invasive common reed, *Phragmites australis*, is a widespread problem in North American Atlantic Coast salt marshes, outcompeting native plants and altering habitat structure.'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Influenced By"] = ['Disturbance:  Roads, ditches, development, nutrient enrichment often create conditions favorable for *Phragmites*.', 'Altered Hydrology.', '**Influences (Stressors):**', 'Native Plant Communities.', 'Habitat Structure.', '**Logic Description:** The invasive common reed, *Phragmites australis*, is a widespread problem in North American Atlantic Coast salt marshes, outcompeting native plants and altering habitat structure.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Influences"] = ['Native Plant Communities.', 'Habitat Structure.', '**Logic Description:** The invasive common reed, *Phragmites australis*, is a widespread problem in North American Atlantic Coast salt marshes, outcompeting native plants and altering habitat structure.']
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Logic Description"] = '---'
aquatic_salt_marshes_north_american_atlantic_coast_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_aquatic_salt_marshes_north_american_atlantic_coast"

