from stressor_templates import *
import copy

aquatic_salt_marshes_european_stressors = {
    "Sea Level Rise and Coastal Squeeze": {},
    "Land Reclamation": {},
    "Pollution": copy.deepcopy(pollution_template),
}

# --- Sea Level Rise and Coastal Squeeze ---
aquatic_salt_marshes_european_stressors["Sea Level Rise and Coastal Squeeze"]["Metric"] = 'Rate of sea level rise; marsh elevation; accretion rates; length of coastline with hard defenses.'
aquatic_salt_marshes_european_stressors["Sea Level Rise and Coastal Squeeze"]["Data Sources"] = ['Tide gauge records.', 'Satellite altimetry.', 'Research publications.', 'European Environment Agency (EEA) data.', '**Impact on Area:** Inundation; erosion; loss of marsh area due to coastal squeeze.', '**Impact on Biodiversity:**', 'Habitat loss.', 'Species shifts.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', 'Coastal Development: Prevents landward migration.', 'Hard Coastal Defenses: Dikes, seawalls.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** Sea level rise is a significant threat, and *coastal squeeze* (due to extensive coastal development and hard defenses) is a *major* problem, preventing marshes from migrating inland.']
aquatic_salt_marshes_european_stressors["Sea Level Rise and Coastal Squeeze"]["Impact on Area"] = 'Inundation; erosion; loss of marsh area due to coastal squeeze.'
aquatic_salt_marshes_european_stressors["Sea Level Rise and Coastal Squeeze"]["Impact on Biodiversity"] = 'Habitat loss.\nSpecies shifts.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\nCoastal Development: Prevents landward migration.\nHard Coastal Defenses: Dikes, seawalls.\n**Influences (Stressors):**\nCoastal Erosion.\nHabitat Loss (the dominant impact).\n**Logic Description:** Sea level rise is a significant threat, and *coastal squeeze* (due to extensive coastal development and hard defenses) is a *major* problem, preventing marshes from migrating inland.'
aquatic_salt_marshes_european_stressors["Sea Level Rise and Coastal Squeeze"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', 'Coastal Development: Prevents landward migration.', 'Hard Coastal Defenses: Dikes, seawalls.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** Sea level rise is a significant threat, and *coastal squeeze* (due to extensive coastal development and hard defenses) is a *major* problem, preventing marshes from migrating inland.']
aquatic_salt_marshes_european_stressors["Sea Level Rise and Coastal Squeeze"]["Influences"] = ['Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** Sea level rise is a significant threat, and *coastal squeeze* (due to extensive coastal development and hard defenses) is a *major* problem, preventing marshes from migrating inland.']
aquatic_salt_marshes_european_stressors["Sea Level Rise and Coastal Squeeze"]["Logic Description"] = '---'

# --- Land Reclamation ---
aquatic_salt_marshes_european_stressors["Land Reclamation"]["Metric"] = 'Area of salt marsh converted to other land uses (agriculture, development) (ha/year).'
aquatic_salt_marshes_european_stressors["Land Reclamation"]["Data Sources"] = ['Historical maps and records.', 'Land-use planning data.', 'Remote sensing.', '**Impact on Area:** *Significant* historical loss of salt marsh habitat; ongoing losses in some areas.', '**Impact on Biodiversity:**', 'Habitat loss.', '**Influenced By (Stressors):**', 'Agricultural Expansion: Historically, many European salt marshes were diked and drained for agriculture.', 'Coastal Development.', '**Influences (Stressors):**', 'Habitat Loss (a major historical impact).', '**Logic Description:**  A large proportion of European salt marshes have been *historically* lost due to land reclamation for agriculture and development. This is a legacy effect that continues to influence the current state of these ecosystems.']
aquatic_salt_marshes_european_stressors["Land Reclamation"]["Impact on Area"] = '*Significant* historical loss of salt marsh habitat; ongoing losses in some areas.'
aquatic_salt_marshes_european_stressors["Land Reclamation"]["Impact on Biodiversity"] = 'Habitat loss.\n**Influenced By (Stressors):**\nAgricultural Expansion: Historically, many European salt marshes were diked and drained for agriculture.\nCoastal Development.\n**Influences (Stressors):**\nHabitat Loss (a major historical impact).\n**Logic Description:**  A large proportion of European salt marshes have been *historically* lost due to land reclamation for agriculture and development. This is a legacy effect that continues to influence the current state of these ecosystems.'
aquatic_salt_marshes_european_stressors["Land Reclamation"]["Influenced By"] = ['Agricultural Expansion: Historically, many European salt marshes were diked and drained for agriculture.', 'Coastal Development.', '**Influences (Stressors):**', 'Habitat Loss (a major historical impact).', '**Logic Description:**  A large proportion of European salt marshes have been *historically* lost due to land reclamation for agriculture and development. This is a legacy effect that continues to influence the current state of these ecosystems.']
aquatic_salt_marshes_european_stressors["Land Reclamation"]["Influences"] = ['Habitat Loss (a major historical impact).', '**Logic Description:**  A large proportion of European salt marshes have been *historically* lost due to land reclamation for agriculture and development. This is a legacy effect that continues to influence the current state of these ecosystems.']
aquatic_salt_marshes_european_stressors["Land Reclamation"]["Logic Description"] = '---'

# --- Pollution ---
aquatic_salt_marshes_european_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants'
aquatic_salt_marshes_european_stressors["Pollution"]["Data Sources"] = ['* Water Quality Monitoring', '* Research', '**Impact on Area:** Water and Sediment', '**Impact on Biodiversity:**', '* Impacts marsh plants and animals', '**Influenced By (Stressors):**', '* Industrial discharge', '*  Agricultural Runoff', '* Urban Runoff', '**Influences (Stressors):**', '* Water quality', '* Marsh health', '**Logic Description:** Pollution from industrial, agricultural, and urban sources.']
aquatic_salt_marshes_european_stressors["Pollution"]["Impact on Area"] = 'Water and Sediment'
aquatic_salt_marshes_european_stressors["Pollution"]["Impact on Biodiversity"] = '* Impacts marsh plants and animals\n**Influenced By (Stressors):**\n* Industrial discharge\n*  Agricultural Runoff\n* Urban Runoff\n**Influences (Stressors):**\n* Water quality\n* Marsh health\n**Logic Description:** Pollution from industrial, agricultural, and urban sources.'
aquatic_salt_marshes_european_stressors["Pollution"]["Influenced By"] = ['* Industrial discharge', '*  Agricultural Runoff', '* Urban Runoff', '**Influences (Stressors):**', '* Water quality', '* Marsh health', '**Logic Description:** Pollution from industrial, agricultural, and urban sources.']
aquatic_salt_marshes_european_stressors["Pollution"]["Influences"] = ['* Water quality', '* Marsh health', '**Logic Description:** Pollution from industrial, agricultural, and urban sources.']
aquatic_salt_marshes_european_stressors["Pollution"]["Logic Description"] = '---'

