from stressor_templates import *
import copy

aquatic_kelp_forests_california_stressors = {
    "Ocean Warming": {},
    "Sea Urchin Grazing / "Urchin Barrens"": {},
    "Water Pollution": copy.deepcopy(pollution_template),
}

# --- Ocean Warming ---
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Metric"] = 'Sea surface temperature (SST) (°C); frequency and severity of marine heatwaves; Degree Heating Weeks (DHW).'
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Data Sources"] = ['Satellite data (e.g., NOAA Coral Reef Watch, CoastWatch).', 'In-situ temperature loggers (e.g., from Scripps Institution of Oceanography, Monterey Bay Aquarium Research Institute - MBARI).', 'Climate models.', '**Impact on Area:** Reduced kelp growth and survival; kelp forest die-offs during extreme events (e.g., "The Blob" marine heatwave).', '**Impact on Biodiversity:**', 'Loss of habitat for many fish, invertebrates, and marine mammals.', 'Changes in community structure (shift towards more warm-tolerant species, including invasive species).', 'Increased vulnerability to other stressors.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions: Primary driver.', 'El Niño-Southern Oscillation (ENSO): El Niño events can bring warmer waters to the California coast.', '**Influences (Stressors):**', 'Sea Urchin Barrens Formation.', 'Disease outbreaks', '**Logic Description:** Rising ocean temperatures, and *especially* marine heatwaves, are a *major* threat to California kelp forests, causing widespread kelp mortality and ecosystem shifts.']
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Impact on Area"] = 'Reduced kelp growth and survival; kelp forest die-offs during extreme events (e.g., "The Blob" marine heatwave).'
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Impact on Biodiversity"] = 'Loss of habitat for many fish, invertebrates, and marine mammals.\nChanges in community structure (shift towards more warm-tolerant species, including invasive species).\nIncreased vulnerability to other stressors.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions: Primary driver.\nEl Niño-Southern Oscillation (ENSO): El Niño events can bring warmer waters to the California coast.\n**Influences (Stressors):**\nSea Urchin Barrens Formation.\nDisease outbreaks\n**Logic Description:** Rising ocean temperatures, and *especially* marine heatwaves, are a *major* threat to California kelp forests, causing widespread kelp mortality and ecosystem shifts.'
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Influenced By"] = ['Global Greenhouse Gas Emissions: Primary driver.', 'El Niño-Southern Oscillation (ENSO): El Niño events can bring warmer waters to the California coast.', '**Influences (Stressors):**', 'Sea Urchin Barrens Formation.', 'Disease outbreaks', '**Logic Description:** Rising ocean temperatures, and *especially* marine heatwaves, are a *major* threat to California kelp forests, causing widespread kelp mortality and ecosystem shifts.']
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Influences"] = ['Sea Urchin Barrens Formation.', 'Disease outbreaks', '**Logic Description:** Rising ocean temperatures, and *especially* marine heatwaves, are a *major* threat to California kelp forests, causing widespread kelp mortality and ecosystem shifts.']
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Logic Description"] = '---'
aquatic_kelp_forests_california_stressors["Ocean Warming"]["Impact Function"] = "impact_ocean_warming_aquatic_kelp_forests_california"

# --- Sea Urchin Grazing / "Urchin Barrens" ---
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Metric"] = 'Sea urchin density (number of urchins per square meter); kelp cover (percentage); presence/absence of sea otters.'
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Data Sources"] = ['Underwater surveys (diver surveys, ROVs).', 'Research studies (e.g., from universities in California).', 'Long-term monitoring programs.', '**Impact on Area:** Conversion of kelp forests to urchin barrens.', '**Impact on Biodiversity:**', 'Dramatic reduction in biodiversity.', 'Loss of habitat for many species.', '**Influenced By (Stressors):**', 'Sea Otter Decline/Absence: Sea otters are a keystone predator of sea urchins. Their decline (historically due to hunting, now recovering in some areas) is a *major* factor.', 'Overfishing of Other Urchin Predators: (e.g., sheephead fish, lobsters).', 'Ocean Warming: Can favor urchin reproduction in some cases.', '**Influences (Stressors):**', 'Kelp Forest Cover (primary impact).', '**Logic Description:** The interplay between sea otters, sea urchins, and kelp is a classic example of a trophic cascade.  Without sufficient otter predation (or predation from other species), urchin populations can explode and overgraze kelp forests, leading to the formation of urchin barrens.']
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Impact on Area"] = 'Conversion of kelp forests to urchin barrens.'
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Impact on Biodiversity"] = 'Dramatic reduction in biodiversity.\nLoss of habitat for many species.\n**Influenced By (Stressors):**\nSea Otter Decline/Absence: Sea otters are a keystone predator of sea urchins. Their decline (historically due to hunting, now recovering in some areas) is a *major* factor.\nOverfishing of Other Urchin Predators: (e.g., sheephead fish, lobsters).\nOcean Warming: Can favor urchin reproduction in some cases.\n**Influences (Stressors):**\nKelp Forest Cover (primary impact).\n**Logic Description:** The interplay between sea otters, sea urchins, and kelp is a classic example of a trophic cascade.  Without sufficient otter predation (or predation from other species), urchin populations can explode and overgraze kelp forests, leading to the formation of urchin barrens.'
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Influenced By"] = ['Sea Otter Decline/Absence: Sea otters are a keystone predator of sea urchins. Their decline (historically due to hunting, now recovering in some areas) is a *major* factor.', 'Overfishing of Other Urchin Predators: (e.g., sheephead fish, lobsters).', 'Ocean Warming: Can favor urchin reproduction in some cases.', '**Influences (Stressors):**', 'Kelp Forest Cover (primary impact).', '**Logic Description:** The interplay between sea otters, sea urchins, and kelp is a classic example of a trophic cascade.  Without sufficient otter predation (or predation from other species), urchin populations can explode and overgraze kelp forests, leading to the formation of urchin barrens.']
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Influences"] = ['Kelp Forest Cover (primary impact).', '**Logic Description:** The interplay between sea otters, sea urchins, and kelp is a classic example of a trophic cascade.  Without sufficient otter predation (or predation from other species), urchin populations can explode and overgraze kelp forests, leading to the formation of urchin barrens.']
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Logic Description"] = '---'
aquatic_kelp_forests_california_stressors["Sea Urchin Grazing / "Urchin Barrens""]["Impact Function"] = "impact_sea_urchin_grazing_/_"urchin_barrens"_aquatic_kelp_forests_california"

# --- Water Pollution ---
aquatic_kelp_forests_california_stressors["Water Pollution"]["Metric"] = 'Concentrations of nutrients (nitrogen, phosphorus), sediments, and pollutants (e.g., pesticides) in coastal waters.'
aquatic_kelp_forests_california_stressors["Water Pollution"]["Data Sources"] = ['California State Water Resources Control Board monitoring data.', 'Regional water quality monitoring programs.', 'Research studies.', '**Impact on Area:** Reduced water quality; increased turbidity.', '**Impact on Biodiversity:**', 'Nutrient enrichment can lead to algal blooms that compete with kelp.', 'Sedimentation reduces light penetration.', 'Toxic pollutants can harm kelp and other organisms.', '**Influenced By (Stressors):**', 'Agricultural Runoff.', 'Urban Runoff.', 'Deforestation (increased sediment runoff).', '**Influences (Stressors):**', 'Kelp Growth and Survival.', 'Water Clarity.', '**Logic Description:** Runoff from agriculture, urban areas, and deforested areas carries pollutants into coastal waters, reducing water quality and impacting kelp forest health.']
aquatic_kelp_forests_california_stressors["Water Pollution"]["Impact on Area"] = 'Reduced water quality; increased turbidity.'
aquatic_kelp_forests_california_stressors["Water Pollution"]["Impact on Biodiversity"] = 'Nutrient enrichment can lead to algal blooms that compete with kelp.\nSedimentation reduces light penetration.\nToxic pollutants can harm kelp and other organisms.\n**Influenced By (Stressors):**\nAgricultural Runoff.\nUrban Runoff.\nDeforestation (increased sediment runoff).\n**Influences (Stressors):**\nKelp Growth and Survival.\nWater Clarity.\n**Logic Description:** Runoff from agriculture, urban areas, and deforested areas carries pollutants into coastal waters, reducing water quality and impacting kelp forest health.'
aquatic_kelp_forests_california_stressors["Water Pollution"]["Influenced By"] = ['Agricultural Runoff.', 'Urban Runoff.', 'Deforestation (increased sediment runoff).', '**Influences (Stressors):**', 'Kelp Growth and Survival.', 'Water Clarity.', '**Logic Description:** Runoff from agriculture, urban areas, and deforested areas carries pollutants into coastal waters, reducing water quality and impacting kelp forest health.']
aquatic_kelp_forests_california_stressors["Water Pollution"]["Influences"] = ['Kelp Growth and Survival.', 'Water Clarity.', '**Logic Description:** Runoff from agriculture, urban areas, and deforested areas carries pollutants into coastal waters, reducing water quality and impacting kelp forest health.']
aquatic_kelp_forests_california_stressors["Water Pollution"]["Logic Description"] = '---'
aquatic_kelp_forests_california_stressors["Water Pollution"]["Impact Function"] = "impact_water_pollution_aquatic_kelp_forests_california"

