from stressor_templates import *
import copy

aquatic_salt_marshes_gulf_of_mexico_stressors = {
    "Sea Level Rise and Subsidence": {},
    "Altered Hydrology and Sediment Deprivation": copy.deepcopy(altered_hydrology_template),
    "Oil Spills": {},
    "Pollution": copy.deepcopy(pollution_template),
}

# --- Sea Level Rise and Subsidence ---
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Metric"] = 'Rate of relative sea level rise (mm/year); marsh elevation; accretion rates.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Data Sources"] = ['Tide gauges (NOAA).', 'Satellite altimetry.', 'Sediment cores.', 'USGS data.', '* Research', '**Impact on Area:**', '*Very high* rates of marsh loss, particularly in Louisiana.', 'Inundation and submergence.', 'Erosion.', '**Impact on Biodiversity:**', 'Extensive habitat loss.', 'Species shifts.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', 'Land Subsidence: *Extremely* significant in Louisiana due to sediment compaction, fluid withdrawal, and faulting.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** The combination of sea level rise and *high rates of land subsidence* makes the Gulf Coast, *especially Louisiana*, extremely vulnerable to marsh loss. This is one of the highest rates of coastal wetland loss in the world.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Impact on Area"] = ''
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Impact on Biodiversity"] = 'Extensive habitat loss.\nSpecies shifts.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\nLand Subsidence: *Extremely* significant in Louisiana due to sediment compaction, fluid withdrawal, and faulting.\n**Influences (Stressors):**\nCoastal Erosion.\nHabitat Loss (the dominant impact).\n**Logic Description:** The combination of sea level rise and *high rates of land subsidence* makes the Gulf Coast, *especially Louisiana*, extremely vulnerable to marsh loss. This is one of the highest rates of coastal wetland loss in the world.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', 'Land Subsidence: *Extremely* significant in Louisiana due to sediment compaction, fluid withdrawal, and faulting.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** The combination of sea level rise and *high rates of land subsidence* makes the Gulf Coast, *especially Louisiana*, extremely vulnerable to marsh loss. This is one of the highest rates of coastal wetland loss in the world.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Influences"] = ['Coastal Erosion.', 'Habitat Loss (the dominant impact).', '**Logic Description:** The combination of sea level rise and *high rates of land subsidence* makes the Gulf Coast, *especially Louisiana*, extremely vulnerable to marsh loss. This is one of the highest rates of coastal wetland loss in the world.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Logic Description"] = '---'
aquatic_salt_marshes_gulf_of_mexico_stressors["Sea Level Rise and Subsidence"]["Impact Function"] = "impact_sea_level_rise_and_subsidence_aquatic_salt_marshes_gulf_of_mexico"

# --- Altered Hydrology and Sediment Deprivation ---
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Metric"] = 'Changes in freshwater and sediment inflow; presence of levees and canals.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Data Sources"] = ['USGS river gauge data.', 'US Army Corps of Engineers (USACE) data.', 'Research publications.', '**Impact on Area:**', 'Reduced sediment delivery to marshes (especially in Louisiana).', 'Changes in salinity.', 'Marsh degradation and loss.', '**Impact on Biodiversity:**', 'Habitat loss.', 'Shifts in plant communities.', '**Influenced By (Stressors):**', 'Mississippi River Levees: Prevent sediment from reaching marshes.', 'Canals and Dredging: Alter hydrology and can lead to saltwater intrusion.', 'Upstream Dams and Diversions.', '**Influences (Stressors):**', 'Sedimentation (or lack thereof).', 'Salinity.', 'Habitat Loss.', "**Logic Description:** The levee system on the Mississippi River, while providing flood protection, prevents the natural deposition of sediment that is crucial for building and maintaining Louisiana's coastal marshes. This sediment deprivation, combined with sea level rise and subsidence, is the primary driver of land loss."]
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Impact on Area"] = ''
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Impact on Biodiversity"] = "Habitat loss.\nShifts in plant communities.\n**Influenced By (Stressors):**\nMississippi River Levees: Prevent sediment from reaching marshes.\nCanals and Dredging: Alter hydrology and can lead to saltwater intrusion.\nUpstream Dams and Diversions.\n**Influences (Stressors):**\nSedimentation (or lack thereof).\nSalinity.\nHabitat Loss.\n**Logic Description:** The levee system on the Mississippi River, while providing flood protection, prevents the natural deposition of sediment that is crucial for building and maintaining Louisiana's coastal marshes. This sediment deprivation, combined with sea level rise and subsidence, is the primary driver of land loss."
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Influenced By"] = ['Mississippi River Levees: Prevent sediment from reaching marshes.', 'Canals and Dredging: Alter hydrology and can lead to saltwater intrusion.', 'Upstream Dams and Diversions.', '**Influences (Stressors):**', 'Sedimentation (or lack thereof).', 'Salinity.', 'Habitat Loss.', "**Logic Description:** The levee system on the Mississippi River, while providing flood protection, prevents the natural deposition of sediment that is crucial for building and maintaining Louisiana's coastal marshes. This sediment deprivation, combined with sea level rise and subsidence, is the primary driver of land loss."]
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Influences"] = ['Sedimentation (or lack thereof).', 'Salinity.', 'Habitat Loss.', "**Logic Description:** The levee system on the Mississippi River, while providing flood protection, prevents the natural deposition of sediment that is crucial for building and maintaining Louisiana's coastal marshes. This sediment deprivation, combined with sea level rise and subsidence, is the primary driver of land loss."]
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Logic Description"] = '---'
aquatic_salt_marshes_gulf_of_mexico_stressors["Altered Hydrology and Sediment Deprivation"]["Impact Function"] = "impact_altered_hydrology_and_sediment_deprivation_aquatic_salt_marshes_gulf_of_mexico"

# --- Oil Spills ---
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Metric"] = 'Frequency and size of oil spills; amount of oil reaching marshes.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Data Sources"] = ['Bureau of Ocean Energy Management (BOEM).', 'NOAA.', 'Research publications.', '**Impact on Area:** Direct oiling of marshes; contamination of sediments.', '**Impact on Biodiversity:**', 'Toxic effects on plants and animals.', 'Long-term contamination of sediments.', 'Mortality', '**Influenced By (Stressors):**', 'Oil and Gas Extraction: The Gulf of Mexico is a major oil and gas producing region.', 'Shipping.', '**Influences (Stressors):**', 'Marsh Health.', 'Wildlife Mortality.', '**Logic Description:** Oil spills, both large (like Deepwater Horizon) and small, pose a recurring threat to Gulf Coast salt marshes.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Impact on Area"] = 'Direct oiling of marshes; contamination of sediments.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Impact on Biodiversity"] = 'Toxic effects on plants and animals.\nLong-term contamination of sediments.\nMortality\n**Influenced By (Stressors):**\nOil and Gas Extraction: The Gulf of Mexico is a major oil and gas producing region.\nShipping.\n**Influences (Stressors):**\nMarsh Health.\nWildlife Mortality.\n**Logic Description:** Oil spills, both large (like Deepwater Horizon) and small, pose a recurring threat to Gulf Coast salt marshes.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Influenced By"] = ['Oil and Gas Extraction: The Gulf of Mexico is a major oil and gas producing region.', 'Shipping.', '**Influences (Stressors):**', 'Marsh Health.', 'Wildlife Mortality.', '**Logic Description:** Oil spills, both large (like Deepwater Horizon) and small, pose a recurring threat to Gulf Coast salt marshes.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Influences"] = ['Marsh Health.', 'Wildlife Mortality.', '**Logic Description:** Oil spills, both large (like Deepwater Horizon) and small, pose a recurring threat to Gulf Coast salt marshes.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Logic Description"] = '---'
aquatic_salt_marshes_gulf_of_mexico_stressors["Oil Spills"]["Impact Function"] = "impact_oil_spills_aquatic_salt_marshes_gulf_of_mexico"

# --- Pollution ---
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Metric"] = 'Concentrations of nitrogen and phosphorus in water.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Data Sources"] = ['* EPA', '* State agencies.', '**Impact on Area:** Eutrophication', '**Impact on Biodiversity:**', 'Altered plant communities.', 'Can weaken plant roots, making marshes more vulnerable to erosion.', '**Influenced By (Stressors):**', '* Agricultural Runoff (from the Mississippi River watershed).', '* Urban Runoff', '**Influences (Stressors):**', '* Marsh health and stability.', '**Logic Description:** Nutrient pollution, primarily from agricultural runoff carried by the Mississippi River, can impact marsh vegetation.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Impact on Area"] = 'Eutrophication'
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Impact on Biodiversity"] = 'Altered plant communities.\nCan weaken plant roots, making marshes more vulnerable to erosion.\n**Influenced By (Stressors):**\n* Agricultural Runoff (from the Mississippi River watershed).\n* Urban Runoff\n**Influences (Stressors):**\n* Marsh health and stability.\n**Logic Description:** Nutrient pollution, primarily from agricultural runoff carried by the Mississippi River, can impact marsh vegetation.'
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Influenced By"] = ['* Agricultural Runoff (from the Mississippi River watershed).', '* Urban Runoff', '**Influences (Stressors):**', '* Marsh health and stability.', '**Logic Description:** Nutrient pollution, primarily from agricultural runoff carried by the Mississippi River, can impact marsh vegetation.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Influences"] = ['* Marsh health and stability.', '**Logic Description:** Nutrient pollution, primarily from agricultural runoff carried by the Mississippi River, can impact marsh vegetation.']
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Logic Description"] = '---'
aquatic_salt_marshes_gulf_of_mexico_stressors["Pollution"]["Impact Function"] = "impact_pollution_aquatic_salt_marshes_gulf_of_mexico"

