from stressor_templates import *
import copy

aquatic_rivers_yangtze_stressors = {
    "Three Gorges Dam": {},
    "Pollution": copy.deepcopy(pollution_template),
    "Overfishing": copy.deepcopy(overfishing_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Three Gorges Dam ---
aquatic_rivers_yangtze_stressors["Three Gorges Dam"]["Metric"] = 'Changes in river flow; sediment trapping; water levels upstream and downstream of the dam; impacts on fish populations.'
aquatic_rivers_yangtze_stressors["Three Gorges Dam"]["Data Sources"] = ['Chinese government agencies (e.g., Ministry of Water Resources).', 'Research publications (Chinese and international).', 'Environmental Impact Assessments (EIAs).', "**Impact on Area:** *Profound* alteration of the Yangtze River's hydrology and ecology.", '**Impact on Biodiversity:**', 'Blockage of fish migration routes (impacts on sturgeon and other migratory species).', 'Changes in downstream flow and sediment delivery, affecting habitats and food webs.', 'Increased risk of extinction for endangered species (e.g., Yangtze finless porpoise, Chinese paddlefish - likely extinct).', 'Changes in water temperature.', '**Influenced By (Stressors):**', 'Hydropower Generation: The primary purpose of the dam.', 'Flood Control.', 'Navigation.', '**Influences (Stressors):**', 'Fish Migration.', 'Sediment Transport.', 'Habitat Connectivity.', 'Water Quality.', 'Endangered Species Survival.', "**Logic Description:** The Three Gorges Dam, the world's largest hydropower project, has had *massive* and complex impacts on the Yangtze River ecosystem, including blocking fish migration, altering sediment transport, and contributing to the decline of endangered species. Numerous other dams, both built and planned, further compound these effects."]
aquatic_rivers_yangtze_stressors["Three Gorges Dam"]["Impact on Area"] = "*Profound* alteration of the Yangtze River's hydrology and ecology."
aquatic_rivers_yangtze_stressors["Three Gorges Dam"]["Impact on Biodiversity"] = "Blockage of fish migration routes (impacts on sturgeon and other migratory species).\nChanges in downstream flow and sediment delivery, affecting habitats and food webs.\nIncreased risk of extinction for endangered species (e.g., Yangtze finless porpoise, Chinese paddlefish - likely extinct).\nChanges in water temperature.\n**Influenced By (Stressors):**\nHydropower Generation: The primary purpose of the dam.\nFlood Control.\nNavigation.\n**Influences (Stressors):**\nFish Migration.\nSediment Transport.\nHabitat Connectivity.\nWater Quality.\nEndangered Species Survival.\n**Logic Description:** The Three Gorges Dam, the world's largest hydropower project, has had *massive* and complex impacts on the Yangtze River ecosystem, including blocking fish migration, altering sediment transport, and contributing to the decline of endangered species. Numerous other dams, both built and planned, further compound these effects."
aquatic_rivers_yangtze_stressors["Three Gorges Dam"]["Influenced By"] = ['Hydropower Generation: The primary purpose of the dam.', 'Flood Control.', 'Navigation.', '**Influences (Stressors):**', 'Fish Migration.', 'Sediment Transport.', 'Habitat Connectivity.', 'Water Quality.', 'Endangered Species Survival.', "**Logic Description:** The Three Gorges Dam, the world's largest hydropower project, has had *massive* and complex impacts on the Yangtze River ecosystem, including blocking fish migration, altering sediment transport, and contributing to the decline of endangered species. Numerous other dams, both built and planned, further compound these effects."]
aquatic_rivers_yangtze_stressors["Three Gorges Dam"]["Influences"] = ['Fish Migration.', 'Sediment Transport.', 'Habitat Connectivity.', 'Water Quality.', 'Endangered Species Survival.', "**Logic Description:** The Three Gorges Dam, the world's largest hydropower project, has had *massive* and complex impacts on the Yangtze River ecosystem, including blocking fish migration, altering sediment transport, and contributing to the decline of endangered species. Numerous other dams, both built and planned, further compound these effects."]
aquatic_rivers_yangtze_stressors["Three Gorges Dam"]["Logic Description"] = '---'

# --- Pollution ---
aquatic_rivers_yangtze_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., nutrients, heavy metals, organic pollutants, microplastics) in water and sediment.'
aquatic_rivers_yangtze_stressors["Pollution"]["Data Sources"] = ['Chinese government environmental monitoring agencies.', 'Research publications.', '**Impact on Area:** Severe water quality degradation in many parts of the river.', '**Impact on Biodiversity:**', 'Toxic effects on aquatic organisms.', 'Eutrophication (nutrient enrichment).', 'Impacts on human health (through drinking water and fish consumption).', '**Influenced By (Stressors):**', 'Industrial Discharge: From factories along the river.', 'Agricultural Runoff: Fertilizers and pesticides.', 'Urban Sewage: From rapidly growing cities.', 'Shipping Activities.', '**Influences (Stressors):**', 'Water Quality.', 'Aquatic Life Health.', 'Human Health.', '**Logic Description:** Pollution from industrial, agricultural, and urban sources is a *major* problem in the Yangtze River, degrading water quality and impacting aquatic life and human health.']
aquatic_rivers_yangtze_stressors["Pollution"]["Impact on Area"] = 'Severe water quality degradation in many parts of the river.'
aquatic_rivers_yangtze_stressors["Pollution"]["Impact on Biodiversity"] = 'Toxic effects on aquatic organisms.\nEutrophication (nutrient enrichment).\nImpacts on human health (through drinking water and fish consumption).\n**Influenced By (Stressors):**\nIndustrial Discharge: From factories along the river.\nAgricultural Runoff: Fertilizers and pesticides.\nUrban Sewage: From rapidly growing cities.\nShipping Activities.\n**Influences (Stressors):**\nWater Quality.\nAquatic Life Health.\nHuman Health.\n**Logic Description:** Pollution from industrial, agricultural, and urban sources is a *major* problem in the Yangtze River, degrading water quality and impacting aquatic life and human health.'
aquatic_rivers_yangtze_stressors["Pollution"]["Influenced By"] = ['Industrial Discharge: From factories along the river.', 'Agricultural Runoff: Fertilizers and pesticides.', 'Urban Sewage: From rapidly growing cities.', 'Shipping Activities.', '**Influences (Stressors):**', 'Water Quality.', 'Aquatic Life Health.', 'Human Health.', '**Logic Description:** Pollution from industrial, agricultural, and urban sources is a *major* problem in the Yangtze River, degrading water quality and impacting aquatic life and human health.']
aquatic_rivers_yangtze_stressors["Pollution"]["Influences"] = ['Water Quality.', 'Aquatic Life Health.', 'Human Health.', '**Logic Description:** Pollution from industrial, agricultural, and urban sources is a *major* problem in the Yangtze River, degrading water quality and impacting aquatic life and human health.']
aquatic_rivers_yangtze_stressors["Pollution"]["Logic Description"] = '---'

# --- Overfishing ---
aquatic_rivers_yangtze_stressors["Overfishing"]["Metric"] = 'Fish catches; fish population sizes; changes in fish community structure.'
aquatic_rivers_yangtze_stressors["Overfishing"]["Data Sources"] = ['Fisheries data (often limited).', 'Research publications.', '**Impact on Area:** Not directly applicable, but affects ecosystem structure.', '**Impact on Biodiversity:**', 'Decline of fish populations, including many endemic species.', 'Disruption of the food web.', '**Influenced By (Stressors):**', 'High Fishing Pressure: Due to large human populations and demand for food.', 'Destructive Fishing Practices: (e.g., electrofishing).', 'Habitat Degradation: (from pollution, dams).', '**Influences (Stressors):**', 'Fish Populations.', 'Food Web Structure.', '**Logic Description:** Overfishing, combined with other stressors, has severely depleted fish populations in the Yangtze River.']
aquatic_rivers_yangtze_stressors["Overfishing"]["Impact on Area"] = 'Not directly applicable, but affects ecosystem structure.'
aquatic_rivers_yangtze_stressors["Overfishing"]["Impact on Biodiversity"] = 'Decline of fish populations, including many endemic species.\nDisruption of the food web.\n**Influenced By (Stressors):**\nHigh Fishing Pressure: Due to large human populations and demand for food.\nDestructive Fishing Practices: (e.g., electrofishing).\nHabitat Degradation: (from pollution, dams).\n**Influences (Stressors):**\nFish Populations.\nFood Web Structure.\n**Logic Description:** Overfishing, combined with other stressors, has severely depleted fish populations in the Yangtze River.'
aquatic_rivers_yangtze_stressors["Overfishing"]["Influenced By"] = ['High Fishing Pressure: Due to large human populations and demand for food.', 'Destructive Fishing Practices: (e.g., electrofishing).', 'Habitat Degradation: (from pollution, dams).', '**Influences (Stressors):**', 'Fish Populations.', 'Food Web Structure.', '**Logic Description:** Overfishing, combined with other stressors, has severely depleted fish populations in the Yangtze River.']
aquatic_rivers_yangtze_stressors["Overfishing"]["Influences"] = ['Fish Populations.', 'Food Web Structure.', '**Logic Description:** Overfishing, combined with other stressors, has severely depleted fish populations in the Yangtze River.']
aquatic_rivers_yangtze_stressors["Overfishing"]["Logic Description"] = '---'

# --- Invasive Species ---
aquatic_rivers_yangtze_stressors["Invasive Species"]["Metric"] = 'Abundance and distribution of invasive aquatic plants and animals.'
aquatic_rivers_yangtze_stressors["Invasive Species"]["Data Sources"] = ['Research studies.', 'Monitoring programs (often limited).', '**Impact on Area:** Changes in habitat structure and ecosystem functioning.', '**Impact on Biodiversity:**', 'Competition with native species.', 'Predation on native species.', 'Alteration of food webs.', '**Influenced By (Stressors):**', 'Human Activities: (e.g., ballast water discharge, intentional introductions).', 'Altered Habitats: (dams and other changes can create conditions favorable to some invasives).', '**Influences (Stressors):**', 'Native Species Populations.', 'Ecosystem Functioning.', '**Logic Description:** Invasive species are an increasing threat to the Yangtze River ecosystem, competing with and preying on native species and altering habitats.']
aquatic_rivers_yangtze_stressors["Invasive Species"]["Impact on Area"] = 'Changes in habitat structure and ecosystem functioning.'
aquatic_rivers_yangtze_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Competition with native species.\nPredation on native species.\nAlteration of food webs.\n**Influenced By (Stressors):**\nHuman Activities: (e.g., ballast water discharge, intentional introductions).\nAltered Habitats: (dams and other changes can create conditions favorable to some invasives).\n**Influences (Stressors):**\nNative Species Populations.\nEcosystem Functioning.\n**Logic Description:** Invasive species are an increasing threat to the Yangtze River ecosystem, competing with and preying on native species and altering habitats.'
aquatic_rivers_yangtze_stressors["Invasive Species"]["Influenced By"] = ['Human Activities: (e.g., ballast water discharge, intentional introductions).', 'Altered Habitats: (dams and other changes can create conditions favorable to some invasives).', '**Influences (Stressors):**', 'Native Species Populations.', 'Ecosystem Functioning.', '**Logic Description:** Invasive species are an increasing threat to the Yangtze River ecosystem, competing with and preying on native species and altering habitats.']
aquatic_rivers_yangtze_stressors["Invasive Species"]["Influences"] = ['Native Species Populations.', 'Ecosystem Functioning.', '**Logic Description:** Invasive species are an increasing threat to the Yangtze River ecosystem, competing with and preying on native species and altering habitats.']
aquatic_rivers_yangtze_stressors["Invasive Species"]["Logic Description"] = '---'

# --- Climate Change ---
aquatic_rivers_yangtze_stressors["Climate Change"]["Metric"] = 'Water temperature; changes in precipitation patterns (amount, intensity, timing); glacier melt (in the headwaters).'
aquatic_rivers_yangtze_stressors["Climate Change"]["Data Sources"] = ['* Climate Models.', '* Historical records (temperature, precipitation, river flow).', '**Impact on Area:** Altered flow regimes; increased water temperatures; increased frequency of extreme events (floods and droughts).', '**Impact on Biodiversity:**', '* Shifts in species distributions.', '* Increased stress on aquatic organisms (particularly cold-water species).', '* Changes to growing seasons', '**Influenced By (Stressors):**', '* Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', '* Hydrology (river flow).', '* Water Temperature.', '* Extreme Weather Events.', '**Logic Description:** Climate change is impacting the Yangtze River through changes in temperature, precipitation, and glacier melt, leading to altered flow regimes, increased water temperatures, and a higher risk of extreme events, further stressing an already heavily impacted ecosystem.']
aquatic_rivers_yangtze_stressors["Climate Change"]["Impact on Area"] = 'Altered flow regimes; increased water temperatures; increased frequency of extreme events (floods and droughts).'
aquatic_rivers_yangtze_stressors["Climate Change"]["Impact on Biodiversity"] = '* Shifts in species distributions.\n* Increased stress on aquatic organisms (particularly cold-water species).\n* Changes to growing seasons\n**Influenced By (Stressors):**\n* Global Greenhouse Gas Emissions.\n**Influences (Stressors):**\n* Hydrology (river flow).\n* Water Temperature.\n* Extreme Weather Events.\n**Logic Description:** Climate change is impacting the Yangtze River through changes in temperature, precipitation, and glacier melt, leading to altered flow regimes, increased water temperatures, and a higher risk of extreme events, further stressing an already heavily impacted ecosystem.'
aquatic_rivers_yangtze_stressors["Climate Change"]["Influenced By"] = ['* Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', '* Hydrology (river flow).', '* Water Temperature.', '* Extreme Weather Events.', '**Logic Description:** Climate change is impacting the Yangtze River through changes in temperature, precipitation, and glacier melt, leading to altered flow regimes, increased water temperatures, and a higher risk of extreme events, further stressing an already heavily impacted ecosystem.']
aquatic_rivers_yangtze_stressors["Climate Change"]["Influences"] = ['* Hydrology (river flow).', '* Water Temperature.', '* Extreme Weather Events.', '**Logic Description:** Climate change is impacting the Yangtze River through changes in temperature, precipitation, and glacier melt, leading to altered flow regimes, increased water temperatures, and a higher risk of extreme events, further stressing an already heavily impacted ecosystem.']
aquatic_rivers_yangtze_stressors["Climate Change"]["Logic Description"] = '---'

