from stressor_templates import *
import copy

aquatic_abyssal_plains_stressors = {
    "Deep-Sea Mining": {},
    "Plastic Pollution": copy.deepcopy(pollution_template),
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Deep-Sea Mining ---
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Metric"] = 'Area of abyssal plain licensed for exploration or exploitation (km²); density of polymetallic nodules; amount of sediment disturbed.'
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Data Sources"] = ['International Seabed Authority (ISA).', 'National government data.', 'Research publications.', 'Environmental Impact Assessments (EIAs).', '**Impact on Area:** Removal of polymetallic nodules (which are a key habitat feature); creation of large sediment plumes.', '**Impact on Biodiversity:**', 'Loss of nodule-dwelling organisms (many of which are small and poorly known).', 'Impacts on sediment-dwelling organisms (from sediment plumes and compaction).', 'Potential for widespread and long-lasting impacts due to the slow recovery rates of abyssal ecosystems.', '**Influenced By (Stressors):**', 'Demand for Metals: (e.g., manganese, nickel, cobalt, copper).', 'Technological Advancements.', 'International Regulations.', '**Influences (Stressors):**', 'Habitat Destruction (primary impact).', 'Water Quality (sediment plumes).', '**Logic Description:** Mining for polymetallic nodules on the abyssal plains poses a significant threat, involving the removal of a key habitat feature and the creation of large sediment plumes, with potentially widespread and long-lasting impacts on the poorly understood biodiversity of this vast habitat.']
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Impact on Area"] = 'Removal of polymetallic nodules (which are a key habitat feature); creation of large sediment plumes.'
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Impact on Biodiversity"] = 'Loss of nodule-dwelling organisms (many of which are small and poorly known).\nImpacts on sediment-dwelling organisms (from sediment plumes and compaction).\nPotential for widespread and long-lasting impacts due to the slow recovery rates of abyssal ecosystems.\n**Influenced By (Stressors):**\nDemand for Metals: (e.g., manganese, nickel, cobalt, copper).\nTechnological Advancements.\nInternational Regulations.\n**Influences (Stressors):**\nHabitat Destruction (primary impact).\nWater Quality (sediment plumes).\n**Logic Description:** Mining for polymetallic nodules on the abyssal plains poses a significant threat, involving the removal of a key habitat feature and the creation of large sediment plumes, with potentially widespread and long-lasting impacts on the poorly understood biodiversity of this vast habitat.'
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Influenced By"] = ['Demand for Metals: (e.g., manganese, nickel, cobalt, copper).', 'Technological Advancements.', 'International Regulations.', '**Influences (Stressors):**', 'Habitat Destruction (primary impact).', 'Water Quality (sediment plumes).', '**Logic Description:** Mining for polymetallic nodules on the abyssal plains poses a significant threat, involving the removal of a key habitat feature and the creation of large sediment plumes, with potentially widespread and long-lasting impacts on the poorly understood biodiversity of this vast habitat.']
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Influences"] = ['Habitat Destruction (primary impact).', 'Water Quality (sediment plumes).', '**Logic Description:** Mining for polymetallic nodules on the abyssal plains poses a significant threat, involving the removal of a key habitat feature and the creation of large sediment plumes, with potentially widespread and long-lasting impacts on the poorly understood biodiversity of this vast habitat.']
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Logic Description"] = '---'
aquatic_abyssal_plains_stressors["Deep-Sea Mining"]["Impact Function"] = "impact_deep_sea_mining_aquatic_abyssal_plains"

# --- Plastic Pollution ---
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Metric"] = 'Concentrations of microplastics and macroplastics in abyssal sediments and water column.'
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Data Sources"] = ['Sampling of deep-sea sediments (using ROVs and coring devices).', 'Research studies.', '**Impact on Area:** Widespread contamination of the abyssal plain with plastic.', '**Impact on Biodiversity:**', 'Ingestion of microplastics by abyssal organisms.', 'Potential for toxic effects.', 'Potential for plastic to act as a substrate for microbial colonization.', '**Influenced By (Stressors):**', 'Land-Based Sources of Plastic Pollution.', 'Ocean Currents: Transporting plastic to the deep sea.', '**Influences (Stressors):**', 'Potential Impacts on Abyssal Food Webs.', '**Logic Description:** Even the remote abyssal plains are accumulating plastic pollution, with potential, though poorly understood, impacts on the deep-sea ecosystem.']
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Impact on Area"] = 'Widespread contamination of the abyssal plain with plastic.'
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Impact on Biodiversity"] = 'Ingestion of microplastics by abyssal organisms.\nPotential for toxic effects.\nPotential for plastic to act as a substrate for microbial colonization.\n**Influenced By (Stressors):**\nLand-Based Sources of Plastic Pollution.\nOcean Currents: Transporting plastic to the deep sea.\n**Influences (Stressors):**\nPotential Impacts on Abyssal Food Webs.\n**Logic Description:** Even the remote abyssal plains are accumulating plastic pollution, with potential, though poorly understood, impacts on the deep-sea ecosystem.'
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Influenced By"] = ['Land-Based Sources of Plastic Pollution.', 'Ocean Currents: Transporting plastic to the deep sea.', '**Influences (Stressors):**', 'Potential Impacts on Abyssal Food Webs.', '**Logic Description:** Even the remote abyssal plains are accumulating plastic pollution, with potential, though poorly understood, impacts on the deep-sea ecosystem.']
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Influences"] = ['Potential Impacts on Abyssal Food Webs.', '**Logic Description:** Even the remote abyssal plains are accumulating plastic pollution, with potential, though poorly understood, impacts on the deep-sea ecosystem.']
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Logic Description"] = '---'
aquatic_abyssal_plains_stressors["Plastic Pollution"]["Impact Function"] = "impact_plastic_pollution_aquatic_abyssal_plains"

# --- Climate Change ---
aquatic_abyssal_plains_stressors["Climate Change"]["Metric"] = 'Changes in deep ocean temperature, currents, oxygen, pH, and food supply.'
aquatic_abyssal_plains_stressors["Climate Change"]["Data Sources"] = ['* Climate models', '* Oceanographic data.', '**Impact on Area:** Changes to the physical and chemical environment.', '**Impact on Biodiversity:**', '* Potential shifts.', '* Changes in food supply.', '**Influenced By (Stressors):**', '* Global emissions.', '**Influences (Stressors):**', '* Ocean acidification.', '**Logic Description:** Climate change impacts even the deep abyssal plain.']
aquatic_abyssal_plains_stressors["Climate Change"]["Impact on Area"] = 'Changes to the physical and chemical environment.'
aquatic_abyssal_plains_stressors["Climate Change"]["Impact on Biodiversity"] = '* Potential shifts.\n* Changes in food supply.\n**Influenced By (Stressors):**\n* Global emissions.\n**Influences (Stressors):**\n* Ocean acidification.\n**Logic Description:** Climate change impacts even the deep abyssal plain.'
aquatic_abyssal_plains_stressors["Climate Change"]["Influenced By"] = ['* Global emissions.', '**Influences (Stressors):**', '* Ocean acidification.', '**Logic Description:** Climate change impacts even the deep abyssal plain.']
aquatic_abyssal_plains_stressors["Climate Change"]["Influences"] = ['* Ocean acidification.', '**Logic Description:** Climate change impacts even the deep abyssal plain.']
aquatic_abyssal_plains_stressors["Climate Change"]["Logic Description"] = '---'
aquatic_abyssal_plains_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_aquatic_abyssal_plains"

