from stressor_templates import *
import copy

aquatic_salt_marshes_san_francisco_bay_stressors = {
    "Historical Habitat Loss": {},
    "Sea Level Rise": {},
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Pollution": copy.deepcopy(pollution_template),
    "Altered Hydrology": copy.deepcopy(altered_hydrology_template),
}

# --- Historical Habitat Loss ---
aquatic_salt_marshes_san_francisco_bay_stressors["Historical Habitat Loss"]["Metric"] = 'Area of salt marsh lost since pre-development times (a *very* large percentage).'
aquatic_salt_marshes_san_francisco_bay_stressors["Historical Habitat Loss"]["Data Sources"] = ['Historical maps and records.', 'Research publications.', 'San Francisco Estuary Institute (SFEI) data.', '**Impact on Area:** *Massive* reduction in salt marsh area (over 90% in many parts of the Bay).', '**Impact on Biodiversity:**', "Loss of habitat for endangered species (e.g., salt marsh harvest mouse, Ridgway's rail).", 'Reduced nursery grounds for fish and shellfish.', 'Loss of coastal protection.', '**Influenced By (Stressors):**', 'Historical Diking and Filling: For agriculture, salt production, and urban development.  This is the *overwhelming* historical driver.', '**Influences (Stressors):**', 'Current Habitat Availability (the primary legacy).', "**Logic Description:** The San Francisco Bay has lost a *vast* majority of its historical salt marshes due to diking and filling for agriculture, salt ponds, and urban development. This historical loss is the *defining* characteristic of the ecosystem's current state and its vulnerability."]
aquatic_salt_marshes_san_francisco_bay_stressors["Historical Habitat Loss"]["Impact on Area"] = '*Massive* reduction in salt marsh area (over 90% in many parts of the Bay).'
aquatic_salt_marshes_san_francisco_bay_stressors["Historical Habitat Loss"]["Impact on Biodiversity"] = "Loss of habitat for endangered species (e.g., salt marsh harvest mouse, Ridgway's rail).\nReduced nursery grounds for fish and shellfish.\nLoss of coastal protection.\n**Influenced By (Stressors):**\nHistorical Diking and Filling: For agriculture, salt production, and urban development.  This is the *overwhelming* historical driver.\n**Influences (Stressors):**\nCurrent Habitat Availability (the primary legacy).\n**Logic Description:** The San Francisco Bay has lost a *vast* majority of its historical salt marshes due to diking and filling for agriculture, salt ponds, and urban development. This historical loss is the *defining* characteristic of the ecosystem's current state and its vulnerability."
aquatic_salt_marshes_san_francisco_bay_stressors["Historical Habitat Loss"]["Influenced By"] = ['Historical Diking and Filling: For agriculture, salt production, and urban development.  This is the *overwhelming* historical driver.', '**Influences (Stressors):**', 'Current Habitat Availability (the primary legacy).', "**Logic Description:** The San Francisco Bay has lost a *vast* majority of its historical salt marshes due to diking and filling for agriculture, salt ponds, and urban development. This historical loss is the *defining* characteristic of the ecosystem's current state and its vulnerability."]
aquatic_salt_marshes_san_francisco_bay_stressors["Historical Habitat Loss"]["Influences"] = ['Current Habitat Availability (the primary legacy).', "**Logic Description:** The San Francisco Bay has lost a *vast* majority of its historical salt marshes due to diking and filling for agriculture, salt ponds, and urban development. This historical loss is the *defining* characteristic of the ecosystem's current state and its vulnerability."]
aquatic_salt_marshes_san_francisco_bay_stressors["Historical Habitat Loss"]["Logic Description"] = '---'

# --- Sea Level Rise ---
aquatic_salt_marshes_san_francisco_bay_stressors["Sea Level Rise"]["Metric"] = 'Rate of sea level rise (mm/year); marsh elevation; accretion rates.'
aquatic_salt_marshes_san_francisco_bay_stressors["Sea Level Rise"]["Data Sources"] = ['Tide gauge records (NOAA).', 'Satellite altimetry.', 'Sediment core analysis.', 'SFEI data.', '**Impact on Area:** Inundation and erosion of remaining marshes; "coastal squeeze."', '**Impact on Biodiversity:**', 'Further habitat loss.', 'Shifts in species composition.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', 'Local Subsidence (in some areas).', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss.', '**Logic Description:** Sea level rise is a growing threat, exacerbating the impacts of historical habitat loss and making restoration efforts more challenging.  Many remaining marshes are "squeezed" between rising seas and development.']
aquatic_salt_marshes_san_francisco_bay_stressors["Sea Level Rise"]["Impact on Area"] = 'Inundation and erosion of remaining marshes; "coastal squeeze."'
aquatic_salt_marshes_san_francisco_bay_stressors["Sea Level Rise"]["Impact on Biodiversity"] = 'Further habitat loss.\nShifts in species composition.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\nLocal Subsidence (in some areas).\n**Influences (Stressors):**\nCoastal Erosion.\nHabitat Loss.\n**Logic Description:** Sea level rise is a growing threat, exacerbating the impacts of historical habitat loss and making restoration efforts more challenging.  Many remaining marshes are "squeezed" between rising seas and development.'
aquatic_salt_marshes_san_francisco_bay_stressors["Sea Level Rise"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', 'Local Subsidence (in some areas).', '**Influences (Stressors):**', 'Coastal Erosion.', 'Habitat Loss.', '**Logic Description:** Sea level rise is a growing threat, exacerbating the impacts of historical habitat loss and making restoration efforts more challenging.  Many remaining marshes are "squeezed" between rising seas and development.']
aquatic_salt_marshes_san_francisco_bay_stressors["Sea Level Rise"]["Influences"] = ['Coastal Erosion.', 'Habitat Loss.', '**Logic Description:** Sea level rise is a growing threat, exacerbating the impacts of historical habitat loss and making restoration efforts more challenging.  Many remaining marshes are "squeezed" between rising seas and development.']
aquatic_salt_marshes_san_francisco_bay_stressors["Sea Level Rise"]["Logic Description"] = '---'

# --- Invasive Species ---
aquatic_salt_marshes_san_francisco_bay_stressors["Invasive Species"]["Metric"] = 'Extent and density of invasive *Spartina* (cordgrass) stands.'
aquatic_salt_marshes_san_francisco_bay_stressors["Invasive Species"]["Data Sources"] = ['Remote sensing data (hyperspectral imagery).', 'Field surveys.', 'San Francisco Estuary Invasive Spartina Project data.', '**Impact on Area:**  *Spartina alterniflora* and its hybrids can outcompete native marsh vegetation and alter sediment dynamics.  It can *increase* overall vegetated area in some cases, but in a way that is detrimental to the native ecosystem.', '**Impact on Biodiversity:**', 'Loss of native plant diversity (especially *Spartina foliosa*, the native Pacific cordgrass).', 'Changes in habitat structure.', 'Impacts on invertebrate and bird communities (both positive and negative, depending on the species and the specific context).', '* Can increase sedimentation and elevation, but in ways that are not always beneficial.', '**Influenced By (Stressors):**', 'Intentional Introduction:  *Spartina alterniflora* was intentionally introduced for erosion control.', 'Hybridization: Hybridization with native *Spartina foliosa* has created more aggressive forms.', 'Disturbance: Altered hydrology and disturbed areas can favor *Spartina* invasion.', '**Influences (Stressors):**', 'Native Plant Communities.', 'Sediment Dynamics.', 'Habitat Structure.', '**Logic Description:** Invasive *Spartina* species, particularly hybrids between the introduced *Spartina alterniflora* and the native *Spartina foliosa*, are a major problem in San Francisco Bay, outcompeting native plants, altering mudflat and marsh habitats, and impacting wildlife.']
aquatic_salt_marshes_san_francisco_bay_stressors["Invasive Species"]["Impact on Area"] = '*Spartina alterniflora* and its hybrids can outcompete native marsh vegetation and alter sediment dynamics.  It can *increase* overall vegetated area in some cases, but in a way that is detrimental to the native ecosystem.'
aquatic_salt_marshes_san_francisco_bay_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Loss of native plant diversity (especially *Spartina foliosa*, the native Pacific cordgrass).\nChanges in habitat structure.\nImpacts on invertebrate and bird communities (both positive and negative, depending on the species and the specific context).\n* Can increase sedimentation and elevation, but in ways that are not always beneficial.\n**Influenced By (Stressors):**\nIntentional Introduction:  *Spartina alterniflora* was intentionally introduced for erosion control.\nHybridization: Hybridization with native *Spartina foliosa* has created more aggressive forms.\nDisturbance: Altered hydrology and disturbed areas can favor *Spartina* invasion.\n**Influences (Stressors):**\nNative Plant Communities.\nSediment Dynamics.\nHabitat Structure.\n**Logic Description:** Invasive *Spartina* species, particularly hybrids between the introduced *Spartina alterniflora* and the native *Spartina foliosa*, are a major problem in San Francisco Bay, outcompeting native plants, altering mudflat and marsh habitats, and impacting wildlife.'
aquatic_salt_marshes_san_francisco_bay_stressors["Invasive Species"]["Influenced By"] = ['Intentional Introduction:  *Spartina alterniflora* was intentionally introduced for erosion control.', 'Hybridization: Hybridization with native *Spartina foliosa* has created more aggressive forms.', 'Disturbance: Altered hydrology and disturbed areas can favor *Spartina* invasion.', '**Influences (Stressors):**', 'Native Plant Communities.', 'Sediment Dynamics.', 'Habitat Structure.', '**Logic Description:** Invasive *Spartina* species, particularly hybrids between the introduced *Spartina alterniflora* and the native *Spartina foliosa*, are a major problem in San Francisco Bay, outcompeting native plants, altering mudflat and marsh habitats, and impacting wildlife.']
aquatic_salt_marshes_san_francisco_bay_stressors["Invasive Species"]["Influences"] = ['Native Plant Communities.', 'Sediment Dynamics.', 'Habitat Structure.', '**Logic Description:** Invasive *Spartina* species, particularly hybrids between the introduced *Spartina alterniflora* and the native *Spartina foliosa*, are a major problem in San Francisco Bay, outcompeting native plants, altering mudflat and marsh habitats, and impacting wildlife.']
aquatic_salt_marshes_san_francisco_bay_stressors["Invasive Species"]["Logic Description"] = '---'

# --- Pollution ---
aquatic_salt_marshes_san_francisco_bay_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (nutrients, heavy metals, legacy contaminants) in water and sediment.'
aquatic_salt_marshes_san_francisco_bay_stressors["Pollution"]["Data Sources"] = ['* Water quality monitoring programs (San Francisco Bay Regional Water Quality Control Board).', '* Research Studies', '**Impact on Area:** Degraded water and sediment quality.', '**Impact on Biodiversity:**', '* Impacts on marsh plants and animals; bioaccumulation of toxins.', '**Influenced By (Stressors):**', '* Urban Runoff.', '* Industrial Discharge (historical and ongoing).', '* Legacy Pollutants: Contaminants from past industrial activities are still present in sediments.', '* Agricultural Runoff.', '**Influences (Stressors):**', '* Water and sediment quality.', '* Marsh health.', '**Logic Description:** The San Francisco Bay is surrounded by a large urban and industrial area, and pollution from runoff, industrial discharge, and legacy contaminants is a concern.']
aquatic_salt_marshes_san_francisco_bay_stressors["Pollution"]["Impact on Area"] = 'Degraded water and sediment quality.'
aquatic_salt_marshes_san_francisco_bay_stressors["Pollution"]["Impact on Biodiversity"] = '* Impacts on marsh plants and animals; bioaccumulation of toxins.\n**Influenced By (Stressors):**\n* Urban Runoff.\n* Industrial Discharge (historical and ongoing).\n* Legacy Pollutants: Contaminants from past industrial activities are still present in sediments.\n* Agricultural Runoff.\n**Influences (Stressors):**\n* Water and sediment quality.\n* Marsh health.\n**Logic Description:** The San Francisco Bay is surrounded by a large urban and industrial area, and pollution from runoff, industrial discharge, and legacy contaminants is a concern.'
aquatic_salt_marshes_san_francisco_bay_stressors["Pollution"]["Influenced By"] = ['* Urban Runoff.', '* Industrial Discharge (historical and ongoing).', '* Legacy Pollutants: Contaminants from past industrial activities are still present in sediments.', '* Agricultural Runoff.', '**Influences (Stressors):**', '* Water and sediment quality.', '* Marsh health.', '**Logic Description:** The San Francisco Bay is surrounded by a large urban and industrial area, and pollution from runoff, industrial discharge, and legacy contaminants is a concern.']
aquatic_salt_marshes_san_francisco_bay_stressors["Pollution"]["Influences"] = ['* Water and sediment quality.', '* Marsh health.', '**Logic Description:** The San Francisco Bay is surrounded by a large urban and industrial area, and pollution from runoff, industrial discharge, and legacy contaminants is a concern.']
aquatic_salt_marshes_san_francisco_bay_stressors["Pollution"]["Logic Description"] = '---'

# --- Altered Hydrology ---
aquatic_salt_marshes_san_francisco_bay_stressors["Altered Hydrology"]["Metric"] = 'Changes to tidal and freshwater flows'
aquatic_salt_marshes_san_francisco_bay_stressors["Altered Hydrology"]["Data Sources"] = ['* Water management records.', '* Research', '**Impact on Area:** Changes in salinity and sedimentation', '**Impact on Biodiversity:**', '* Species shifts', '**Influenced By (Stressors):**', '* Water diversions', '* Levees', '**Influences (Stressors):**', '* Salinity and Sedimentation', '**Logic Description:** Alterations to water flow impacts the system.']
aquatic_salt_marshes_san_francisco_bay_stressors["Altered Hydrology"]["Impact on Area"] = 'Changes in salinity and sedimentation'
aquatic_salt_marshes_san_francisco_bay_stressors["Altered Hydrology"]["Impact on Biodiversity"] = '* Species shifts\n**Influenced By (Stressors):**\n* Water diversions\n* Levees\n**Influences (Stressors):**\n* Salinity and Sedimentation\n**Logic Description:** Alterations to water flow impacts the system.'
aquatic_salt_marshes_san_francisco_bay_stressors["Altered Hydrology"]["Influenced By"] = ['* Water diversions', '* Levees', '**Influences (Stressors):**', '* Salinity and Sedimentation', '**Logic Description:** Alterations to water flow impacts the system.']
aquatic_salt_marshes_san_francisco_bay_stressors["Altered Hydrology"]["Influences"] = ['* Salinity and Sedimentation', '**Logic Description:** Alterations to water flow impacts the system.']
aquatic_salt_marshes_san_francisco_bay_stressors["Altered Hydrology"]["Logic Description"] = '---'

