from stressor_templates import *
import copy

aquatic_smaller_lakes_and_ponds_stressors = {
    "Eutrophication": {},
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Water Withdrawals": {},
    "Shoreline Development": {},
}

# --- Eutrophication ---
aquatic_smaller_lakes_and_ponds_stressors["Eutrophication"]["Metric"] = 'Nutrient concentrations (phosphorus, nitrogen); chlorophyll *a*; Secchi depth; dissolved oxygen.'
aquatic_smaller_lakes_and_ponds_stressors["Eutrophication"]["Data Sources"] = ['Local water quality monitoring programs (often citizen science-based).', 'State and local government agencies.', 'Research studies.', '**Impact on Area:** Increased algal growth; reduced water clarity; oxygen depletion.', '**Impact on Biodiversity:**', 'Harmful algal blooms (HABs).', 'Loss of submerged aquatic vegetation.', 'Fish kills.', 'Changes in species composition.', '**Influenced By (Stressors):**', 'Agricultural Runoff: Fertilizers and animal waste.', 'Urban Runoff: Sewage, stormwater, lawn fertilizers.', 'Septic Systems: Leaking septic systems.', 'Internal Loading: From sediments.', '**Influences (Stressors):**', 'Harmful Algal Blooms.', 'Oxygen Depletion.', 'Water Quality.', '**Logic Description:** Smaller lakes and ponds are *particularly vulnerable* to eutrophication due to their smaller volume and often close proximity to human activities. Nutrient pollution from agriculture, urban areas, and septic systems leads to excessive algal growth, reduced water clarity, and impacts on aquatic life.']
aquatic_smaller_lakes_and_ponds_stressors["Eutrophication"]["Impact on Area"] = 'Increased algal growth; reduced water clarity; oxygen depletion.'
aquatic_smaller_lakes_and_ponds_stressors["Eutrophication"]["Impact on Biodiversity"] = 'Harmful algal blooms (HABs).\nLoss of submerged aquatic vegetation.\nFish kills.\nChanges in species composition.\n**Influenced By (Stressors):**\nAgricultural Runoff: Fertilizers and animal waste.\nUrban Runoff: Sewage, stormwater, lawn fertilizers.\nSeptic Systems: Leaking septic systems.\nInternal Loading: From sediments.\n**Influences (Stressors):**\nHarmful Algal Blooms.\nOxygen Depletion.\nWater Quality.\n**Logic Description:** Smaller lakes and ponds are *particularly vulnerable* to eutrophication due to their smaller volume and often close proximity to human activities. Nutrient pollution from agriculture, urban areas, and septic systems leads to excessive algal growth, reduced water clarity, and impacts on aquatic life.'
aquatic_smaller_lakes_and_ponds_stressors["Eutrophication"]["Influenced By"] = ['Agricultural Runoff: Fertilizers and animal waste.', 'Urban Runoff: Sewage, stormwater, lawn fertilizers.', 'Septic Systems: Leaking septic systems.', 'Internal Loading: From sediments.', '**Influences (Stressors):**', 'Harmful Algal Blooms.', 'Oxygen Depletion.', 'Water Quality.', '**Logic Description:** Smaller lakes and ponds are *particularly vulnerable* to eutrophication due to their smaller volume and often close proximity to human activities. Nutrient pollution from agriculture, urban areas, and septic systems leads to excessive algal growth, reduced water clarity, and impacts on aquatic life.']
aquatic_smaller_lakes_and_ponds_stressors["Eutrophication"]["Influences"] = ['Harmful Algal Blooms.', 'Oxygen Depletion.', 'Water Quality.', '**Logic Description:** Smaller lakes and ponds are *particularly vulnerable* to eutrophication due to their smaller volume and often close proximity to human activities. Nutrient pollution from agriculture, urban areas, and septic systems leads to excessive algal growth, reduced water clarity, and impacts on aquatic life.']
aquatic_smaller_lakes_and_ponds_stressors["Eutrophication"]["Logic Description"] = '---'

# --- Invasive Species ---
aquatic_smaller_lakes_and_ponds_stressors["Invasive Species"]["Metric"] = 'Distribution and abundance of invasive aquatic plants (e.g., Eurasian watermilfoil, hydrilla) and animals (e.g., common carp, rusty crayfish).'
aquatic_smaller_lakes_and_ponds_stressors["Invasive Species"]["Data Sources"] = ['Local monitoring programs.', 'State and local government agencies.', 'Research studies.', '**Impact on Area:** Changes in habitat structure; reduced recreational value.', '**Impact on Biodiversity:**', 'Competition with native species.', 'Alteration of habitat.', 'Changes in food web structure.', '**Influenced By (Stressors):**', 'Recreational Boating: Transport of species between water bodies.', 'Aquarium Releases.', 'Intentional Introductions (for some species).', '**Influences (Stressors):**', 'Native Species Populations.', 'Water Quality.', 'Ecosystem Functioning.', '**Logic Description:** Invasive species can rapidly colonize and dominate smaller lakes and ponds, outcompeting native species, altering habitats, and impacting water quality.']
aquatic_smaller_lakes_and_ponds_stressors["Invasive Species"]["Impact on Area"] = 'Changes in habitat structure; reduced recreational value.'
aquatic_smaller_lakes_and_ponds_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Competition with native species.\nAlteration of habitat.\nChanges in food web structure.\n**Influenced By (Stressors):**\nRecreational Boating: Transport of species between water bodies.\nAquarium Releases.\nIntentional Introductions (for some species).\n**Influences (Stressors):**\nNative Species Populations.\nWater Quality.\nEcosystem Functioning.\n**Logic Description:** Invasive species can rapidly colonize and dominate smaller lakes and ponds, outcompeting native species, altering habitats, and impacting water quality.'
aquatic_smaller_lakes_and_ponds_stressors["Invasive Species"]["Influenced By"] = ['Recreational Boating: Transport of species between water bodies.', 'Aquarium Releases.', 'Intentional Introductions (for some species).', '**Influences (Stressors):**', 'Native Species Populations.', 'Water Quality.', 'Ecosystem Functioning.', '**Logic Description:** Invasive species can rapidly colonize and dominate smaller lakes and ponds, outcompeting native species, altering habitats, and impacting water quality.']
aquatic_smaller_lakes_and_ponds_stressors["Invasive Species"]["Influences"] = ['Native Species Populations.', 'Water Quality.', 'Ecosystem Functioning.', '**Logic Description:** Invasive species can rapidly colonize and dominate smaller lakes and ponds, outcompeting native species, altering habitats, and impacting water quality.']
aquatic_smaller_lakes_and_ponds_stressors["Invasive Species"]["Logic Description"] = '---'

# --- Water Withdrawals ---
aquatic_smaller_lakes_and_ponds_stressors["Water Withdrawals"]["Metric"] = 'Water levels; volume of water withdrawn; changes in outflow.'
aquatic_smaller_lakes_and_ponds_stressors["Water Withdrawals"]["Data Sources"] = ['Local water use records.', 'Water level monitoring.', '**Impact on Area:** Reduced water levels; potential for complete drying up in extreme cases.', '**Impact on Biodiversity:**', 'Loss of habitat.', 'Increased stress on aquatic organisms.', 'Changes in species composition.', 'Concentration of pollutants.', '**Influenced By (Stressors):**', 'Irrigation: For agriculture.', 'Residential Water Use.', 'Industrial Water Use.', 'Drought (exacerbates the problem).', '**Influences (Stressors):**', 'Water Availability.', 'Habitat Loss.', 'Water Quality.', '**Logic Description:** Water withdrawals, particularly during dry periods, can significantly reduce water levels in smaller lakes and ponds, leading to habitat loss, increased stress on aquatic life, and potentially complete drying up of the water body.']
aquatic_smaller_lakes_and_ponds_stressors["Water Withdrawals"]["Impact on Area"] = 'Reduced water levels; potential for complete drying up in extreme cases.'
aquatic_smaller_lakes_and_ponds_stressors["Water Withdrawals"]["Impact on Biodiversity"] = 'Loss of habitat.\nIncreased stress on aquatic organisms.\nChanges in species composition.\nConcentration of pollutants.\n**Influenced By (Stressors):**\nIrrigation: For agriculture.\nResidential Water Use.\nIndustrial Water Use.\nDrought (exacerbates the problem).\n**Influences (Stressors):**\nWater Availability.\nHabitat Loss.\nWater Quality.\n**Logic Description:** Water withdrawals, particularly during dry periods, can significantly reduce water levels in smaller lakes and ponds, leading to habitat loss, increased stress on aquatic life, and potentially complete drying up of the water body.'
aquatic_smaller_lakes_and_ponds_stressors["Water Withdrawals"]["Influenced By"] = ['Irrigation: For agriculture.', 'Residential Water Use.', 'Industrial Water Use.', 'Drought (exacerbates the problem).', '**Influences (Stressors):**', 'Water Availability.', 'Habitat Loss.', 'Water Quality.', '**Logic Description:** Water withdrawals, particularly during dry periods, can significantly reduce water levels in smaller lakes and ponds, leading to habitat loss, increased stress on aquatic life, and potentially complete drying up of the water body.']
aquatic_smaller_lakes_and_ponds_stressors["Water Withdrawals"]["Influences"] = ['Water Availability.', 'Habitat Loss.', 'Water Quality.', '**Logic Description:** Water withdrawals, particularly during dry periods, can significantly reduce water levels in smaller lakes and ponds, leading to habitat loss, increased stress on aquatic life, and potentially complete drying up of the water body.']
aquatic_smaller_lakes_and_ponds_stressors["Water Withdrawals"]["Logic Description"] = '---'

# --- Shoreline Development ---
aquatic_smaller_lakes_and_ponds_stressors["Shoreline Development"]["Data Sources"] = ['* Local planning and zoning records', '* Aerial photography.', '**Impact on Area**: Loss of natural shoreline', '**Impact on Biodiversity:**', '* Loss of habitat for plants, invertebrates, and fish.', '* Increased runoff and erosion.', '**Influenced By (Stressors):**', '* Human population growth', '* Desire for lakefront property', '**Influences (Stressors):**', '* Habitat loss', '* Water Quality', '**Logic Description:**  Development of shorelines removes natural buffers and habitats.']
aquatic_smaller_lakes_and_ponds_stressors["Shoreline Development"]["Impact on Biodiversity"] = '* Loss of habitat for plants, invertebrates, and fish.\n* Increased runoff and erosion.\n**Influenced By (Stressors):**\n* Human population growth\n* Desire for lakefront property\n**Influences (Stressors):**\n* Habitat loss\n* Water Quality\n**Logic Description:**  Development of shorelines removes natural buffers and habitats.'
aquatic_smaller_lakes_and_ponds_stressors["Shoreline Development"]["Influenced By"] = ['* Human population growth', '* Desire for lakefront property', '**Influences (Stressors):**', '* Habitat loss', '* Water Quality', '**Logic Description:**  Development of shorelines removes natural buffers and habitats.']
aquatic_smaller_lakes_and_ponds_stressors["Shoreline Development"]["Influences"] = ['* Habitat loss', '* Water Quality', '**Logic Description:**  Development of shorelines removes natural buffers and habitats.']
aquatic_smaller_lakes_and_ponds_stressors["Shoreline Development"]["Logic Description"] = '---'

