from stressor_templates import *
import copy

aquatic_african_great_lakes_stressors = {
    "Overfishing": copy.deepcopy(overfishing_template),
    "Sedimentation": {},
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Overfishing ---
aquatic_african_great_lakes_stressors["Overfishing"]["Metric"] = 'Fish biomass, size structure, and abundance of key species (e.g., Nile perch, cichlids); catch per unit effort.'
aquatic_african_great_lakes_stressors["Overfishing"]["Data Sources"] = ['National fisheries research institutes (of Tanzania, Uganda, Kenya, Malawi, etc.).', 'International research collaborations (e.g., LVFO - Lake Victoria Fisheries Organization).', 'Fisheries data (often incomplete).', 'Underwater surveys.', '**Impact on Area:** Not directly applicable, but major impacts on ecosystem structure.', '**Impact on Biodiversity:**', 'Decline of important fish species, including both commercially important species and endemic cichlids.', 'Disruption of food webs.', 'Loss of biodiversity (particularly in Lake Victoria, where many cichlid species have gone extinct).', '**Influenced By (Stressors):**', 'High Fishing Pressure: Due to large human populations dependent on fishing.', 'Use of Destructive Fishing Gear: (e.g., small mesh nets).', 'Weak Enforcement of Fisheries Regulations.', 'Lack of Alternative Livelihoods.', '**Influences (Stressors):**', 'Food Web Structure.', 'Fish Populations.', 'Lake Ecosystem Health.', '**Logic Description:** Overfishing is a *severe* and widespread problem in the African Great Lakes, driven by high fishing pressure, destructive fishing practices, and weak governance, leading to the decline of fish populations and the disruption of lake ecosystems.']
aquatic_african_great_lakes_stressors["Overfishing"]["Impact on Area"] = 'Not directly applicable, but major impacts on ecosystem structure.'
aquatic_african_great_lakes_stressors["Overfishing"]["Impact on Biodiversity"] = 'Decline of important fish species, including both commercially important species and endemic cichlids.\nDisruption of food webs.\nLoss of biodiversity (particularly in Lake Victoria, where many cichlid species have gone extinct).\n**Influenced By (Stressors):**\nHigh Fishing Pressure: Due to large human populations dependent on fishing.\nUse of Destructive Fishing Gear: (e.g., small mesh nets).\nWeak Enforcement of Fisheries Regulations.\nLack of Alternative Livelihoods.\n**Influences (Stressors):**\nFood Web Structure.\nFish Populations.\nLake Ecosystem Health.\n**Logic Description:** Overfishing is a *severe* and widespread problem in the African Great Lakes, driven by high fishing pressure, destructive fishing practices, and weak governance, leading to the decline of fish populations and the disruption of lake ecosystems.'
aquatic_african_great_lakes_stressors["Overfishing"]["Influenced By"] = ['High Fishing Pressure: Due to large human populations dependent on fishing.', 'Use of Destructive Fishing Gear: (e.g., small mesh nets).', 'Weak Enforcement of Fisheries Regulations.', 'Lack of Alternative Livelihoods.', '**Influences (Stressors):**', 'Food Web Structure.', 'Fish Populations.', 'Lake Ecosystem Health.', '**Logic Description:** Overfishing is a *severe* and widespread problem in the African Great Lakes, driven by high fishing pressure, destructive fishing practices, and weak governance, leading to the decline of fish populations and the disruption of lake ecosystems.']
aquatic_african_great_lakes_stressors["Overfishing"]["Influences"] = ['Food Web Structure.', 'Fish Populations.', 'Lake Ecosystem Health.', '**Logic Description:** Overfishing is a *severe* and widespread problem in the African Great Lakes, driven by high fishing pressure, destructive fishing practices, and weak governance, leading to the decline of fish populations and the disruption of lake ecosystems.']
aquatic_african_great_lakes_stressors["Overfishing"]["Logic Description"] = '---'
aquatic_african_great_lakes_stressors["Overfishing"]["Impact Function"] = "impact_overfishing_aquatic_african_great_lakes"

# --- Sedimentation ---
aquatic_african_great_lakes_stressors["Sedimentation"]["Metric"] = 'Sediment load in rivers flowing into the lakes; turbidity (water cloudiness); sedimentation rates in the lakes.'
aquatic_african_great_lakes_stressors["Sedimentation"]["Data Sources"] = ['National research institutes.', 'International research collaborations.', 'Remote sensing data.', '**Impact on Area:** Reduced water clarity; smothering of benthic habitats.', '**Impact on Biodiversity:**', 'Loss of submerged aquatic vegetation.', 'Impacts on fish spawning and feeding grounds.', 'Reduced light penetration.', 'Harm to benthic organisms.', '**Influenced By (Stressors):**', 'Deforestation: In the watersheds surrounding the lakes.', 'Agricultural Practices: Poor soil conservation practices.', 'Population Growth: Leading to increased land clearing.', '**Influences (Stressors):**', 'Water Quality.', 'Habitat Loss.', 'Lake Ecosystem Health.', '**Logic Description:** Increased sedimentation, primarily due to deforestation and poor agricultural practices in the watersheds surrounding the lakes, is a major threat, reducing water clarity, smothering habitats, and impacting aquatic life.']
aquatic_african_great_lakes_stressors["Sedimentation"]["Impact on Area"] = 'Reduced water clarity; smothering of benthic habitats.'
aquatic_african_great_lakes_stressors["Sedimentation"]["Impact on Biodiversity"] = 'Loss of submerged aquatic vegetation.\nImpacts on fish spawning and feeding grounds.\nReduced light penetration.\nHarm to benthic organisms.\n**Influenced By (Stressors):**\nDeforestation: In the watersheds surrounding the lakes.\nAgricultural Practices: Poor soil conservation practices.\nPopulation Growth: Leading to increased land clearing.\n**Influences (Stressors):**\nWater Quality.\nHabitat Loss.\nLake Ecosystem Health.\n**Logic Description:** Increased sedimentation, primarily due to deforestation and poor agricultural practices in the watersheds surrounding the lakes, is a major threat, reducing water clarity, smothering habitats, and impacting aquatic life.'
aquatic_african_great_lakes_stressors["Sedimentation"]["Influenced By"] = ['Deforestation: In the watersheds surrounding the lakes.', 'Agricultural Practices: Poor soil conservation practices.', 'Population Growth: Leading to increased land clearing.', '**Influences (Stressors):**', 'Water Quality.', 'Habitat Loss.', 'Lake Ecosystem Health.', '**Logic Description:** Increased sedimentation, primarily due to deforestation and poor agricultural practices in the watersheds surrounding the lakes, is a major threat, reducing water clarity, smothering habitats, and impacting aquatic life.']
aquatic_african_great_lakes_stressors["Sedimentation"]["Influences"] = ['Water Quality.', 'Habitat Loss.', 'Lake Ecosystem Health.', '**Logic Description:** Increased sedimentation, primarily due to deforestation and poor agricultural practices in the watersheds surrounding the lakes, is a major threat, reducing water clarity, smothering habitats, and impacting aquatic life.']
aquatic_african_great_lakes_stressors["Sedimentation"]["Logic Description"] = '---'
aquatic_african_great_lakes_stressors["Sedimentation"]["Impact Function"] = "impact_sedimentation_aquatic_african_great_lakes"

# --- Invasive Species ---
aquatic_african_great_lakes_stressors["Invasive Species"]["Metric"] = 'Distribution and abundance of key invasive species (e.g., water hyacinth, Nile perch (in Lake Victoria)).'
aquatic_african_great_lakes_stressors["Invasive Species"]["Data Sources"] = ['National research institutes.', 'International research collaborations.', 'Monitoring programs.', '**Impact on Area:** Significant impacts on lake ecosystems (especially Lake Victoria).', '**Impact on Biodiversity:**', 'Water hyacinth: Forms dense mats, blocking sunlight, reducing oxygen levels, and hindering navigation.', 'Nile perch (Lake Victoria): Predation on native cichlids, leading to widespread extinctions.', '**Influenced By (Stressors):**', 'Intentional Introductions: (e.g., Nile perch in Lake Victoria).', 'Accidental Introductions.', 'Lack of Natural Controls.', '**Influences (Stressors):**', 'Water Quality (water hyacinth).', 'Fish Populations (Nile perch).', 'Ecosystem Structure.', '**Logic Description:** Invasive species, such as water hyacinth and Nile perch (in Lake Victoria), have had devastating impacts on the African Great Lakes, disrupting ecosystems and causing significant ecological and economic damage.']
aquatic_african_great_lakes_stressors["Invasive Species"]["Impact on Area"] = 'Significant impacts on lake ecosystems (especially Lake Victoria).'
aquatic_african_great_lakes_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Water hyacinth: Forms dense mats, blocking sunlight, reducing oxygen levels, and hindering navigation.\nNile perch (Lake Victoria): Predation on native cichlids, leading to widespread extinctions.\n**Influenced By (Stressors):**\nIntentional Introductions: (e.g., Nile perch in Lake Victoria).\nAccidental Introductions.\nLack of Natural Controls.\n**Influences (Stressors):**\nWater Quality (water hyacinth).\nFish Populations (Nile perch).\nEcosystem Structure.\n**Logic Description:** Invasive species, such as water hyacinth and Nile perch (in Lake Victoria), have had devastating impacts on the African Great Lakes, disrupting ecosystems and causing significant ecological and economic damage.'
aquatic_african_great_lakes_stressors["Invasive Species"]["Influenced By"] = ['Intentional Introductions: (e.g., Nile perch in Lake Victoria).', 'Accidental Introductions.', 'Lack of Natural Controls.', '**Influences (Stressors):**', 'Water Quality (water hyacinth).', 'Fish Populations (Nile perch).', 'Ecosystem Structure.', '**Logic Description:** Invasive species, such as water hyacinth and Nile perch (in Lake Victoria), have had devastating impacts on the African Great Lakes, disrupting ecosystems and causing significant ecological and economic damage.']
aquatic_african_great_lakes_stressors["Invasive Species"]["Influences"] = ['Water Quality (water hyacinth).', 'Fish Populations (Nile perch).', 'Ecosystem Structure.', '**Logic Description:** Invasive species, such as water hyacinth and Nile perch (in Lake Victoria), have had devastating impacts on the African Great Lakes, disrupting ecosystems and causing significant ecological and economic damage.']
aquatic_african_great_lakes_stressors["Invasive Species"]["Logic Description"] = '---'
aquatic_african_great_lakes_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_aquatic_african_great_lakes"

# --- Climate Change ---
aquatic_african_great_lakes_stressors["Climate Change"]["Metric"] = 'Water temperature; changes in rainfall patterns; changes in lake levels.'
aquatic_african_great_lakes_stressors["Climate Change"]["Data Sources"] = ['National research institutes.', 'International research collaborations.', 'Climate models.', '**Impact on Area:** Changes in water temperature, lake levels, and stratification patterns.', '**Impact on Biodiversity:**', 'Potential shifts in species distributions.', 'Increased stress on aquatic organisms.', 'Changes in food web dynamics.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Water Levels.', 'Lake Stratification.', 'Ecosystem Functioning.', '**Logic Description:** Climate change is an emerging threat to the African Great Lakes, with potential impacts on water temperature, lake levels, and ecosystem dynamics.']
aquatic_african_great_lakes_stressors["Climate Change"]["Impact on Area"] = 'Changes in water temperature, lake levels, and stratification patterns.'
aquatic_african_great_lakes_stressors["Climate Change"]["Impact on Biodiversity"] = 'Potential shifts in species distributions.\nIncreased stress on aquatic organisms.\nChanges in food web dynamics.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nWater Levels.\nLake Stratification.\nEcosystem Functioning.\n**Logic Description:** Climate change is an emerging threat to the African Great Lakes, with potential impacts on water temperature, lake levels, and ecosystem dynamics.'
aquatic_african_great_lakes_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Water Levels.', 'Lake Stratification.', 'Ecosystem Functioning.', '**Logic Description:** Climate change is an emerging threat to the African Great Lakes, with potential impacts on water temperature, lake levels, and ecosystem dynamics.']
aquatic_african_great_lakes_stressors["Climate Change"]["Influences"] = ['Water Levels.', 'Lake Stratification.', 'Ecosystem Functioning.', '**Logic Description:** Climate change is an emerging threat to the African Great Lakes, with potential impacts on water temperature, lake levels, and ecosystem dynamics.']
aquatic_african_great_lakes_stressors["Climate Change"]["Logic Description"] = '---'
aquatic_african_great_lakes_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_aquatic_african_great_lakes"

