from stressor_templates import *
import copy

aquatic_pelagic_open_ocean_stressors = {
    "Overfishing": copy.deepcopy(overfishing_template),
    "Climate Change": copy.deepcopy(climate_change_template),
    "Plastic Pollution": copy.deepcopy(pollution_template),
    "Chemical Pollution": copy.deepcopy(pollution_template),
    "Noise Pollution": copy.deepcopy(pollution_template),
}

# --- Overfishing ---
aquatic_pelagic_open_ocean_stressors["Overfishing"]["Metric"] = 'Fish catches (tonnes/year); fishing effort (e.g., number of vessels, days at sea); stock assessments (estimates of fish population size and biomass); bycatch (amount of non-target species caught).'
aquatic_pelagic_open_ocean_stressors["Overfishing"]["Data Sources"] = ['Fisheries data (reported catches, often incomplete).', 'Stock assessments (conducted by regional fisheries management organizations - RFMOs - and national agencies).', 'Scientific research (e.g., using tagging studies to track fish movements).', 'Observer programs (placing observers on fishing vessels to monitor catches and bycatch).', '**Impact on Area:** Not directly applicable (fishing occurs throughout the water column), but affects the entire ecosystem.', '**Impact on Biodiversity:**', 'Depletion of fish stocks (target species and bycatch).', 'Changes in the structure of marine food webs (e.g., removal of top predators).', 'Impacts on seabirds, marine mammals, and sea turtles (through bycatch and competition for food).', 'Loss of genetic diversity within fish populations.', '**Influenced By (Stressors):**', 'Global Demand for Seafood: Growing human population and increasing per capita consumption.', 'Fishing Technology: Advances in fishing gear and vessel capabilities.', 'Subsidies: Government subsidies can encourage overfishing.', 'Illegal, Unreported, and Unregulated (IUU) Fishing.', 'Weak Governance and Enforcement: Ineffective management of fisheries.', '**Influences (Stressors):**', 'Marine Food Webs: Disrupts trophic relationships.', 'Ecosystem Functioning.', '**Logic Description:** Overfishing is a major threat to the open ocean, depleting fish stocks, altering food web structure, and impacting a wide range of marine species.']
aquatic_pelagic_open_ocean_stressors["Overfishing"]["Impact on Area"] = 'Not directly applicable (fishing occurs throughout the water column), but affects the entire ecosystem.'
aquatic_pelagic_open_ocean_stressors["Overfishing"]["Impact on Biodiversity"] = 'Depletion of fish stocks (target species and bycatch).\nChanges in the structure of marine food webs (e.g., removal of top predators).\nImpacts on seabirds, marine mammals, and sea turtles (through bycatch and competition for food).\nLoss of genetic diversity within fish populations.\n**Influenced By (Stressors):**\nGlobal Demand for Seafood: Growing human population and increasing per capita consumption.\nFishing Technology: Advances in fishing gear and vessel capabilities.\nSubsidies: Government subsidies can encourage overfishing.\nIllegal, Unreported, and Unregulated (IUU) Fishing.\nWeak Governance and Enforcement: Ineffective management of fisheries.\n**Influences (Stressors):**\nMarine Food Webs: Disrupts trophic relationships.\nEcosystem Functioning.\n**Logic Description:** Overfishing is a major threat to the open ocean, depleting fish stocks, altering food web structure, and impacting a wide range of marine species.'
aquatic_pelagic_open_ocean_stressors["Overfishing"]["Influenced By"] = ['Global Demand for Seafood: Growing human population and increasing per capita consumption.', 'Fishing Technology: Advances in fishing gear and vessel capabilities.', 'Subsidies: Government subsidies can encourage overfishing.', 'Illegal, Unreported, and Unregulated (IUU) Fishing.', 'Weak Governance and Enforcement: Ineffective management of fisheries.', '**Influences (Stressors):**', 'Marine Food Webs: Disrupts trophic relationships.', 'Ecosystem Functioning.', '**Logic Description:** Overfishing is a major threat to the open ocean, depleting fish stocks, altering food web structure, and impacting a wide range of marine species.']
aquatic_pelagic_open_ocean_stressors["Overfishing"]["Influences"] = ['Marine Food Webs: Disrupts trophic relationships.', 'Ecosystem Functioning.', '**Logic Description:** Overfishing is a major threat to the open ocean, depleting fish stocks, altering food web structure, and impacting a wide range of marine species.']
aquatic_pelagic_open_ocean_stressors["Overfishing"]["Logic Description"] = '---'

# --- Climate Change ---
aquatic_pelagic_open_ocean_stressors["Climate Change"]["Metric"] = 'Sea surface temperature (SST) (°C); ocean acidification (pH); changes in ocean currents; changes in stratification (layering of the water column); oxygen minimum zone expansion.'
aquatic_pelagic_open_ocean_stressors["Climate Change"]["Data Sources"] = ['Climate models.', 'Oceanographic data (buoys, ships, satellites).', 'Historical records.', '**Impact on Area:** Widespread changes in ocean conditions.', '**Impact on Biodiversity:**', 'Shifts in species distributions (as species track suitable temperatures).', 'Increased stress on marine organisms (due to warming, acidification, and reduced oxygen).', 'Changes in phenology (timing of biological events).', 'Impacts on primary productivity (phytoplankton growth).', 'Increased frequency and intensity of marine heatwaves.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Ocean Acidification.', 'Ocean Currents.', 'Stratification.', 'Oxygen Minimum Zones.', '**Logic Description:** Climate change is causing widespread and fundamental changes to the open ocean, impacting temperature, acidity, currents, stratification, and oxygen levels, with cascading effects on marine life.']
aquatic_pelagic_open_ocean_stressors["Climate Change"]["Impact on Area"] = 'Widespread changes in ocean conditions.'
aquatic_pelagic_open_ocean_stressors["Climate Change"]["Impact on Biodiversity"] = 'Shifts in species distributions (as species track suitable temperatures).\nIncreased stress on marine organisms (due to warming, acidification, and reduced oxygen).\nChanges in phenology (timing of biological events).\nImpacts on primary productivity (phytoplankton growth).\nIncreased frequency and intensity of marine heatwaves.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nOcean Acidification.\nOcean Currents.\nStratification.\nOxygen Minimum Zones.\n**Logic Description:** Climate change is causing widespread and fundamental changes to the open ocean, impacting temperature, acidity, currents, stratification, and oxygen levels, with cascading effects on marine life.'
aquatic_pelagic_open_ocean_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Ocean Acidification.', 'Ocean Currents.', 'Stratification.', 'Oxygen Minimum Zones.', '**Logic Description:** Climate change is causing widespread and fundamental changes to the open ocean, impacting temperature, acidity, currents, stratification, and oxygen levels, with cascading effects on marine life.']
aquatic_pelagic_open_ocean_stressors["Climate Change"]["Influences"] = ['Ocean Acidification.', 'Ocean Currents.', 'Stratification.', 'Oxygen Minimum Zones.', '**Logic Description:** Climate change is causing widespread and fundamental changes to the open ocean, impacting temperature, acidity, currents, stratification, and oxygen levels, with cascading effects on marine life.']
aquatic_pelagic_open_ocean_stressors["Climate Change"]["Logic Description"] = '---'

# --- Plastic Pollution ---
aquatic_pelagic_open_ocean_stressors["Plastic Pollution"]["Metric"] = 'Concentrations of plastic debris (macroplastics, microplastics) in surface waters, the water column, and sediments; abundance of plastic ingested by marine organisms.'
aquatic_pelagic_open_ocean_stressors["Plastic Pollution"]["Data Sources"] = ['Surface water sampling (using nets).', 'Beach surveys.', 'Analysis of the stomach contents of marine animals.', 'Research studies.', '**Impact on Area:** Widespread contamination of the ocean with plastic.', '**Impact on Biodiversity:**', 'Entanglement of marine animals (e.g., seabirds, turtles, marine mammals).', 'Ingestion of plastic by marine animals (leading to starvation, blockage of digestive tracts, and exposure to toxic chemicals).', 'Potential for microplastics to accumulate in the food chain.', 'Transport of invasive species (on plastic debris).', '**Influenced By (Stressors):**', 'Land-Based Sources: Improper waste disposal, runoff from rivers.', 'Shipping Activities.', 'Fishing Gear (lost or discarded).', '**Influences (Stressors):**', '* Wildlife mortality', '**Logic Description:** Plastic pollution is a pervasive problem in the open ocean, impacting marine life through entanglement, ingestion, and the potential for toxic effects.']
aquatic_pelagic_open_ocean_stressors["Plastic Pollution"]["Impact on Area"] = 'Widespread contamination of the ocean with plastic.'
aquatic_pelagic_open_ocean_stressors["Plastic Pollution"]["Impact on Biodiversity"] = 'Entanglement of marine animals (e.g., seabirds, turtles, marine mammals).\nIngestion of plastic by marine animals (leading to starvation, blockage of digestive tracts, and exposure to toxic chemicals).\nPotential for microplastics to accumulate in the food chain.\nTransport of invasive species (on plastic debris).\n**Influenced By (Stressors):**\nLand-Based Sources: Improper waste disposal, runoff from rivers.\nShipping Activities.\nFishing Gear (lost or discarded).\n**Influences (Stressors):**\n* Wildlife mortality\n**Logic Description:** Plastic pollution is a pervasive problem in the open ocean, impacting marine life through entanglement, ingestion, and the potential for toxic effects.'
aquatic_pelagic_open_ocean_stressors["Plastic Pollution"]["Influenced By"] = ['Land-Based Sources: Improper waste disposal, runoff from rivers.', 'Shipping Activities.', 'Fishing Gear (lost or discarded).', '**Influences (Stressors):**', '* Wildlife mortality', '**Logic Description:** Plastic pollution is a pervasive problem in the open ocean, impacting marine life through entanglement, ingestion, and the potential for toxic effects.']
aquatic_pelagic_open_ocean_stressors["Plastic Pollution"]["Influences"] = ['* Wildlife mortality', '**Logic Description:** Plastic pollution is a pervasive problem in the open ocean, impacting marine life through entanglement, ingestion, and the potential for toxic effects.']
aquatic_pelagic_open_ocean_stressors["Plastic Pollution"]["Logic Description"] = '---'

# --- Chemical Pollution ---
aquatic_pelagic_open_ocean_stressors["Chemical Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., heavy metals, persistent organic pollutants (POPs), oil) in seawater, sediments, and marine organisms.'
aquatic_pelagic_open_ocean_stressors["Chemical Pollution"]["Data Sources"] = ['Water quality monitoring programs.', 'Sediment analysis.', 'Analysis of tissues from marine organisms.', 'Research studies.', '**Impact on Area:** Contamination of the ocean environment.', '**Impact on Biodiversity:**', 'Toxic effects on marine organisms (e.g., reproductive impairment, immune suppression).', 'Bioaccumulation of pollutants in the food chain (leading to higher concentrations in top predators).', '**Influenced By (Stressors):**', 'Industrial Discharge.', 'Agricultural Runoff.', 'Shipping Activities (oil spills, discharge of waste).', 'Atmospheric Deposition: Pollutants can travel long distances through the air.', '**Influences (Stressors):**', '* Wildlife health', '**Logic Description:** Chemical pollution from various sources contaminates the open ocean, impacting marine life through toxic effects and bioaccumulation.']
aquatic_pelagic_open_ocean_stressors["Chemical Pollution"]["Impact on Area"] = 'Contamination of the ocean environment.'
aquatic_pelagic_open_ocean_stressors["Chemical Pollution"]["Impact on Biodiversity"] = 'Toxic effects on marine organisms (e.g., reproductive impairment, immune suppression).\nBioaccumulation of pollutants in the food chain (leading to higher concentrations in top predators).\n**Influenced By (Stressors):**\nIndustrial Discharge.\nAgricultural Runoff.\nShipping Activities (oil spills, discharge of waste).\nAtmospheric Deposition: Pollutants can travel long distances through the air.\n**Influences (Stressors):**\n* Wildlife health\n**Logic Description:** Chemical pollution from various sources contaminates the open ocean, impacting marine life through toxic effects and bioaccumulation.'
aquatic_pelagic_open_ocean_stressors["Chemical Pollution"]["Influenced By"] = ['Industrial Discharge.', 'Agricultural Runoff.', 'Shipping Activities (oil spills, discharge of waste).', 'Atmospheric Deposition: Pollutants can travel long distances through the air.', '**Influences (Stressors):**', '* Wildlife health', '**Logic Description:** Chemical pollution from various sources contaminates the open ocean, impacting marine life through toxic effects and bioaccumulation.']
aquatic_pelagic_open_ocean_stressors["Chemical Pollution"]["Influences"] = ['* Wildlife health', '**Logic Description:** Chemical pollution from various sources contaminates the open ocean, impacting marine life through toxic effects and bioaccumulation.']
aquatic_pelagic_open_ocean_stressors["Chemical Pollution"]["Logic Description"] = '---'

# --- Noise Pollution ---
aquatic_pelagic_open_ocean_stressors["Noise Pollution"]["Metric"] = 'Ambient noise levels; frequency and intensity of anthropogenic noise.'
aquatic_pelagic_open_ocean_stressors["Noise Pollution"]["Data Sources"] = ['* Hydrophones', '* Research', '**Impact on Area:** Increased noise levels in the ocean.', '**Impact on Biodiversity:**', '* Interference with communication', 'Behavioral changes.', '* Stress', 'Hearing damage (in extreme cases).', '**Influenced By (Stressors):**', '* Shipping', '* Sonar', '* Seismic surveys', '* Construction', '**Influences (Stressors):**', '* Marine mammal behavior and communication', '**Logic Description:** Noise pollution from shipping, sonar, and other human activities can interfere with marine animal communication, navigation, and behavior.']
aquatic_pelagic_open_ocean_stressors["Noise Pollution"]["Impact on Area"] = 'Increased noise levels in the ocean.'
aquatic_pelagic_open_ocean_stressors["Noise Pollution"]["Impact on Biodiversity"] = '* Interference with communication\nBehavioral changes.\n* Stress\nHearing damage (in extreme cases).\n**Influenced By (Stressors):**\n* Shipping\n* Sonar\n* Seismic surveys\n* Construction\n**Influences (Stressors):**\n* Marine mammal behavior and communication\n**Logic Description:** Noise pollution from shipping, sonar, and other human activities can interfere with marine animal communication, navigation, and behavior.'
aquatic_pelagic_open_ocean_stressors["Noise Pollution"]["Influenced By"] = ['* Shipping', '* Sonar', '* Seismic surveys', '* Construction', '**Influences (Stressors):**', '* Marine mammal behavior and communication', '**Logic Description:** Noise pollution from shipping, sonar, and other human activities can interfere with marine animal communication, navigation, and behavior.']
aquatic_pelagic_open_ocean_stressors["Noise Pollution"]["Influences"] = ['* Marine mammal behavior and communication', '**Logic Description:** Noise pollution from shipping, sonar, and other human activities can interfere with marine animal communication, navigation, and behavior.']
aquatic_pelagic_open_ocean_stressors["Noise Pollution"]["Logic Description"] = '---'

