from stressor_templates import *
import copy

aquatic_mangrove_southeast_asian_stressors = {
    "Aquaculture Expansion": {},
    "Deforestation": copy.deepcopy(deforestation_template),
    "Pollution": copy.deepcopy(pollution_template),
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Aquaculture Expansion ---
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Metric"] = 'Area of mangroves converted to aquaculture ponds (primarily shrimp farms) (ha/year).'
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Data Sources"] = ['Remote sensing data.', 'Government statistics (Indonesia, Malaysia, Thailand, Vietnam, etc.).', 'Research publications.', '**Impact on Area:** *Massive* loss of mangrove habitat. This is the *dominant* driver of mangrove loss in Southeast Asia.', '**Impact on Biodiversity:**', 'Loss of habitat for a wide range of species.', 'Reduced nursery grounds for fish and shellfish.', 'Loss of coastal protection.', 'Water pollution from aquaculture effluent.', '**Influenced By (Stressors):**', 'Global Demand for Shrimp: A major economic driver.', 'Government Policies: Promotion of aquaculture development (in some cases).', 'Lack of Enforcement of Environmental Regulations.', 'Poverty and Lack of Alternative Livelihoods.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Water Quality (pollution from ponds).', 'Habitat Loss (the primary impact).', '**Logic Description:** The conversion of mangroves to aquaculture ponds, primarily for shrimp farming, is the *single largest cause* of mangrove loss in Southeast Asia. This has devastating impacts on biodiversity, coastal protection, and water quality.']
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Impact on Area"] = '*Massive* loss of mangrove habitat. This is the *dominant* driver of mangrove loss in Southeast Asia.'
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Impact on Biodiversity"] = 'Loss of habitat for a wide range of species.\nReduced nursery grounds for fish and shellfish.\nLoss of coastal protection.\nWater pollution from aquaculture effluent.\n**Influenced By (Stressors):**\nGlobal Demand for Shrimp: A major economic driver.\nGovernment Policies: Promotion of aquaculture development (in some cases).\nLack of Enforcement of Environmental Regulations.\nPoverty and Lack of Alternative Livelihoods.\n**Influences (Stressors):**\nCoastal Erosion.\nWater Quality (pollution from ponds).\nHabitat Loss (the primary impact).\n**Logic Description:** The conversion of mangroves to aquaculture ponds, primarily for shrimp farming, is the *single largest cause* of mangrove loss in Southeast Asia. This has devastating impacts on biodiversity, coastal protection, and water quality.'
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Influenced By"] = ['Global Demand for Shrimp: A major economic driver.', 'Government Policies: Promotion of aquaculture development (in some cases).', 'Lack of Enforcement of Environmental Regulations.', 'Poverty and Lack of Alternative Livelihoods.', '**Influences (Stressors):**', 'Coastal Erosion.', 'Water Quality (pollution from ponds).', 'Habitat Loss (the primary impact).', '**Logic Description:** The conversion of mangroves to aquaculture ponds, primarily for shrimp farming, is the *single largest cause* of mangrove loss in Southeast Asia. This has devastating impacts on biodiversity, coastal protection, and water quality.']
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Influences"] = ['Coastal Erosion.', 'Water Quality (pollution from ponds).', 'Habitat Loss (the primary impact).', '**Logic Description:** The conversion of mangroves to aquaculture ponds, primarily for shrimp farming, is the *single largest cause* of mangrove loss in Southeast Asia. This has devastating impacts on biodiversity, coastal protection, and water quality.']
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Logic Description"] = '---'
aquatic_mangrove_southeast_asian_stressors["Aquaculture Expansion"]["Impact Function"] = "impact_aquaculture_expansion_aquatic_mangrove_southeast_asian"

# --- Deforestation ---
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Metric"] = 'Area of mangroves cleared per year (ha/year) (for timber, charcoal, etc.).'
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Data Sources"] = ['Remote sensing data.', 'Government statistics.', 'Research publications.', '**Impact on Area:** Loss of mangrove habitat.', '**Impact on Biodiversity:**', 'Habitat loss.', 'Reduced carbon sequestration.', '**Influenced By (Stressors):**', 'Demand for Timber and Fuelwood: Local use and export.', 'Poverty and Lack of Alternative Livelihoods.', 'Coastal Development', '**Influences (Stressors):**', '* Coastal erosion', '**Logic Description:** Deforestation for timber, fuelwood, and charcoal production also contributes to mangrove loss.']
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Impact on Area"] = 'Loss of mangrove habitat.'
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Impact on Biodiversity"] = 'Habitat loss.\nReduced carbon sequestration.\n**Influenced By (Stressors):**\nDemand for Timber and Fuelwood: Local use and export.\nPoverty and Lack of Alternative Livelihoods.\nCoastal Development\n**Influences (Stressors):**\n* Coastal erosion\n**Logic Description:** Deforestation for timber, fuelwood, and charcoal production also contributes to mangrove loss.'
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Influenced By"] = ['Demand for Timber and Fuelwood: Local use and export.', 'Poverty and Lack of Alternative Livelihoods.', 'Coastal Development', '**Influences (Stressors):**', '* Coastal erosion', '**Logic Description:** Deforestation for timber, fuelwood, and charcoal production also contributes to mangrove loss.']
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Influences"] = ['* Coastal erosion', '**Logic Description:** Deforestation for timber, fuelwood, and charcoal production also contributes to mangrove loss.']
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Logic Description"] = '---'
aquatic_mangrove_southeast_asian_stressors["Deforestation"]["Impact Function"] = "impact_deforestation_aquatic_mangrove_southeast_asian"

# --- Pollution ---
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (nutrients, heavy metals, plastics) in water and sediment.'
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Data Sources"] = ['Water quality monitoring data (often limited).', 'Research studies.', '**Impact on Area:** Water quality degradation.', '**Impact on Biodiversity:**', 'Toxic effects on mangroves and associated fauna.', 'Eutrophication.', '**Influenced By (Stressors):**', 'Industrial Discharge.', 'Urban Runoff.', 'Agricultural Runoff.', 'Aquaculture Effluent.', '**Influences (Stressors):**', 'Mangrove Health.', 'Water Quality.', '**Logic Description:** Pollution from various sources degrades water quality and impacts mangrove ecosystems.']
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Impact on Area"] = 'Water quality degradation.'
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Impact on Biodiversity"] = 'Toxic effects on mangroves and associated fauna.\nEutrophication.\n**Influenced By (Stressors):**\nIndustrial Discharge.\nUrban Runoff.\nAgricultural Runoff.\nAquaculture Effluent.\n**Influences (Stressors):**\nMangrove Health.\nWater Quality.\n**Logic Description:** Pollution from various sources degrades water quality and impacts mangrove ecosystems.'
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Influenced By"] = ['Industrial Discharge.', 'Urban Runoff.', 'Agricultural Runoff.', 'Aquaculture Effluent.', '**Influences (Stressors):**', 'Mangrove Health.', 'Water Quality.', '**Logic Description:** Pollution from various sources degrades water quality and impacts mangrove ecosystems.']
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Influences"] = ['Mangrove Health.', 'Water Quality.', '**Logic Description:** Pollution from various sources degrades water quality and impacts mangrove ecosystems.']
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Logic Description"] = '---'
aquatic_mangrove_southeast_asian_stressors["Pollution"]["Impact Function"] = "impact_pollution_aquatic_mangrove_southeast_asian"

# --- Climate Change ---
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Metric"] = 'Sea Level Rise, Temperature, Storms'
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Data Sources"] = ['* Climate Models', '* Tide Gauges', '* Weather records', '**Impact on Area:** Innundation, Erosion, Storm Damage.', '**Impact on Biodiversity:**', '* Species Shifts', '* Increased Stress', '**Influenced By (Stressors):**', '* Global GHG', '**Influences (Stressors):**', '* Sea level', '* Storm surge', '**Logic Description:**  Climate change impacts.']
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Impact on Area"] = 'Innundation, Erosion, Storm Damage.'
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Impact on Biodiversity"] = '* Species Shifts\n* Increased Stress\n**Influenced By (Stressors):**\n* Global GHG\n**Influences (Stressors):**\n* Sea level\n* Storm surge\n**Logic Description:**  Climate change impacts.'
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Influenced By"] = ['* Global GHG', '**Influences (Stressors):**', '* Sea level', '* Storm surge', '**Logic Description:**  Climate change impacts.']
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Influences"] = ['* Sea level', '* Storm surge', '**Logic Description:**  Climate change impacts.']
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Logic Description"] = '---'
aquatic_mangrove_southeast_asian_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_aquatic_mangrove_southeast_asian"

