from stressor_templates import *
import copy

aquatic_seagrass_mediterranean_stressors = {
    "Physical Damage": {},
    "Water Quality Degradation": {},
    "Climate Change": copy.deepcopy(climate_change_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
}

# --- Physical Damage ---
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Metric"] = 'Area of *Posidonia oceanica* meadows damaged by anchoring and trawling (ha/year); density of boat anchors in seagrass areas.'
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Data Sources"] = ['Underwater surveys (using divers, ROVs, and sonar).', 'Mapping of seagrass meadows.', 'Boating activity data.', 'Research publications.', '**Impact on Area:** Direct destruction of *Posidonia oceanica* meadows; fragmentation. *Posidonia* is *extremely* slow-growing, so damage is long-lasting.', '**Impact on Biodiversity:**', 'Loss of habitat for a wide range of species.', 'Reduced nursery grounds for fish.', 'Increased coastal erosion (Posidonia meadows stabilize sediments).', '**Influenced By (Stressors):**', 'Boating Activity: Anchoring in seagrass meadows.', 'Illegal Trawling: Trawling is prohibited in many areas, but illegal trawling still occurs.', 'Coastal Development.', '**Influences (Stressors):**', 'Habitat Loss (the primary impact).', 'Coastal Erosion.', '**Logic Description:** Physical damage from anchoring and (illegal) trawling is a *major* threat to *Posidonia oceanica* meadows.  These meadows are extremely slow-growing and recover very slowly from damage, so the impacts can last for decades or centuries.']
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Impact on Area"] = 'Direct destruction of *Posidonia oceanica* meadows; fragmentation. *Posidonia* is *extremely* slow-growing, so damage is long-lasting.'
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Impact on Biodiversity"] = 'Loss of habitat for a wide range of species.\nReduced nursery grounds for fish.\nIncreased coastal erosion (Posidonia meadows stabilize sediments).\n**Influenced By (Stressors):**\nBoating Activity: Anchoring in seagrass meadows.\nIllegal Trawling: Trawling is prohibited in many areas, but illegal trawling still occurs.\nCoastal Development.\n**Influences (Stressors):**\nHabitat Loss (the primary impact).\nCoastal Erosion.\n**Logic Description:** Physical damage from anchoring and (illegal) trawling is a *major* threat to *Posidonia oceanica* meadows.  These meadows are extremely slow-growing and recover very slowly from damage, so the impacts can last for decades or centuries.'
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Influenced By"] = ['Boating Activity: Anchoring in seagrass meadows.', 'Illegal Trawling: Trawling is prohibited in many areas, but illegal trawling still occurs.', 'Coastal Development.', '**Influences (Stressors):**', 'Habitat Loss (the primary impact).', 'Coastal Erosion.', '**Logic Description:** Physical damage from anchoring and (illegal) trawling is a *major* threat to *Posidonia oceanica* meadows.  These meadows are extremely slow-growing and recover very slowly from damage, so the impacts can last for decades or centuries.']
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Influences"] = ['Habitat Loss (the primary impact).', 'Coastal Erosion.', '**Logic Description:** Physical damage from anchoring and (illegal) trawling is a *major* threat to *Posidonia oceanica* meadows.  These meadows are extremely slow-growing and recover very slowly from damage, so the impacts can last for decades or centuries.']
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Logic Description"] = '---'
aquatic_seagrass_mediterranean_stressors["Physical Damage"]["Impact Function"] = "impact_physical_damage_aquatic_seagrass_mediterranean"

# --- Water Quality Degradation ---
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Metric"] = 'Water clarity (turbidity); nutrient concentrations; concentrations of pollutants.'
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Data Sources"] = ['Water quality monitoring programs.', 'Research studies.', '**Impact on Area:** Reduced light penetration; stress on *Posidonia*.', '**Impact on Biodiversity:**', 'Reduced seagrass growth and survival.', 'Algal blooms.', '**Influenced By (Stressors):**', 'Urban Runoff: Sewage, stormwater.', 'Agricultural Runoff.', 'Industrial Discharge.', 'Coastal Development.', '**Influences (Stressors):**', 'Light Availability.', 'Seagrass Health.', '**Logic Description:** Reduced water quality due to pollution and increased turbidity is a significant threat.']
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Impact on Area"] = 'Reduced light penetration; stress on *Posidonia*.'
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Impact on Biodiversity"] = 'Reduced seagrass growth and survival.\nAlgal blooms.\n**Influenced By (Stressors):**\nUrban Runoff: Sewage, stormwater.\nAgricultural Runoff.\nIndustrial Discharge.\nCoastal Development.\n**Influences (Stressors):**\nLight Availability.\nSeagrass Health.\n**Logic Description:** Reduced water quality due to pollution and increased turbidity is a significant threat.'
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Influenced By"] = ['Urban Runoff: Sewage, stormwater.', 'Agricultural Runoff.', 'Industrial Discharge.', 'Coastal Development.', '**Influences (Stressors):**', 'Light Availability.', 'Seagrass Health.', '**Logic Description:** Reduced water quality due to pollution and increased turbidity is a significant threat.']
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Influences"] = ['Light Availability.', 'Seagrass Health.', '**Logic Description:** Reduced water quality due to pollution and increased turbidity is a significant threat.']
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Logic Description"] = '---'
aquatic_seagrass_mediterranean_stressors["Water Quality Degradation"]["Impact Function"] = "impact_water_quality_degradation_aquatic_seagrass_mediterranean"

# --- Climate Change ---
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Metric"] = 'Sea surface temperature; frequency/intensity of heatwaves; ocean acidification.'
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Data Sources"] = ['Climate models.', '* Oceanographic data.', '**Impact on Area:**', 'Increased *Posidonia* mortality (especially during heatwaves).', '**Impact on Biodiversity:**', '* Shifts in species distributions.', 'Increased stress on *Posidonia* and associated species.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Heat Stress.', '* Ocean Acidification', '**Logic Description:** The Mediterranean Sea is warming rapidly, and marine heatwaves are becoming more frequent and intense, posing a significant threat to *Posidonia oceanica*.']
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Impact on Area"] = ''
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Impact on Biodiversity"] = '* Shifts in species distributions.\nIncreased stress on *Posidonia* and associated species.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nHeat Stress.\n* Ocean Acidification\n**Logic Description:** The Mediterranean Sea is warming rapidly, and marine heatwaves are becoming more frequent and intense, posing a significant threat to *Posidonia oceanica*.'
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Heat Stress.', '* Ocean Acidification', '**Logic Description:** The Mediterranean Sea is warming rapidly, and marine heatwaves are becoming more frequent and intense, posing a significant threat to *Posidonia oceanica*.']
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Influences"] = ['Heat Stress.', '* Ocean Acidification', '**Logic Description:** The Mediterranean Sea is warming rapidly, and marine heatwaves are becoming more frequent and intense, posing a significant threat to *Posidonia oceanica*.']
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Logic Description"] = '---'
aquatic_seagrass_mediterranean_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_aquatic_seagrass_mediterranean"

# --- Invasive Species ---
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Metric"] = 'Distribution and abundance of invasive *Caulerpa* species.'
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Data Sources"] = ['* Underwater surveys.', '* Research publications.', '**Impact on Area:** Competition with *Posidonia*.', '**Impact on Biodiversity:**', '* Can outcompete *Posidonia* and alter habitat structure.', '**Influenced By (Stressors):**', 'Shipping (ballast water, hull fouling).', 'Aquarium releases.', '* Climate Change', '**Influences (Stressors):**', '*  Native Seagrass', '**Logic Description:** Invasive algae, particularly *Caulerpa* species, can outcompete *Posidonia oceanica*.']
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Impact on Area"] = 'Competition with *Posidonia*.'
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Impact on Biodiversity"] = '* Can outcompete *Posidonia* and alter habitat structure.\n**Influenced By (Stressors):**\nShipping (ballast water, hull fouling).\nAquarium releases.\n* Climate Change\n**Influences (Stressors):**\n*  Native Seagrass\n**Logic Description:** Invasive algae, particularly *Caulerpa* species, can outcompete *Posidonia oceanica*.'
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Influenced By"] = ['Shipping (ballast water, hull fouling).', 'Aquarium releases.', '* Climate Change', '**Influences (Stressors):**', '*  Native Seagrass', '**Logic Description:** Invasive algae, particularly *Caulerpa* species, can outcompete *Posidonia oceanica*.']
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Influences"] = ['*  Native Seagrass', '**Logic Description:** Invasive algae, particularly *Caulerpa* species, can outcompete *Posidonia oceanica*.']
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Logic Description"] = '---'
aquatic_seagrass_mediterranean_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_aquatic_seagrass_mediterranean"

