from stressor_templates import *
import copy

aquatic_rivers_amazon_stressors = {
    "Deforestation": copy.deepcopy(deforestation_template),
    "Hydropower Dams": {},
    "Climate Change": copy.deepcopy(climate_change_template),
    "Pollution": copy.deepcopy(pollution_template),
}

# --- Deforestation ---
aquatic_rivers_amazon_stressors["Deforestation"]["Metric"] = 'Rate of deforestation (km²/year); area of forest converted to agriculture and pasture; forest fragmentation.'
aquatic_rivers_amazon_stressors["Deforestation"]["Data Sources"] = ['Brazilian National Institute for Space Research (INPE) - PRODES, DETER.', 'Global Forest Watch.', 'Remote sensing data (Landsat, Sentinel).', 'Research publications.', '**Impact on Area:** Increased sediment load in the Amazon River and its tributaries; altered hydrological cycle.', '**Impact on Biodiversity:**', 'Loss of habitat for aquatic and riparian species.', 'Increased water temperatures in streams due to loss of shade.', 'Changes in fish communities.', 'Impacts on migratory fish species.', '**Influenced By (Stressors):**', 'Agricultural Expansion: (cattle ranching, soybean farming).', 'Illegal Logging.', 'Road Construction.', 'Mining.', 'Weak Environmental Governance.', '**Influences (Stressors):**', 'Sedimentation (major impact).', 'Hydrology.', 'Water Quality.', '**Logic Description:** Deforestation in the Amazon basin is the *primary* driver of environmental change in the Amazon River system. It leads to increased soil erosion, resulting in higher sediment loads in rivers, altered flow patterns, and impacts on aquatic life.']
aquatic_rivers_amazon_stressors["Deforestation"]["Impact on Area"] = 'Increased sediment load in the Amazon River and its tributaries; altered hydrological cycle.'
aquatic_rivers_amazon_stressors["Deforestation"]["Impact on Biodiversity"] = 'Loss of habitat for aquatic and riparian species.\nIncreased water temperatures in streams due to loss of shade.\nChanges in fish communities.\nImpacts on migratory fish species.\n**Influenced By (Stressors):**\nAgricultural Expansion: (cattle ranching, soybean farming).\nIllegal Logging.\nRoad Construction.\nMining.\nWeak Environmental Governance.\n**Influences (Stressors):**\nSedimentation (major impact).\nHydrology.\nWater Quality.\n**Logic Description:** Deforestation in the Amazon basin is the *primary* driver of environmental change in the Amazon River system. It leads to increased soil erosion, resulting in higher sediment loads in rivers, altered flow patterns, and impacts on aquatic life.'
aquatic_rivers_amazon_stressors["Deforestation"]["Influenced By"] = ['Agricultural Expansion: (cattle ranching, soybean farming).', 'Illegal Logging.', 'Road Construction.', 'Mining.', 'Weak Environmental Governance.', '**Influences (Stressors):**', 'Sedimentation (major impact).', 'Hydrology.', 'Water Quality.', '**Logic Description:** Deforestation in the Amazon basin is the *primary* driver of environmental change in the Amazon River system. It leads to increased soil erosion, resulting in higher sediment loads in rivers, altered flow patterns, and impacts on aquatic life.']
aquatic_rivers_amazon_stressors["Deforestation"]["Influences"] = ['Sedimentation (major impact).', 'Hydrology.', 'Water Quality.', '**Logic Description:** Deforestation in the Amazon basin is the *primary* driver of environmental change in the Amazon River system. It leads to increased soil erosion, resulting in higher sediment loads in rivers, altered flow patterns, and impacts on aquatic life.']
aquatic_rivers_amazon_stressors["Deforestation"]["Logic Description"] = '---'

# --- Hydropower Dams ---
aquatic_rivers_amazon_stressors["Hydropower Dams"]["Metric"] = 'Number of dams constructed and planned; changes in river flow; area of land flooded by reservoirs.'
aquatic_rivers_amazon_stressors["Hydropower Dams"]["Data Sources"] = ['Brazilian National Electric Energy Agency (ANEEL).', 'Environmental Impact Assessments (EIAs) for dam projects.', 'Research publications.', '**Impact on Area:** Altered flow regimes; fragmentation of river habitats; blockage of fish migration routes; changes in sediment transport; greenhouse gas emissions from reservoirs (methane).', '**Impact on Biodiversity:**', 'Impacts on fish populations (particularly migratory species).', 'Loss of riverine and floodplain habitats.', 'Changes in aquatic food webs.', 'Impacts on indigenous communities.', '**Influenced By (Stressors):**', 'Demand for Electricity: In Brazil and neighboring countries.', 'Government Energy Policies.', '**Influences (Stressors):**', 'Fish Migration.', 'Sediment Transport.', 'Habitat Connectivity.', 'Greenhouse Gas Emissions.', '**Logic Description:**  Hydropower dam construction is a rapidly growing threat to the Amazon River system, altering flow patterns, blocking fish migration, fragmenting habitats, and releasing greenhouse gases.']
aquatic_rivers_amazon_stressors["Hydropower Dams"]["Impact on Area"] = 'Altered flow regimes; fragmentation of river habitats; blockage of fish migration routes; changes in sediment transport; greenhouse gas emissions from reservoirs (methane).'
aquatic_rivers_amazon_stressors["Hydropower Dams"]["Impact on Biodiversity"] = 'Impacts on fish populations (particularly migratory species).\nLoss of riverine and floodplain habitats.\nChanges in aquatic food webs.\nImpacts on indigenous communities.\n**Influenced By (Stressors):**\nDemand for Electricity: In Brazil and neighboring countries.\nGovernment Energy Policies.\n**Influences (Stressors):**\nFish Migration.\nSediment Transport.\nHabitat Connectivity.\nGreenhouse Gas Emissions.\n**Logic Description:**  Hydropower dam construction is a rapidly growing threat to the Amazon River system, altering flow patterns, blocking fish migration, fragmenting habitats, and releasing greenhouse gases.'
aquatic_rivers_amazon_stressors["Hydropower Dams"]["Influenced By"] = ['Demand for Electricity: In Brazil and neighboring countries.', 'Government Energy Policies.', '**Influences (Stressors):**', 'Fish Migration.', 'Sediment Transport.', 'Habitat Connectivity.', 'Greenhouse Gas Emissions.', '**Logic Description:**  Hydropower dam construction is a rapidly growing threat to the Amazon River system, altering flow patterns, blocking fish migration, fragmenting habitats, and releasing greenhouse gases.']
aquatic_rivers_amazon_stressors["Hydropower Dams"]["Influences"] = ['Fish Migration.', 'Sediment Transport.', 'Habitat Connectivity.', 'Greenhouse Gas Emissions.', '**Logic Description:**  Hydropower dam construction is a rapidly growing threat to the Amazon River system, altering flow patterns, blocking fish migration, fragmenting habitats, and releasing greenhouse gases.']
aquatic_rivers_amazon_stressors["Hydropower Dams"]["Logic Description"] = '---'

# --- Climate Change ---
aquatic_rivers_amazon_stressors["Climate Change"]["Metric"] = 'Changes in precipitation patterns; changes in river discharge; increased frequency and severity of droughts and floods; water temperature.'
aquatic_rivers_amazon_stressors["Climate Change"]["Data Sources"] = ['Climate models.', 'Hydrological data (river gauge measurements).', 'Research publications.', '**Impact on Area:** Altered hydrological cycle; increased risk of extreme events.', '**Impact on Biodiversity:**', 'Impacts on fish and other aquatic organisms.', 'Changes in floodplain inundation patterns, affecting plant and animal communities.', 'Increased stress on ecosystems already impacted by deforestation and dams.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', 'Deforestation (can exacerbate local climate change impacts).', '**Influences (Stressors):**', 'Hydrology.', 'Extreme Events (Floods and Droughts).', 'Water Temperature.', '**Logic Description:** Climate change is impacting the Amazon River through changes in precipitation, increased frequency of extreme events, and interactions with other stressors like deforestation.']
aquatic_rivers_amazon_stressors["Climate Change"]["Impact on Area"] = 'Altered hydrological cycle; increased risk of extreme events.'
aquatic_rivers_amazon_stressors["Climate Change"]["Impact on Biodiversity"] = 'Impacts on fish and other aquatic organisms.\nChanges in floodplain inundation patterns, affecting plant and animal communities.\nIncreased stress on ecosystems already impacted by deforestation and dams.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\nDeforestation (can exacerbate local climate change impacts).\n**Influences (Stressors):**\nHydrology.\nExtreme Events (Floods and Droughts).\nWater Temperature.\n**Logic Description:** Climate change is impacting the Amazon River through changes in precipitation, increased frequency of extreme events, and interactions with other stressors like deforestation.'
aquatic_rivers_amazon_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', 'Deforestation (can exacerbate local climate change impacts).', '**Influences (Stressors):**', 'Hydrology.', 'Extreme Events (Floods and Droughts).', 'Water Temperature.', '**Logic Description:** Climate change is impacting the Amazon River through changes in precipitation, increased frequency of extreme events, and interactions with other stressors like deforestation.']
aquatic_rivers_amazon_stressors["Climate Change"]["Influences"] = ['Hydrology.', 'Extreme Events (Floods and Droughts).', 'Water Temperature.', '**Logic Description:** Climate change is impacting the Amazon River through changes in precipitation, increased frequency of extreme events, and interactions with other stressors like deforestation.']
aquatic_rivers_amazon_stressors["Climate Change"]["Logic Description"] = '---'

# --- Pollution ---
aquatic_rivers_amazon_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (mercury from gold mining, pesticides, sewage).'
aquatic_rivers_amazon_stressors["Pollution"]["Data Sources"] = ['* Research studies', '* Government monitoring', '**Impact on Area:** Localized and regional water quality issues.', '**Impact on Biodiversity:**', '* Toxic effects on fish and other organisms.', '* Bioaccumulation of mercury in the food chain.', '**Influenced By (Stressors):**', '* Gold mining (mercury).', '* Agriculture (pesticides).', '* Urban areas (sewage).', '**Influences (Stressors):**', 'Water Quality.', '* Wildlife and human health.', '**Logic Description:**  Mining, agriculture, and urban areas contribute to pollution.']
aquatic_rivers_amazon_stressors["Pollution"]["Impact on Area"] = 'Localized and regional water quality issues.'
aquatic_rivers_amazon_stressors["Pollution"]["Impact on Biodiversity"] = '* Toxic effects on fish and other organisms.\n* Bioaccumulation of mercury in the food chain.\n**Influenced By (Stressors):**\n* Gold mining (mercury).\n* Agriculture (pesticides).\n* Urban areas (sewage).\n**Influences (Stressors):**\nWater Quality.\n* Wildlife and human health.\n**Logic Description:**  Mining, agriculture, and urban areas contribute to pollution.'
aquatic_rivers_amazon_stressors["Pollution"]["Influenced By"] = ['* Gold mining (mercury).', '* Agriculture (pesticides).', '* Urban areas (sewage).', '**Influences (Stressors):**', 'Water Quality.', '* Wildlife and human health.', '**Logic Description:**  Mining, agriculture, and urban areas contribute to pollution.']
aquatic_rivers_amazon_stressors["Pollution"]["Influences"] = ['Water Quality.', '* Wildlife and human health.', '**Logic Description:**  Mining, agriculture, and urban areas contribute to pollution.']
aquatic_rivers_amazon_stressors["Pollution"]["Logic Description"] = '---'

