from stressor_templates import *
import copy

aquatic_rivers_danube_stressors = {
    "Pollution": copy.deepcopy(pollution_template),
    "Hydromorphological Alterations": {},
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Pollution ---
aquatic_rivers_danube_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (nutrients, heavy metals, organic pollutants, pharmaceuticals) in water, sediment, and biota.'
aquatic_rivers_danube_stressors["Pollution"]["Data Sources"] = ['International Commission for the Protection of the Danube River (ICPDR).', 'National monitoring programs (of countries along the Danube).', 'Research publications.', '**Impact on Area:** Widespread water quality degradation.', '**Impact on Biodiversity:**', 'Eutrophication (nutrient enrichment).', 'Toxic effects on aquatic organisms.', 'Impacts on human health (through drinking water and fish consumption).', 'Bioaccumulation of pollutants.', '**Influenced By (Stressors):**', 'Agricultural Runoff: Fertilizers and animal waste.', 'Industrial Discharge: Untreated or poorly treated industrial wastewater.', 'Municipal Wastewater: Sewage from cities and towns.', 'Mining Activities: Release of heavy metals.', '**Influences (Stressors):**', 'Water Quality.', 'Aquatic Life Health.', 'Human Health.', '**Logic Description:** The Danube River is a transboundary river flowing through many countries, and it receives pollution from a wide range of sources, including agriculture, industry, and urban areas. This pollution degrades water quality and impacts both aquatic life and human health.']
aquatic_rivers_danube_stressors["Pollution"]["Impact on Area"] = 'Widespread water quality degradation.'
aquatic_rivers_danube_stressors["Pollution"]["Impact on Biodiversity"] = 'Eutrophication (nutrient enrichment).\nToxic effects on aquatic organisms.\nImpacts on human health (through drinking water and fish consumption).\nBioaccumulation of pollutants.\n**Influenced By (Stressors):**\nAgricultural Runoff: Fertilizers and animal waste.\nIndustrial Discharge: Untreated or poorly treated industrial wastewater.\nMunicipal Wastewater: Sewage from cities and towns.\nMining Activities: Release of heavy metals.\n**Influences (Stressors):**\nWater Quality.\nAquatic Life Health.\nHuman Health.\n**Logic Description:** The Danube River is a transboundary river flowing through many countries, and it receives pollution from a wide range of sources, including agriculture, industry, and urban areas. This pollution degrades water quality and impacts both aquatic life and human health.'
aquatic_rivers_danube_stressors["Pollution"]["Influenced By"] = ['Agricultural Runoff: Fertilizers and animal waste.', 'Industrial Discharge: Untreated or poorly treated industrial wastewater.', 'Municipal Wastewater: Sewage from cities and towns.', 'Mining Activities: Release of heavy metals.', '**Influences (Stressors):**', 'Water Quality.', 'Aquatic Life Health.', 'Human Health.', '**Logic Description:** The Danube River is a transboundary river flowing through many countries, and it receives pollution from a wide range of sources, including agriculture, industry, and urban areas. This pollution degrades water quality and impacts both aquatic life and human health.']
aquatic_rivers_danube_stressors["Pollution"]["Influences"] = ['Water Quality.', 'Aquatic Life Health.', 'Human Health.', '**Logic Description:** The Danube River is a transboundary river flowing through many countries, and it receives pollution from a wide range of sources, including agriculture, industry, and urban areas. This pollution degrades water quality and impacts both aquatic life and human health.']
aquatic_rivers_danube_stressors["Pollution"]["Logic Description"] = '---'
aquatic_rivers_danube_stressors["Pollution"]["Impact Function"] = "impact_pollution_aquatic_rivers_danube"

# --- Hydromorphological Alterations ---
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Metric"] = 'Number of dams, weirs, and other structures; extent of channelization; loss of floodplain habitats; changes in flow regime.'
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Data Sources"] = ['ICPDR.', 'National water management agencies.', 'Research publications.', '**Impact on Area:** Altered river morphology and hydrology; loss of natural habitats.', '**Impact on Biodiversity:**', 'Impacts on fish migration (dams block passage).', 'Loss of spawning grounds.', 'Changes in invertebrate communities.', 'Loss of floodplain wetlands and riparian habitats.', '**Influenced By (Stressors):**', 'Hydropower Generation: Dams.', 'Navigation: Channelization and locks.', 'Flood Control: Levees and embankments.', 'Water Abstraction: For irrigation and other uses.', '**Influences (Stressors):**', 'Habitat Connectivity.', 'Sediment Transport.', 'Floodplain Ecosystems.', 'Fish Migration', "**Logic Description:** Dams, weirs, channelization, and other hydromorphological alterations have significantly changed the Danube River's natural flow regime, fragmenting habitats, blocking fish migration, and reducing the extent of floodplains."]
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Impact on Area"] = 'Altered river morphology and hydrology; loss of natural habitats.'
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Impact on Biodiversity"] = "Impacts on fish migration (dams block passage).\nLoss of spawning grounds.\nChanges in invertebrate communities.\nLoss of floodplain wetlands and riparian habitats.\n**Influenced By (Stressors):**\nHydropower Generation: Dams.\nNavigation: Channelization and locks.\nFlood Control: Levees and embankments.\nWater Abstraction: For irrigation and other uses.\n**Influences (Stressors):**\nHabitat Connectivity.\nSediment Transport.\nFloodplain Ecosystems.\nFish Migration\n**Logic Description:** Dams, weirs, channelization, and other hydromorphological alterations have significantly changed the Danube River's natural flow regime, fragmenting habitats, blocking fish migration, and reducing the extent of floodplains."
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Influenced By"] = ['Hydropower Generation: Dams.', 'Navigation: Channelization and locks.', 'Flood Control: Levees and embankments.', 'Water Abstraction: For irrigation and other uses.', '**Influences (Stressors):**', 'Habitat Connectivity.', 'Sediment Transport.', 'Floodplain Ecosystems.', 'Fish Migration', "**Logic Description:** Dams, weirs, channelization, and other hydromorphological alterations have significantly changed the Danube River's natural flow regime, fragmenting habitats, blocking fish migration, and reducing the extent of floodplains."]
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Influences"] = ['Habitat Connectivity.', 'Sediment Transport.', 'Floodplain Ecosystems.', 'Fish Migration', "**Logic Description:** Dams, weirs, channelization, and other hydromorphological alterations have significantly changed the Danube River's natural flow regime, fragmenting habitats, blocking fish migration, and reducing the extent of floodplains."]
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Logic Description"] = '---'
aquatic_rivers_danube_stressors["Hydromorphological Alterations"]["Impact Function"] = "impact_hydromorphological_alterations_aquatic_rivers_danube"

# --- Invasive Species ---
aquatic_rivers_danube_stressors["Invasive Species"]["Data Sources"] = ['* Research', '* Monitoring programs.', '**Impact on Area**: Changes to habitats.', '**Impact on Biodiversity:**', 'Competition with native species.', 'Alteration of food webs.', '**Influenced By (Stressors):**', '* Ballast water.', '* Canals', '* Climate Change', '**Influences (Stressors):**', '* Native Species', '**Logic Description:** Invasive species impact.']
aquatic_rivers_danube_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Competition with native species.\nAlteration of food webs.\n**Influenced By (Stressors):**\n* Ballast water.\n* Canals\n* Climate Change\n**Influences (Stressors):**\n* Native Species\n**Logic Description:** Invasive species impact.'
aquatic_rivers_danube_stressors["Invasive Species"]["Influenced By"] = ['* Ballast water.', '* Canals', '* Climate Change', '**Influences (Stressors):**', '* Native Species', '**Logic Description:** Invasive species impact.']
aquatic_rivers_danube_stressors["Invasive Species"]["Influences"] = ['* Native Species', '**Logic Description:** Invasive species impact.']
aquatic_rivers_danube_stressors["Invasive Species"]["Logic Description"] = '---'
aquatic_rivers_danube_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_aquatic_rivers_danube"

# --- Climate Change ---
aquatic_rivers_danube_stressors["Climate Change"]["Metric"] = 'Temperature and precipitation changes'
aquatic_rivers_danube_stressors["Climate Change"]["Data Sources"] = ['* Climate Models', '* Historical Data', '**Impact on Area:** Altered flow and temperature', '**Impact on Biodiversity:**', '* Species shifts', '* Increased Stress', '**Influenced By (Stressors):**', '* Global GHG Emissions', '**Influences (Stressors):**', '*  Hydrology', '**Logic Description:** Climate change impacts.']
aquatic_rivers_danube_stressors["Climate Change"]["Impact on Area"] = 'Altered flow and temperature'
aquatic_rivers_danube_stressors["Climate Change"]["Impact on Biodiversity"] = '* Species shifts\n* Increased Stress\n**Influenced By (Stressors):**\n* Global GHG Emissions\n**Influences (Stressors):**\n*  Hydrology\n**Logic Description:** Climate change impacts.'
aquatic_rivers_danube_stressors["Climate Change"]["Influenced By"] = ['* Global GHG Emissions', '**Influences (Stressors):**', '*  Hydrology', '**Logic Description:** Climate change impacts.']
aquatic_rivers_danube_stressors["Climate Change"]["Influences"] = ['*  Hydrology', '**Logic Description:** Climate change impacts.']
aquatic_rivers_danube_stressors["Climate Change"]["Logic Description"] = '---'
aquatic_rivers_danube_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_aquatic_rivers_danube"

