from stressor_templates import *
import copy

aquatic_rivers_mississippi_stressors = {
    "Agricultural Runoff": {},
    "Dams and Levees": {},
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Agricultural Runoff ---
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Metric"] = 'Concentrations of nitrogen and phosphorus in the Mississippi River and its tributaries; size and severity of the hypoxic zone (dead zone) in the Gulf of Mexico.'
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Data Sources"] = ['US Geological Survey (USGS) National Water-Quality Assessment (NAWQA) program.', 'NOAA National Centers for Coastal Ocean Science (NCCOS).', 'State environmental agencies.', 'Research publications.', '**Impact on Area:** *Major* impact on water quality in the Mississippi River and the Gulf of Mexico.', '**Impact on Biodiversity:**', 'Hypoxia (oxygen depletion) in the Gulf of Mexico, creating a "dead zone" where marine life cannot survive.', 'Impacts on fisheries in the Gulf.', 'Altered food webs.', '**Influenced By (Stressors):**', 'Agricultural Practices: Use of fertilizers in the vast Mississippi River basin.', 'Animal Agriculture: Waste from livestock operations.', 'Lack of Effective Nutrient Management Practices.', '**Influences (Stressors):**', 'Gulf of Mexico Hypoxia (the dominant impact).', 'Water Quality.', '**Logic Description:** Agricultural runoff, carrying excess nutrients (nitrogen and phosphorus) from fertilizers and animal waste, is the *primary* driver of the large hypoxic zone (dead zone) in the Gulf of Mexico, with significant impacts on marine ecosystems and fisheries. This is one of the most well-known and well-studied environmental problems in the United States.']
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Impact on Area"] = '*Major* impact on water quality in the Mississippi River and the Gulf of Mexico.'
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Impact on Biodiversity"] = 'Hypoxia (oxygen depletion) in the Gulf of Mexico, creating a "dead zone" where marine life cannot survive.\nImpacts on fisheries in the Gulf.\nAltered food webs.\n**Influenced By (Stressors):**\nAgricultural Practices: Use of fertilizers in the vast Mississippi River basin.\nAnimal Agriculture: Waste from livestock operations.\nLack of Effective Nutrient Management Practices.\n**Influences (Stressors):**\nGulf of Mexico Hypoxia (the dominant impact).\nWater Quality.\n**Logic Description:** Agricultural runoff, carrying excess nutrients (nitrogen and phosphorus) from fertilizers and animal waste, is the *primary* driver of the large hypoxic zone (dead zone) in the Gulf of Mexico, with significant impacts on marine ecosystems and fisheries. This is one of the most well-known and well-studied environmental problems in the United States.'
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Influenced By"] = ['Agricultural Practices: Use of fertilizers in the vast Mississippi River basin.', 'Animal Agriculture: Waste from livestock operations.', 'Lack of Effective Nutrient Management Practices.', '**Influences (Stressors):**', 'Gulf of Mexico Hypoxia (the dominant impact).', 'Water Quality.', '**Logic Description:** Agricultural runoff, carrying excess nutrients (nitrogen and phosphorus) from fertilizers and animal waste, is the *primary* driver of the large hypoxic zone (dead zone) in the Gulf of Mexico, with significant impacts on marine ecosystems and fisheries. This is one of the most well-known and well-studied environmental problems in the United States.']
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Influences"] = ['Gulf of Mexico Hypoxia (the dominant impact).', 'Water Quality.', '**Logic Description:** Agricultural runoff, carrying excess nutrients (nitrogen and phosphorus) from fertilizers and animal waste, is the *primary* driver of the large hypoxic zone (dead zone) in the Gulf of Mexico, with significant impacts on marine ecosystems and fisheries. This is one of the most well-known and well-studied environmental problems in the United States.']
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Logic Description"] = '---'
aquatic_rivers_mississippi_stressors["Agricultural Runoff"]["Impact Function"] = "impact_agricultural_runoff_aquatic_rivers_mississippi"

# --- Dams and Levees ---
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Metric"] = 'Number of dams and levees; changes in river flow and sediment transport; loss of floodplain connectivity.'
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Data Sources"] = ['US Army Corps of Engineers (USACE).', 'USGS.', 'Research publications.', '**Impact on Area:** Altered hydrology; reduced sediment delivery to coastal wetlands; loss of floodplain habitats.', '**Impact on Biodiversity:**', 'Impacts on fish migration.', 'Loss of wetlands and floodplain habitats.', 'Changes in riverine ecosystems.', '**Influenced By (Stressors):**', 'Flood Control: Levees were built to protect communities and agriculture from flooding.', 'Navigation: Dams and locks were built to facilitate barge traffic.', '**Influences (Stressors):**', 'Sediment Transport.', 'Habitat Connectivity.', 'Coastal Wetland Loss (in Louisiana).', "**Logic Description:**  Dams and levees along the Mississippi River, constructed for flood control and navigation, have significantly altered the river's hydrology, reduced sediment delivery to coastal wetlands, and fragmented habitats."]
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Impact on Area"] = 'Altered hydrology; reduced sediment delivery to coastal wetlands; loss of floodplain habitats.'
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Impact on Biodiversity"] = "Impacts on fish migration.\nLoss of wetlands and floodplain habitats.\nChanges in riverine ecosystems.\n**Influenced By (Stressors):**\nFlood Control: Levees were built to protect communities and agriculture from flooding.\nNavigation: Dams and locks were built to facilitate barge traffic.\n**Influences (Stressors):**\nSediment Transport.\nHabitat Connectivity.\nCoastal Wetland Loss (in Louisiana).\n**Logic Description:**  Dams and levees along the Mississippi River, constructed for flood control and navigation, have significantly altered the river's hydrology, reduced sediment delivery to coastal wetlands, and fragmented habitats."
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Influenced By"] = ['Flood Control: Levees were built to protect communities and agriculture from flooding.', 'Navigation: Dams and locks were built to facilitate barge traffic.', '**Influences (Stressors):**', 'Sediment Transport.', 'Habitat Connectivity.', 'Coastal Wetland Loss (in Louisiana).', "**Logic Description:**  Dams and levees along the Mississippi River, constructed for flood control and navigation, have significantly altered the river's hydrology, reduced sediment delivery to coastal wetlands, and fragmented habitats."]
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Influences"] = ['Sediment Transport.', 'Habitat Connectivity.', 'Coastal Wetland Loss (in Louisiana).', "**Logic Description:**  Dams and levees along the Mississippi River, constructed for flood control and navigation, have significantly altered the river's hydrology, reduced sediment delivery to coastal wetlands, and fragmented habitats."]
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Logic Description"] = '---'
aquatic_rivers_mississippi_stressors["Dams and Levees"]["Impact Function"] = "impact_dams_and_levees_aquatic_rivers_mississippi"

# --- Climate Change ---
aquatic_rivers_mississippi_stressors["Climate Change"]["Metric"] = 'Changes in precipitation; changes in flow; increased frequency of floods and droughts.'
aquatic_rivers_mississippi_stressors["Climate Change"]["Data Sources"] = ['* Climate Models', '* Hydrological Data', '**Impact on Area**: Altered flow regimes', '**Impact on Biodiversity:**', '* Impacts to fish and wildlife', '**Influenced By (Stressors):**', '* Global emissions', '**Influences (Stressors):**', '* Floods and droughts.', '* Water quality', '**Logic Description:** Climate change may alter precipitation.']
aquatic_rivers_mississippi_stressors["Climate Change"]["Impact on Biodiversity"] = '* Impacts to fish and wildlife\n**Influenced By (Stressors):**\n* Global emissions\n**Influences (Stressors):**\n* Floods and droughts.\n* Water quality\n**Logic Description:** Climate change may alter precipitation.'
aquatic_rivers_mississippi_stressors["Climate Change"]["Influenced By"] = ['* Global emissions', '**Influences (Stressors):**', '* Floods and droughts.', '* Water quality', '**Logic Description:** Climate change may alter precipitation.']
aquatic_rivers_mississippi_stressors["Climate Change"]["Influences"] = ['* Floods and droughts.', '* Water quality', '**Logic Description:** Climate change may alter precipitation.']
aquatic_rivers_mississippi_stressors["Climate Change"]["Logic Description"] = '---'
aquatic_rivers_mississippi_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_aquatic_rivers_mississippi"

