from stressor_templates import *
import copy

aquatic_mangrove_sundarbans_stressors = {
    "Coastal Development": {},
    "Deforestation": copy.deepcopy(deforestation_template),
    "Pollution": copy.deepcopy(pollution_template),
    "Climate Change": copy.deepcopy(climate_change_template),
    "Upstream Water Diversions": {},
}

# --- Coastal Development ---
aquatic_mangrove_sundarbans_stressors["Coastal Development"]["Metric"] = 'Area of mangroves converted to other land uses (ha/year); population density in coastal areas.'
aquatic_mangrove_sundarbans_stressors["Coastal Development"]["Data Sources"] = ['Remote sensing data.', 'Government statistics (India and Bangladesh).', 'Research publications.', '**Impact on Area:** Direct loss of mangrove habitat; fragmentation.', '**Impact on Biodiversity:**', 'Loss of habitat for a wide range of species, including the Bengal tiger.', 'Reduced nursery grounds for fish and shellfish.', 'Loss of coastal protection.', '**Influenced By (Stressors):**', 'Population Growth: High population density in the region.', 'Poverty and Lack of Alternative Livelihoods.', 'Shrimp Farming: Expansion of shrimp farms.', 'Infrastructure Development (ports, roads).', '**Influences (Stressors):**', 'Coastal Erosion.', 'Water Quality.', '**Logic Description:** Coastal development, driven by population growth, poverty, and economic activities like shrimp farming, is a significant threat to the Sundarbans, leading to habitat loss and fragmentation.']
aquatic_mangrove_sundarbans_stressors["Coastal Development"]["Impact on Area"] = 'Direct loss of mangrove habitat; fragmentation.'
aquatic_mangrove_sundarbans_stressors["Coastal Development"]["Impact on Biodiversity"] = 'Loss of habitat for a wide range of species, including the Bengal tiger.\nReduced nursery grounds for fish and shellfish.\nLoss of coastal protection.\n**Influenced By (Stressors):**\nPopulation Growth: High population density in the region.\nPoverty and Lack of Alternative Livelihoods.\nShrimp Farming: Expansion of shrimp farms.\nInfrastructure Development (ports, roads).\n**Influences (Stressors):**\nCoastal Erosion.\nWater Quality.\n**Logic Description:** Coastal development, driven by population growth, poverty, and economic activities like shrimp farming, is a significant threat to the Sundarbans, leading to habitat loss and fragmentation.'
aquatic_mangrove_sundarbans_stressors["Coastal Development"]["Influenced By"] = ['Population Growth: High population density in the region.', 'Poverty and Lack of Alternative Livelihoods.', 'Shrimp Farming: Expansion of shrimp farms.', 'Infrastructure Development (ports, roads).', '**Influences (Stressors):**', 'Coastal Erosion.', 'Water Quality.', '**Logic Description:** Coastal development, driven by population growth, poverty, and economic activities like shrimp farming, is a significant threat to the Sundarbans, leading to habitat loss and fragmentation.']
aquatic_mangrove_sundarbans_stressors["Coastal Development"]["Influences"] = ['Coastal Erosion.', 'Water Quality.', '**Logic Description:** Coastal development, driven by population growth, poverty, and economic activities like shrimp farming, is a significant threat to the Sundarbans, leading to habitat loss and fragmentation.']
aquatic_mangrove_sundarbans_stressors["Coastal Development"]["Logic Description"] = '---'

# --- Deforestation ---
aquatic_mangrove_sundarbans_stressors["Deforestation"]["Metric"] = 'Area of mangroves cleared per year (ha/year) (often illegal logging).'
aquatic_mangrove_sundarbans_stressors["Deforestation"]["Data Sources"] = ['Remote sensing data.', 'Forest department data (often incomplete).', 'Reports from environmental organizations.', '**Impact on Area:** Direct loss of mangrove habitat.', '**Impact on Biodiversity:**', 'Habitat loss.', 'Reduced carbon sequestration.', '**Influenced By (Stressors):**', 'Poverty and Lack of Alternative Livelihoods: Fuelwood collection, timber harvesting.', 'Weak Law Enforcement.', 'Corruption.', '**Influences (Stressors):**', '* Coastal erosion', '**Logic Description:** Deforestation, often illegal, for fuelwood, timber, and land clearing, reduces mangrove area.']
aquatic_mangrove_sundarbans_stressors["Deforestation"]["Impact on Area"] = 'Direct loss of mangrove habitat.'
aquatic_mangrove_sundarbans_stressors["Deforestation"]["Impact on Biodiversity"] = 'Habitat loss.\nReduced carbon sequestration.\n**Influenced By (Stressors):**\nPoverty and Lack of Alternative Livelihoods: Fuelwood collection, timber harvesting.\nWeak Law Enforcement.\nCorruption.\n**Influences (Stressors):**\n* Coastal erosion\n**Logic Description:** Deforestation, often illegal, for fuelwood, timber, and land clearing, reduces mangrove area.'
aquatic_mangrove_sundarbans_stressors["Deforestation"]["Influenced By"] = ['Poverty and Lack of Alternative Livelihoods: Fuelwood collection, timber harvesting.', 'Weak Law Enforcement.', 'Corruption.', '**Influences (Stressors):**', '* Coastal erosion', '**Logic Description:** Deforestation, often illegal, for fuelwood, timber, and land clearing, reduces mangrove area.']
aquatic_mangrove_sundarbans_stressors["Deforestation"]["Influences"] = ['* Coastal erosion', '**Logic Description:** Deforestation, often illegal, for fuelwood, timber, and land clearing, reduces mangrove area.']
aquatic_mangrove_sundarbans_stressors["Deforestation"]["Logic Description"] = '---'

# --- Pollution ---
aquatic_mangrove_sundarbans_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., heavy metals, pesticides, plastics) in water, sediment, and mangrove tissues.'
aquatic_mangrove_sundarbans_stressors["Pollution"]["Data Sources"] = ['Water quality monitoring data (limited).', 'Research studies.', '**Impact on Area:** Degradation of water quality; contamination of sediments.', '**Impact on Biodiversity:**', 'Toxic effects on mangroves and associated fauna.', 'Impacts on fish populations.', 'Potential for bioaccumulation in the food chain.', '**Influenced By (Stressors):**', 'Industrial Discharge: From industries located upstream.', 'Agricultural Runoff: Pesticides and fertilizers.', 'Urban Runoff: Sewage and industrial effluent.', 'Shipping Activities: Oil spills and discharge of waste.', '**Influences (Stressors):**', 'Mangrove Health.', 'Water Quality.', '* Wildlife populations.', '**Logic Description:** Pollution from upstream industrial sources, agriculture, and shipping activities degrades water quality and impacts the Sundarbans ecosystem.']
aquatic_mangrove_sundarbans_stressors["Pollution"]["Impact on Area"] = 'Degradation of water quality; contamination of sediments.'
aquatic_mangrove_sundarbans_stressors["Pollution"]["Impact on Biodiversity"] = 'Toxic effects on mangroves and associated fauna.\nImpacts on fish populations.\nPotential for bioaccumulation in the food chain.\n**Influenced By (Stressors):**\nIndustrial Discharge: From industries located upstream.\nAgricultural Runoff: Pesticides and fertilizers.\nUrban Runoff: Sewage and industrial effluent.\nShipping Activities: Oil spills and discharge of waste.\n**Influences (Stressors):**\nMangrove Health.\nWater Quality.\n* Wildlife populations.\n**Logic Description:** Pollution from upstream industrial sources, agriculture, and shipping activities degrades water quality and impacts the Sundarbans ecosystem.'
aquatic_mangrove_sundarbans_stressors["Pollution"]["Influenced By"] = ['Industrial Discharge: From industries located upstream.', 'Agricultural Runoff: Pesticides and fertilizers.', 'Urban Runoff: Sewage and industrial effluent.', 'Shipping Activities: Oil spills and discharge of waste.', '**Influences (Stressors):**', 'Mangrove Health.', 'Water Quality.', '* Wildlife populations.', '**Logic Description:** Pollution from upstream industrial sources, agriculture, and shipping activities degrades water quality and impacts the Sundarbans ecosystem.']
aquatic_mangrove_sundarbans_stressors["Pollution"]["Influences"] = ['Mangrove Health.', 'Water Quality.', '* Wildlife populations.', '**Logic Description:** Pollution from upstream industrial sources, agriculture, and shipping activities degrades water quality and impacts the Sundarbans ecosystem.']
aquatic_mangrove_sundarbans_stressors["Pollution"]["Logic Description"] = '---'

# --- Climate Change ---
aquatic_mangrove_sundarbans_stressors["Climate Change"]["Metric"] = 'Sea level rise (mm/year); sea surface temperature (°C); changes in precipitation patterns; increased storm intensity and frequency; cyclone frequency.'
aquatic_mangrove_sundarbans_stressors["Climate Change"]["Data Sources"] = ['Climate models.', 'Tide gauge records.', 'Remote sensing data.', 'Historical weather records.', '**Impact on Area:**', 'Coastal inundation and erosion: The Sundarbans is *extremely* vulnerable to sea level rise.', 'Increased salinity in estuaries and waterways.', 'Increased damage from storm surges.', '**Impact on Biodiversity:**', 'Loss of mangrove habitat due to sea level rise.', 'Shifts in species distributions.', 'Increased stress on mangroves and associated fauna.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Sea Level Rise (the dominant impact).', 'Coastal Erosion.', 'Salinity Intrusion.', 'Storm Surge.', '**Logic Description:** Climate change, particularly sea level rise, poses an *existential* threat to the Sundarbans. Increased storm intensity and changes in freshwater input also have significant impacts.']
aquatic_mangrove_sundarbans_stressors["Climate Change"]["Impact on Area"] = ''
aquatic_mangrove_sundarbans_stressors["Climate Change"]["Impact on Biodiversity"] = 'Loss of mangrove habitat due to sea level rise.\nShifts in species distributions.\nIncreased stress on mangroves and associated fauna.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nSea Level Rise (the dominant impact).\nCoastal Erosion.\nSalinity Intrusion.\nStorm Surge.\n**Logic Description:** Climate change, particularly sea level rise, poses an *existential* threat to the Sundarbans. Increased storm intensity and changes in freshwater input also have significant impacts.'
aquatic_mangrove_sundarbans_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Sea Level Rise (the dominant impact).', 'Coastal Erosion.', 'Salinity Intrusion.', 'Storm Surge.', '**Logic Description:** Climate change, particularly sea level rise, poses an *existential* threat to the Sundarbans. Increased storm intensity and changes in freshwater input also have significant impacts.']
aquatic_mangrove_sundarbans_stressors["Climate Change"]["Influences"] = ['Sea Level Rise (the dominant impact).', 'Coastal Erosion.', 'Salinity Intrusion.', 'Storm Surge.', '**Logic Description:** Climate change, particularly sea level rise, poses an *existential* threat to the Sundarbans. Increased storm intensity and changes in freshwater input also have significant impacts.']
aquatic_mangrove_sundarbans_stressors["Climate Change"]["Logic Description"] = '---'

# --- Upstream Water Diversions ---
aquatic_mangrove_sundarbans_stressors["Upstream Water Diversions"]["Metric"] = 'River flow rates into the Sundarbans.'
aquatic_mangrove_sundarbans_stressors["Upstream Water Diversions"]["Data Sources"] = ['* Government data', '* Research.', '**Impact on Area:** Altered salinity and sediment delivery.', '**Impact on Biodiversity:**', '* Impacts on mangrove and aquatic species.', '**Influenced By (Stressors):**', '* Water management in India and Bangladesh (e.g., Farakka Barrage).', '**Influences (Stressors):**', '* Salinity.', '* Sedimentation.', '**Logic Description:** Upstream water diversions reduce freshwater flow, increasing salinity and affecting sediment delivery.']
aquatic_mangrove_sundarbans_stressors["Upstream Water Diversions"]["Impact on Area"] = 'Altered salinity and sediment delivery.'
aquatic_mangrove_sundarbans_stressors["Upstream Water Diversions"]["Impact on Biodiversity"] = '* Impacts on mangrove and aquatic species.\n**Influenced By (Stressors):**\n* Water management in India and Bangladesh (e.g., Farakka Barrage).\n**Influences (Stressors):**\n* Salinity.\n* Sedimentation.\n**Logic Description:** Upstream water diversions reduce freshwater flow, increasing salinity and affecting sediment delivery.'
aquatic_mangrove_sundarbans_stressors["Upstream Water Diversions"]["Influenced By"] = ['* Water management in India and Bangladesh (e.g., Farakka Barrage).', '**Influences (Stressors):**', '* Salinity.', '* Sedimentation.', '**Logic Description:** Upstream water diversions reduce freshwater flow, increasing salinity and affecting sediment delivery.']
aquatic_mangrove_sundarbans_stressors["Upstream Water Diversions"]["Influences"] = ['* Salinity.', '* Sedimentation.', '**Logic Description:** Upstream water diversions reduce freshwater flow, increasing salinity and affecting sediment delivery.']
aquatic_mangrove_sundarbans_stressors["Upstream Water Diversions"]["Logic Description"] = '---'

