from stressor_templates import *
import copy

deserts_sahara_stressors = {
    "Climate Change": copy.deepcopy(climate_change_template),
    "Water Extraction": copy.deepcopy(water_extraction_template),
    "Desertification": {},
}

# --- Climate Change ---
deserts_sahara_stressors["Climate Change"]["Metric"] = 'Temperature increase (°C); changes in precipitation (mm/year, seasonality); increased frequency and severity of drought; increased frequency of extreme heat events.'
deserts_sahara_stressors["Climate Change"]["Data Sources"] = ['Climate models (global and regional).', 'Historical weather records (often sparse in desert regions).', 'Remote sensing data.', '**Impact on Area:** Indirect; changes in water availability, potentially leading to desertification and expansion of desert areas. *Expansion of the Sahara is a major concern.*', '**Impact on Biodiversity:**', 'Increased stress on desert-adapted species, potentially exceeding their tolerance limits.', 'Changes in species distributions (shifts towards areas with more favorable conditions, if possible).', 'Increased risk of local extinctions.', 'Impacts on water sources (springs, oases), affecting wildlife.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions: The primary driver.', '**Influences (Stressors):**', 'Water Availability: Further reduces already scarce water resources.', 'Desertification: *Expansion of the desert is a major concern.*', 'Dust Storms: May increase in frequency and intensity.', '**Logic Description:**  The Sahara is already extremely hot and dry. Climate change is projected to make it even hotter and, in some areas, drier, exacerbating desertification and impacting the already limited biodiversity.  *Dust storms originating in the Sahara can have far-reaching impacts.*']
deserts_sahara_stressors["Climate Change"]["Impact on Area"] = 'Indirect; changes in water availability, potentially leading to desertification and expansion of desert areas. *Expansion of the Sahara is a major concern.*'
deserts_sahara_stressors["Climate Change"]["Impact on Biodiversity"] = 'Increased stress on desert-adapted species, potentially exceeding their tolerance limits.\nChanges in species distributions (shifts towards areas with more favorable conditions, if possible).\nIncreased risk of local extinctions.\nImpacts on water sources (springs, oases), affecting wildlife.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions: The primary driver.\n**Influences (Stressors):**\nWater Availability: Further reduces already scarce water resources.\nDesertification: *Expansion of the desert is a major concern.*\nDust Storms: May increase in frequency and intensity.\n**Logic Description:**  The Sahara is already extremely hot and dry. Climate change is projected to make it even hotter and, in some areas, drier, exacerbating desertification and impacting the already limited biodiversity.  *Dust storms originating in the Sahara can have far-reaching impacts.*'
deserts_sahara_stressors["Climate Change"]["Influenced By"] = ['Global Greenhouse Gas Emissions: The primary driver.', '**Influences (Stressors):**', 'Water Availability: Further reduces already scarce water resources.', 'Desertification: *Expansion of the desert is a major concern.*', 'Dust Storms: May increase in frequency and intensity.', '**Logic Description:**  The Sahara is already extremely hot and dry. Climate change is projected to make it even hotter and, in some areas, drier, exacerbating desertification and impacting the already limited biodiversity.  *Dust storms originating in the Sahara can have far-reaching impacts.*']
deserts_sahara_stressors["Climate Change"]["Influences"] = ['Water Availability: Further reduces already scarce water resources.', 'Desertification: *Expansion of the desert is a major concern.*', 'Dust Storms: May increase in frequency and intensity.', '**Logic Description:**  The Sahara is already extremely hot and dry. Climate change is projected to make it even hotter and, in some areas, drier, exacerbating desertification and impacting the already limited biodiversity.  *Dust storms originating in the Sahara can have far-reaching impacts.*']
deserts_sahara_stressors["Climate Change"]["Logic Description"] = '---'

# --- Water Extraction ---
deserts_sahara_stressors["Water Extraction"]["Metric"] = 'Volume of groundwater extracted (m³/year); changes in groundwater levels (meters).'
deserts_sahara_stressors["Water Extraction"]["Data Sources"] = ['Governmental water resource agencies (where available - data may be limited).', 'Research studies.', 'Remote sensing (in some cases).', '**Impact on Area:** Depletion of groundwater resources; loss of oases.', '**Impact on Biodiversity:**', 'Loss of water sources for wildlife.', 'Decline of vegetation dependent on groundwater.', '**Influenced By (Stressors):**', 'Population Growth: Increased demand for water.', 'Agricultural Expansion: Irrigation projects (often unsustainable in the long term).', '**Influences (Stressors):**', 'Water Availability: Directly impacts water resources.', '**Logic Description:** Groundwater extraction, often for agriculture, can deplete aquifers and threaten oases, which are critical habitats in the Sahara.']
deserts_sahara_stressors["Water Extraction"]["Impact on Area"] = 'Depletion of groundwater resources; loss of oases.'
deserts_sahara_stressors["Water Extraction"]["Impact on Biodiversity"] = 'Loss of water sources for wildlife.\nDecline of vegetation dependent on groundwater.\n**Influenced By (Stressors):**\nPopulation Growth: Increased demand for water.\nAgricultural Expansion: Irrigation projects (often unsustainable in the long term).\n**Influences (Stressors):**\nWater Availability: Directly impacts water resources.\n**Logic Description:** Groundwater extraction, often for agriculture, can deplete aquifers and threaten oases, which are critical habitats in the Sahara.'
deserts_sahara_stressors["Water Extraction"]["Influenced By"] = ['Population Growth: Increased demand for water.', 'Agricultural Expansion: Irrigation projects (often unsustainable in the long term).', '**Influences (Stressors):**', 'Water Availability: Directly impacts water resources.', '**Logic Description:** Groundwater extraction, often for agriculture, can deplete aquifers and threaten oases, which are critical habitats in the Sahara.']
deserts_sahara_stressors["Water Extraction"]["Influences"] = ['Water Availability: Directly impacts water resources.', '**Logic Description:** Groundwater extraction, often for agriculture, can deplete aquifers and threaten oases, which are critical habitats in the Sahara.']
deserts_sahara_stressors["Water Extraction"]["Logic Description"] = '---'

# --- Desertification ---
deserts_sahara_stressors["Desertification"]["Data Sources"] = ['* Remote sensing.', '* Research studies.', '**Impact on Area:** Expansion of desert area.', '**Impact on Biodiversity:**', 'Loss of habitat.', 'Shifts in species composition.', '**Influenced By (Stressors):**', 'Climate Change.', '* Overgrazing.', '* Unsustainable water use.', 'Deforestation (in transition zones).', '**Influences (Stressors):**', '* Further exacerbates climate change impacts.', '**Logic Description:** The Sahara is expanding, driven by climate and human activities.']
deserts_sahara_stressors["Desertification"]["Impact on Area"] = 'Expansion of desert area.'
deserts_sahara_stressors["Desertification"]["Impact on Biodiversity"] = 'Loss of habitat.\nShifts in species composition.\n**Influenced By (Stressors):**\nClimate Change.\n* Overgrazing.\n* Unsustainable water use.\nDeforestation (in transition zones).\n**Influences (Stressors):**\n* Further exacerbates climate change impacts.\n**Logic Description:** The Sahara is expanding, driven by climate and human activities.'
deserts_sahara_stressors["Desertification"]["Influenced By"] = ['Climate Change.', '* Overgrazing.', '* Unsustainable water use.', 'Deforestation (in transition zones).', '**Influences (Stressors):**', '* Further exacerbates climate change impacts.', '**Logic Description:** The Sahara is expanding, driven by climate and human activities.']
deserts_sahara_stressors["Desertification"]["Influences"] = ['* Further exacerbates climate change impacts.', '**Logic Description:** The Sahara is expanding, driven by climate and human activities.']
deserts_sahara_stressors["Desertification"]["Logic Description"] = '---'

