from stressor_templates import *
import copy

deserts_australian_stressors = {
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Altered Fire Regimes": copy.deepcopy(fire_regime_template),
    "Climate Change": copy.deepcopy(climate_change_template),
    "Overgrazing": {},
}

# --- Invasive Species ---
deserts_australian_stressors["Invasive Species"]["Metric"] = 'Abundance and distribution of key invasive species (e.g., feral camels, rabbits, cats, foxes, buffel grass).'
deserts_australian_stressors["Invasive Species"]["Data Sources"] = ['Government reports (Australian Department of Agriculture, Water and the Environment).', 'Research publications.', 'Wildlife surveys.', '**Impact on Area:** Changes in vegetation composition; increased grazing pressure; increased predation pressure.', '**Impact on Biodiversity:**', 'Feral camels: Damage vegetation and compete with native herbivores for water.', 'Rabbits: Overgraze vegetation, contributing to soil erosion.', 'Cats and foxes: Predation on native mammals, birds, and reptiles.', 'Buffel grass: Outcompetes native grasses and increases fire intensity.', '**Influenced By (Stressors):**', 'Historical Introductions: Many invasive species were introduced intentionally or accidentally.', 'Lack of Natural Predators or Competitors.', 'Disturbance: Overgrazing, land clearing, and altered fire regimes can create opportunities for invasives.', '* Climate Change', '**Influences (Stressors):**', 'Native Species Populations: A *major* impact.', 'Fire Regimes: (e.g., buffel grass).', 'Ecosystem Functioning.', '**Logic Description:** Invasive species are a *major* threat to the biodiversity of Australian deserts. Feral animals (camels, rabbits, cats, foxes) and invasive plants (e.g., buffel grass) have had devastating impacts on native species and ecosystems.']
deserts_australian_stressors["Invasive Species"]["Impact on Area"] = 'Changes in vegetation composition; increased grazing pressure; increased predation pressure.'
deserts_australian_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Feral camels: Damage vegetation and compete with native herbivores for water.\nRabbits: Overgraze vegetation, contributing to soil erosion.\nCats and foxes: Predation on native mammals, birds, and reptiles.\nBuffel grass: Outcompetes native grasses and increases fire intensity.\n**Influenced By (Stressors):**\nHistorical Introductions: Many invasive species were introduced intentionally or accidentally.\nLack of Natural Predators or Competitors.\nDisturbance: Overgrazing, land clearing, and altered fire regimes can create opportunities for invasives.\n* Climate Change\n**Influences (Stressors):**\nNative Species Populations: A *major* impact.\nFire Regimes: (e.g., buffel grass).\nEcosystem Functioning.\n**Logic Description:** Invasive species are a *major* threat to the biodiversity of Australian deserts. Feral animals (camels, rabbits, cats, foxes) and invasive plants (e.g., buffel grass) have had devastating impacts on native species and ecosystems.'
deserts_australian_stressors["Invasive Species"]["Influenced By"] = ['Historical Introductions: Many invasive species were introduced intentionally or accidentally.', 'Lack of Natural Predators or Competitors.', 'Disturbance: Overgrazing, land clearing, and altered fire regimes can create opportunities for invasives.', '* Climate Change', '**Influences (Stressors):**', 'Native Species Populations: A *major* impact.', 'Fire Regimes: (e.g., buffel grass).', 'Ecosystem Functioning.', '**Logic Description:** Invasive species are a *major* threat to the biodiversity of Australian deserts. Feral animals (camels, rabbits, cats, foxes) and invasive plants (e.g., buffel grass) have had devastating impacts on native species and ecosystems.']
deserts_australian_stressors["Invasive Species"]["Influences"] = ['Native Species Populations: A *major* impact.', 'Fire Regimes: (e.g., buffel grass).', 'Ecosystem Functioning.', '**Logic Description:** Invasive species are a *major* threat to the biodiversity of Australian deserts. Feral animals (camels, rabbits, cats, foxes) and invasive plants (e.g., buffel grass) have had devastating impacts on native species and ecosystems.']
deserts_australian_stressors["Invasive Species"]["Logic Description"] = '---'
deserts_australian_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_deserts_australian"

# --- Altered Fire Regimes ---
deserts_australian_stressors["Altered Fire Regimes"]["Metric"] = 'Fire frequency; fire intensity; area burned; seasonality of fires.'
deserts_australian_stressors["Altered Fire Regimes"]["Data Sources"] = ['Remote sensing data (fire scars).', 'Historical fire records.', 'Research publications.', '**Impact on Area:** Changes in vegetation structure and composition.', '**Impact on Biodiversity:**', 'Some native species are adapted to specific fire regimes, and changes can be detrimental.', 'Increased fire frequency and intensity (often linked to invasive grasses) can lead to loss of fire-sensitive species.', 'Changes in habitat structure.', '**Influenced By (Stressors):**', 'Invasive Grasses: (e.g., buffel grass) can increase fuel loads and fire intensity.', 'Climate Change: Hotter, drier conditions increase fire risk.', 'Changes in Indigenous Land Management Practices: Traditional burning practices played an important role in shaping Australian ecosystems.', '**Influences (Stressors):**', 'Vegetation Structure.', 'Biodiversity.', '**Logic Description:** Changes in fire regimes, often driven by invasive grasses and climate change, can have significant impacts on Australian desert ecosystems.']
deserts_australian_stressors["Altered Fire Regimes"]["Impact on Area"] = 'Changes in vegetation structure and composition.'
deserts_australian_stressors["Altered Fire Regimes"]["Impact on Biodiversity"] = 'Some native species are adapted to specific fire regimes, and changes can be detrimental.\nIncreased fire frequency and intensity (often linked to invasive grasses) can lead to loss of fire-sensitive species.\nChanges in habitat structure.\n**Influenced By (Stressors):**\nInvasive Grasses: (e.g., buffel grass) can increase fuel loads and fire intensity.\nClimate Change: Hotter, drier conditions increase fire risk.\nChanges in Indigenous Land Management Practices: Traditional burning practices played an important role in shaping Australian ecosystems.\n**Influences (Stressors):**\nVegetation Structure.\nBiodiversity.\n**Logic Description:** Changes in fire regimes, often driven by invasive grasses and climate change, can have significant impacts on Australian desert ecosystems.'
deserts_australian_stressors["Altered Fire Regimes"]["Influenced By"] = ['Invasive Grasses: (e.g., buffel grass) can increase fuel loads and fire intensity.', 'Climate Change: Hotter, drier conditions increase fire risk.', 'Changes in Indigenous Land Management Practices: Traditional burning practices played an important role in shaping Australian ecosystems.', '**Influences (Stressors):**', 'Vegetation Structure.', 'Biodiversity.', '**Logic Description:** Changes in fire regimes, often driven by invasive grasses and climate change, can have significant impacts on Australian desert ecosystems.']
deserts_australian_stressors["Altered Fire Regimes"]["Influences"] = ['Vegetation Structure.', 'Biodiversity.', '**Logic Description:** Changes in fire regimes, often driven by invasive grasses and climate change, can have significant impacts on Australian desert ecosystems.']
deserts_australian_stressors["Altered Fire Regimes"]["Logic Description"] = '---'
deserts_australian_stressors["Altered Fire Regimes"]["Impact Function"] = "impact_altered_fire_regimes_deserts_australian"

# --- Climate Change ---
deserts_australian_stressors["Climate Change"]["Metric"] = 'Temperature increase; changes in rainfall; increased frequency/severity of drought.'
deserts_australian_stressors["Climate Change"]["Data Sources"] = ['* Climate Models', '* Historical data', '**Impact on Area:** Increased aridity.', '**Impact on Biodiversity:**', '* Increased stress.', '* Species shifts', '**Influenced By (Stressors):**', '* Global GHG', '**Influences (Stressors):**', '* Water availability', '* Fire regimes', '**Logic Description:** Climate change impacts.']
deserts_australian_stressors["Climate Change"]["Impact on Area"] = 'Increased aridity.'
deserts_australian_stressors["Climate Change"]["Impact on Biodiversity"] = '* Increased stress.\n* Species shifts\n**Influenced By (Stressors):**\n* Global GHG\n**Influences (Stressors):**\n* Water availability\n* Fire regimes\n**Logic Description:** Climate change impacts.'
deserts_australian_stressors["Climate Change"]["Influenced By"] = ['* Global GHG', '**Influences (Stressors):**', '* Water availability', '* Fire regimes', '**Logic Description:** Climate change impacts.']
deserts_australian_stressors["Climate Change"]["Influences"] = ['* Water availability', '* Fire regimes', '**Logic Description:** Climate change impacts.']
deserts_australian_stressors["Climate Change"]["Logic Description"] = '---'
deserts_australian_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_deserts_australian"

# --- Overgrazing ---
deserts_australian_stressors["Overgrazing"]["Metric"] = 'Livestock and feral herbivore density.'
deserts_australian_stressors["Overgrazing"]["Data Sources"] = ['* Government statistics.', '* Research.', '**Impact on Area:** Vegetation and soil degradation.', '**Impact on Biodiversity:**', '* Impacts on native plant communities.', '**Influenced By (Stressors):**', '* Land management practices', '**Influences (Stressors):**', '* Desertification.', '**Logic Description:** Overgrazing impacts.']
deserts_australian_stressors["Overgrazing"]["Impact on Area"] = 'Vegetation and soil degradation.'
deserts_australian_stressors["Overgrazing"]["Impact on Biodiversity"] = '* Impacts on native plant communities.\n**Influenced By (Stressors):**\n* Land management practices\n**Influences (Stressors):**\n* Desertification.\n**Logic Description:** Overgrazing impacts.'
deserts_australian_stressors["Overgrazing"]["Influenced By"] = ['* Land management practices', '**Influences (Stressors):**', '* Desertification.', '**Logic Description:** Overgrazing impacts.']
deserts_australian_stressors["Overgrazing"]["Influences"] = ['* Desertification.', '**Logic Description:** Overgrazing impacts.']
deserts_australian_stressors["Overgrazing"]["Logic Description"] = '---'
deserts_australian_stressors["Overgrazing"]["Impact Function"] = "impact_overgrazing_deserts_australian"

