from stressor_templates import *
import copy

forests_temperate_forests_appalachian_stressors = {
    "Infrastructure Development": copy.deepcopy(infrastructure_development_template),
    "Deforestation": copy.deepcopy(deforestation_template),
    "Temperature Increase": copy.deepcopy(climate_change_template),
    "Changes in Precipitation": copy.deepcopy(climate_change_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Air Pollution": copy.deepcopy(pollution_template),
}

# --- Infrastructure Development ---
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Metric"] = 'Road density (km/km²); area affected by mining, energy development (e.g., fracking) (ha/year).'
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Data Sources"] = ['US Forest Service data.', 'State and federal transportation agencies.', 'Energy Information Administration (EIA).', 'Remote sensing data.', '**Impact on Area:** Habitat fragmentation; direct loss due to mining and energy infrastructure.', '**Impact on Biodiversity:**', 'Habitat loss and fragmentation.', 'Disruption of ecological corridors.', 'Water pollution from mining and energy development.', 'Increased edge effects', '**Influenced By (Stressors):**', 'Economic Growth: Demand for energy and resources.', 'Population Growth (in some areas).', 'Government Policies: Energy policy, transportation planning.', '**Influences (Stressors):**', 'Deforestation (though often localized around infrastructure).', 'Water Pollution.', 'Air pollution', '**Logic Description:** Infrastructure, including roads and energy development (mining, fracking), fragments habitat and leads to direct habitat loss, impacting biodiversity.']
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Impact on Area"] = 'Habitat fragmentation; direct loss due to mining and energy infrastructure.'
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Impact on Biodiversity"] = 'Habitat loss and fragmentation.\nDisruption of ecological corridors.\nWater pollution from mining and energy development.\nIncreased edge effects\n**Influenced By (Stressors):**\nEconomic Growth: Demand for energy and resources.\nPopulation Growth (in some areas).\nGovernment Policies: Energy policy, transportation planning.\n**Influences (Stressors):**\nDeforestation (though often localized around infrastructure).\nWater Pollution.\nAir pollution\n**Logic Description:** Infrastructure, including roads and energy development (mining, fracking), fragments habitat and leads to direct habitat loss, impacting biodiversity.'
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Influenced By"] = ['Economic Growth: Demand for energy and resources.', 'Population Growth (in some areas).', 'Government Policies: Energy policy, transportation planning.', '**Influences (Stressors):**', 'Deforestation (though often localized around infrastructure).', 'Water Pollution.', 'Air pollution', '**Logic Description:** Infrastructure, including roads and energy development (mining, fracking), fragments habitat and leads to direct habitat loss, impacting biodiversity.']
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Influences"] = ['Deforestation (though often localized around infrastructure).', 'Water Pollution.', 'Air pollution', '**Logic Description:** Infrastructure, including roads and energy development (mining, fracking), fragments habitat and leads to direct habitat loss, impacting biodiversity.']
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Logic Description"] = '---'
forests_temperate_forests_appalachian_stressors["Infrastructure Development"]["Impact Function"] = "impact_infrastructure_development_forests_temperate_forests_appalachian"

# --- Deforestation ---
forests_temperate_forests_appalachian_stressors["Deforestation"]["Metric"] = 'Area of forest cleared per year (ha/year) (although net forest loss may be low or even negative in some areas due to regrowth, *localized* deforestation is still a stressor).'
forests_temperate_forests_appalachian_stressors["Deforestation"]["Data Sources"] = ['US Forest Service data (Forest Inventory and Analysis - FIA).', 'Remote sensing data.', '**Impact on Area:** Localized forest loss; changes in forest age structure.', '**Impact on Biodiversity:**', 'Habitat loss (especially for species requiring mature forest).', 'Changes in species composition.', '**Influenced By (Stressors):**', 'Infrastructure Development.', 'Urban Sprawl.', 'Agricultural Expansion (limited in some areas).', 'Timber Harvesting (depending on management practices).', '**Influences (Stressors):**', 'Changes in forest age and structure affecting biodiversity', '**Logic Description:** While overall forest cover in the Appalachians may be stable or even increasing in some areas due to reforestation, *localized* deforestation due to development, agriculture, and unsustainable timber harvesting continues to be a stressor, impacting habitat quality and biodiversity.']
forests_temperate_forests_appalachian_stressors["Deforestation"]["Impact on Area"] = 'Localized forest loss; changes in forest age structure.'
forests_temperate_forests_appalachian_stressors["Deforestation"]["Impact on Biodiversity"] = 'Habitat loss (especially for species requiring mature forest).\nChanges in species composition.\n**Influenced By (Stressors):**\nInfrastructure Development.\nUrban Sprawl.\nAgricultural Expansion (limited in some areas).\nTimber Harvesting (depending on management practices).\n**Influences (Stressors):**\nChanges in forest age and structure affecting biodiversity\n**Logic Description:** While overall forest cover in the Appalachians may be stable or even increasing in some areas due to reforestation, *localized* deforestation due to development, agriculture, and unsustainable timber harvesting continues to be a stressor, impacting habitat quality and biodiversity.'
forests_temperate_forests_appalachian_stressors["Deforestation"]["Influenced By"] = ['Infrastructure Development.', 'Urban Sprawl.', 'Agricultural Expansion (limited in some areas).', 'Timber Harvesting (depending on management practices).', '**Influences (Stressors):**', 'Changes in forest age and structure affecting biodiversity', '**Logic Description:** While overall forest cover in the Appalachians may be stable or even increasing in some areas due to reforestation, *localized* deforestation due to development, agriculture, and unsustainable timber harvesting continues to be a stressor, impacting habitat quality and biodiversity.']
forests_temperate_forests_appalachian_stressors["Deforestation"]["Influences"] = ['Changes in forest age and structure affecting biodiversity', '**Logic Description:** While overall forest cover in the Appalachians may be stable or even increasing in some areas due to reforestation, *localized* deforestation due to development, agriculture, and unsustainable timber harvesting continues to be a stressor, impacting habitat quality and biodiversity.']
forests_temperate_forests_appalachian_stressors["Deforestation"]["Logic Description"] = '---'
forests_temperate_forests_appalachian_stressors["Deforestation"]["Impact Function"] = "impact_deforestation_forests_temperate_forests_appalachian"

# --- Temperature Increase ---
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Metric"] = 'Average annual temperature increase (°C).'
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Data Sources"] = ['Global and regional climate models.', 'Historical temperature records.', '**Impact on Area:** Indirect.', '**Impact on Biodiversity:**', 'Shifts in species distributions (northward and upslope).', 'Increased physiological stress.', 'Changes in phenology (timing of biological events).', 'Increased susceptibility to pests and diseases.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Changes in Precipitation.', 'Increased pest and pathogen outbreaks.', '**Logic Description:** Climate change leads to warming temperatures, impacting species distributions, physiology, and increasing vulnerability to other stressors.']
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Impact on Area"] = 'Indirect.'
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Impact on Biodiversity"] = 'Shifts in species distributions (northward and upslope).\nIncreased physiological stress.\nChanges in phenology (timing of biological events).\nIncreased susceptibility to pests and diseases.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nChanges in Precipitation.\nIncreased pest and pathogen outbreaks.\n**Logic Description:** Climate change leads to warming temperatures, impacting species distributions, physiology, and increasing vulnerability to other stressors.'
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Changes in Precipitation.', 'Increased pest and pathogen outbreaks.', '**Logic Description:** Climate change leads to warming temperatures, impacting species distributions, physiology, and increasing vulnerability to other stressors.']
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Influences"] = ['Changes in Precipitation.', 'Increased pest and pathogen outbreaks.', '**Logic Description:** Climate change leads to warming temperatures, impacting species distributions, physiology, and increasing vulnerability to other stressors.']
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Logic Description"] = '---'
forests_temperate_forests_appalachian_stressors["Temperature Increase"]["Impact Function"] = "impact_temperature_increase_forests_temperate_forests_appalachian"

# --- Changes in Precipitation ---
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Metric"] = 'Change in annual precipitation (mm/year); changes in seasonality (e.g., more intense rainfall events, longer dry periods).'
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Data Sources"] = ['Climate models.', 'Historical weather records.', '**Impact on Area:** Indirect.', '**Impact on Biodiversity:**', 'Changes in species composition (favoring drought-tolerant or flood-tolerant species).', 'Altered streamflow regimes.', 'Increased risk of drought stress in some areas.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Water quality in streams', '**Logic Description:** Climate change alters precipitation patterns, leading to shifts in species composition and impacting water resources.']
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Impact on Area"] = 'Indirect.'
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Impact on Biodiversity"] = 'Changes in species composition (favoring drought-tolerant or flood-tolerant species).\nAltered streamflow regimes.\nIncreased risk of drought stress in some areas.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nWater quality in streams\n**Logic Description:** Climate change alters precipitation patterns, leading to shifts in species composition and impacting water resources.'
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Water quality in streams', '**Logic Description:** Climate change alters precipitation patterns, leading to shifts in species composition and impacting water resources.']
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Influences"] = ['Water quality in streams', '**Logic Description:** Climate change alters precipitation patterns, leading to shifts in species composition and impacting water resources.']
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Logic Description"] = '---'
forests_temperate_forests_appalachian_stressors["Changes in Precipitation"]["Impact Function"] = "impact_changes_in_precipitation_forests_temperate_forests_appalachian"

# --- Invasive Species ---
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Metric"] = 'Abundance and distribution of key invasive species (e.g., emerald ash borer, hemlock woolly adelgid, gypsy moth, garlic mustard).'
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Data Sources"] = ['Forest health monitoring programs (US Forest Service, state agencies).', 'Research studies.', '**Impact on Area:** Changes in forest composition and structure (loss of key tree species).', '**Impact on Biodiversity:**', 'Decline of native tree species.', 'Cascading effects on other species that depend on those trees.', 'Altered ecosystem processes (e.g., nutrient cycling).', '**Influenced By (Stressors):**', 'Global Trade and Travel (introduction of new species).', 'Climate Change (may favor some invasive species).', 'Disturbance (e.g., logging, which can create opportunities for invasives).', '**Influences (Stressors):**', '* Forest Composition and structure', '**Logic Description:** Invasive species, often introduced through human activities, can cause significant damage to forests, leading to the decline of native species and altering ecosystem function. Climate change may exacerbate the impacts of some invasives.']
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Impact on Area"] = 'Changes in forest composition and structure (loss of key tree species).'
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Decline of native tree species.\nCascading effects on other species that depend on those trees.\nAltered ecosystem processes (e.g., nutrient cycling).\n**Influenced By (Stressors):**\nGlobal Trade and Travel (introduction of new species).\nClimate Change (may favor some invasive species).\nDisturbance (e.g., logging, which can create opportunities for invasives).\n**Influences (Stressors):**\n* Forest Composition and structure\n**Logic Description:** Invasive species, often introduced through human activities, can cause significant damage to forests, leading to the decline of native species and altering ecosystem function. Climate change may exacerbate the impacts of some invasives.'
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Influenced By"] = ['Global Trade and Travel (introduction of new species).', 'Climate Change (may favor some invasive species).', 'Disturbance (e.g., logging, which can create opportunities for invasives).', '**Influences (Stressors):**', '* Forest Composition and structure', '**Logic Description:** Invasive species, often introduced through human activities, can cause significant damage to forests, leading to the decline of native species and altering ecosystem function. Climate change may exacerbate the impacts of some invasives.']
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Influences"] = ['* Forest Composition and structure', '**Logic Description:** Invasive species, often introduced through human activities, can cause significant damage to forests, leading to the decline of native species and altering ecosystem function. Climate change may exacerbate the impacts of some invasives.']
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Logic Description"] = '---'
forests_temperate_forests_appalachian_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_forests_temperate_forests_appalachian"

# --- Air Pollution ---
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., ozone, nitrogen oxides, sulfur dioxide) (parts per billion - ppb, micrograms per cubic meter - µg/m³).'
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Data Sources"] = ['* EPA Air Quality System (AQS).', '* National Atmospheric Deposition Program (NADP).', '**Impact on Area:** Reduced forest health and productivity.', '**Impact on Biodiversity:**', 'Damage to foliage, reducing photosynthesis.', ' Increased susceptibility to pests and diseases.', 'Acidification of soils and water bodies, impacting aquatic life.', '**Influenced By (Stressors):**', 'Industrial Activity.', 'Fossil Fuel Combustion (power plants, vehicles).', 'Agricultural Practices (fertilizer use).', '**Influences (Stressors):**', '* Water Quality', '* Forest Health', '**Logic Description:** Air pollution, from industrial activity and fossil fuel combustion, damages trees, reduces forest productivity, and can acidify soils and water.']
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Impact on Area"] = 'Reduced forest health and productivity.'
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Impact on Biodiversity"] = 'Damage to foliage, reducing photosynthesis.\n Increased susceptibility to pests and diseases.\nAcidification of soils and water bodies, impacting aquatic life.\n**Influenced By (Stressors):**\nIndustrial Activity.\nFossil Fuel Combustion (power plants, vehicles).\nAgricultural Practices (fertilizer use).\n**Influences (Stressors):**\n* Water Quality\n* Forest Health\n**Logic Description:** Air pollution, from industrial activity and fossil fuel combustion, damages trees, reduces forest productivity, and can acidify soils and water.'
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Influenced By"] = ['Industrial Activity.', 'Fossil Fuel Combustion (power plants, vehicles).', 'Agricultural Practices (fertilizer use).', '**Influences (Stressors):**', '* Water Quality', '* Forest Health', '**Logic Description:** Air pollution, from industrial activity and fossil fuel combustion, damages trees, reduces forest productivity, and can acidify soils and water.']
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Influences"] = ['* Water Quality', '* Forest Health', '**Logic Description:** Air pollution, from industrial activity and fossil fuel combustion, damages trees, reduces forest productivity, and can acidify soils and water.']
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Logic Description"] = '---'
forests_temperate_forests_appalachian_stressors["Air Pollution"]["Impact Function"] = "impact_air_pollution_forests_temperate_forests_appalachian"

