from stressor_templates import *
import copy

forests_rainforest_sundaland_stressors = {
    "Infrastructure Development": copy.deepcopy(infrastructure_development_template),
    "Deforestation": copy.deepcopy(deforestation_template),
    "Temperature Increase": copy.deepcopy(climate_change_template),
    "Changes in Precipitation": copy.deepcopy(climate_change_template),
    "Wildfires": copy.deepcopy(fire_regime_template),
    "Peatland Degradation": {},
}

# --- Infrastructure Development ---
forests_rainforest_sundaland_stressors["Infrastructure Development"]["Metric"] = 'Road length (km/year); area affected by other projects (ha/year).'
forests_rainforest_sundaland_stressors["Infrastructure Development"]["Data Sources"] = ['Government and industry reports.', 'Remote sensing data.', 'NGO reports.', '**Impact on Area:** Direct Loss and fragmentation', '**Impact on Biodiversity:**', 'Habitat Loss', 'Increased Access', 'Disruption of Corridors', '**Influenced By (Stressors):**', 'Economic Growth', 'Population Growth', 'Government Policies', 'Global commodity prices', '**Influences (Stressors):**', 'Deforestation', 'Wildfires', 'Pollution', '**Logic Description:** Similar to other rainforests, but with high pressure from palm oil plantation development.']
forests_rainforest_sundaland_stressors["Infrastructure Development"]["Impact on Area"] = 'Direct Loss and fragmentation'
forests_rainforest_sundaland_stressors["Infrastructure Development"]["Impact on Biodiversity"] = 'Habitat Loss\nIncreased Access\nDisruption of Corridors\n**Influenced By (Stressors):**\nEconomic Growth\nPopulation Growth\nGovernment Policies\nGlobal commodity prices\n**Influences (Stressors):**\nDeforestation\nWildfires\nPollution\n**Logic Description:** Similar to other rainforests, but with high pressure from palm oil plantation development.'
forests_rainforest_sundaland_stressors["Infrastructure Development"]["Influenced By"] = ['Economic Growth', 'Population Growth', 'Government Policies', 'Global commodity prices', '**Influences (Stressors):**', 'Deforestation', 'Wildfires', 'Pollution', '**Logic Description:** Similar to other rainforests, but with high pressure from palm oil plantation development.']
forests_rainforest_sundaland_stressors["Infrastructure Development"]["Influences"] = ['Deforestation', 'Wildfires', 'Pollution', '**Logic Description:** Similar to other rainforests, but with high pressure from palm oil plantation development.']
forests_rainforest_sundaland_stressors["Infrastructure Development"]["Logic Description"] = '---'

# --- Deforestation ---
forests_rainforest_sundaland_stressors["Deforestation"]["Metric"] = 'Area of Forest Cleared (ha/year)'
forests_rainforest_sundaland_stressors["Deforestation"]["Data Sources"] = ['Remote Sensing', 'NGO and research reports', '**Impact on Area:** Direct Reduction', '**Impact on Biodiversity:**', 'Habitat Loss', 'Carbon Emissions', '**Influenced By (Stressors):**', 'Infrastructure Development', 'Economic Growth (Palm Oil)', 'Global Commodity Prices', 'Population Growth', 'Government Policies', '**Influences (Stressors):**', 'Wildfires', 'Peatland Degradation', '**Logic Description:** Palm oil plantation expansion is the dominant driver, along with logging and other agricultural expansion. Significant impact on peatlands (see below).']
forests_rainforest_sundaland_stressors["Deforestation"]["Impact on Area"] = 'Direct Reduction'
forests_rainforest_sundaland_stressors["Deforestation"]["Impact on Biodiversity"] = 'Habitat Loss\nCarbon Emissions\n**Influenced By (Stressors):**\nInfrastructure Development\nEconomic Growth (Palm Oil)\nGlobal Commodity Prices\nPopulation Growth\nGovernment Policies\n**Influences (Stressors):**\nWildfires\nPeatland Degradation\n**Logic Description:** Palm oil plantation expansion is the dominant driver, along with logging and other agricultural expansion. Significant impact on peatlands (see below).'
forests_rainforest_sundaland_stressors["Deforestation"]["Influenced By"] = ['Infrastructure Development', 'Economic Growth (Palm Oil)', 'Global Commodity Prices', 'Population Growth', 'Government Policies', '**Influences (Stressors):**', 'Wildfires', 'Peatland Degradation', '**Logic Description:** Palm oil plantation expansion is the dominant driver, along with logging and other agricultural expansion. Significant impact on peatlands (see below).']
forests_rainforest_sundaland_stressors["Deforestation"]["Influences"] = ['Wildfires', 'Peatland Degradation', '**Logic Description:** Palm oil plantation expansion is the dominant driver, along with logging and other agricultural expansion. Significant impact on peatlands (see below).']
forests_rainforest_sundaland_stressors["Deforestation"]["Logic Description"] = '---'

# --- Temperature Increase ---
forests_rainforest_sundaland_stressors["Temperature Increase"]["Metric"] = 'Average annual temperature increase (Celsius)'
forests_rainforest_sundaland_stressors["Temperature Increase"]["Data Sources"] = ['Global and Regional climate models.', 'Limited historical data.', '**Impact on Area**: Indirect', '**Impact on Biodiversity:**', 'Species shifts', 'Physiological Stress', '**Influenced By (Stressors):**', 'Global GHG Emissions', 'Deforestation', 'Peatland Degradation', '**Influences (Stressors):**', 'Wildfires', 'Changes in Precipitation', '**Logic Description:** Global warming amplified by deforestation and peatland degradation.']
forests_rainforest_sundaland_stressors["Temperature Increase"]["Impact on Biodiversity"] = 'Species shifts\nPhysiological Stress\n**Influenced By (Stressors):**\nGlobal GHG Emissions\nDeforestation\nPeatland Degradation\n**Influences (Stressors):**\nWildfires\nChanges in Precipitation\n**Logic Description:** Global warming amplified by deforestation and peatland degradation.'
forests_rainforest_sundaland_stressors["Temperature Increase"]["Influenced By"] = ['Global GHG Emissions', 'Deforestation', 'Peatland Degradation', '**Influences (Stressors):**', 'Wildfires', 'Changes in Precipitation', '**Logic Description:** Global warming amplified by deforestation and peatland degradation.']
forests_rainforest_sundaland_stressors["Temperature Increase"]["Influences"] = ['Wildfires', 'Changes in Precipitation', '**Logic Description:** Global warming amplified by deforestation and peatland degradation.']
forests_rainforest_sundaland_stressors["Temperature Increase"]["Logic Description"] = '---'

# --- Changes in Precipitation ---
forests_rainforest_sundaland_stressors["Changes in Precipitation"]["Metric"] = 'Change in annual precipitation; dry season length/severity'
forests_rainforest_sundaland_stressors["Changes in Precipitation"]["Data Sources"] = ['Climate models.', 'Limited historical data.', '**Impact on Area:** Indirect', '**Impact on Biodiversity:**', 'Species shifts', 'Drought stress', '**Influenced By (Stressors):**', 'Global GHG Emissions', 'Deforestation', '**Influences (Stressors):**', 'Wildfires', 'Peatland Fires', '**Logic Description:** Changes in rainfall patterns and increased drought risk.']
forests_rainforest_sundaland_stressors["Changes in Precipitation"]["Impact on Area"] = 'Indirect'
forests_rainforest_sundaland_stressors["Changes in Precipitation"]["Impact on Biodiversity"] = 'Species shifts\nDrought stress\n**Influenced By (Stressors):**\nGlobal GHG Emissions\nDeforestation\n**Influences (Stressors):**\nWildfires\nPeatland Fires\n**Logic Description:** Changes in rainfall patterns and increased drought risk.'
forests_rainforest_sundaland_stressors["Changes in Precipitation"]["Influenced By"] = ['Global GHG Emissions', 'Deforestation', '**Influences (Stressors):**', 'Wildfires', 'Peatland Fires', '**Logic Description:** Changes in rainfall patterns and increased drought risk.']
forests_rainforest_sundaland_stressors["Changes in Precipitation"]["Influences"] = ['Wildfires', 'Peatland Fires', '**Logic Description:** Changes in rainfall patterns and increased drought risk.']
forests_rainforest_sundaland_stressors["Changes in Precipitation"]["Logic Description"] = '---'

# --- Wildfires ---
forests_rainforest_sundaland_stressors["Wildfires"]["Metric"] = 'Number of fires, Area Burned'
forests_rainforest_sundaland_stressors["Wildfires"]["Data Sources"] = ['Remote Sensing.', 'Local reports.', '**Impact on Area**: Direct loss, particularly of peatland.', '**Impact on Biodiversity:**', 'Mortality.', 'Habitat loss.', 'Severe air pollution (haze).', '**Influenced By (Stressors):**', 'Deforestation.', 'Temperature Increase.', 'Changes in Precipitation.', 'Peatland Drainage.', 'Human Activities (land clearing).', '**Influences (Stressors):**', 'Deforestation.', 'Peatland Degradation.', 'Climate Change (through massive carbon emissions).', '**Logic Description:** Wildfires, often intentionally set for land clearing (especially for palm oil), are a HUGE problem in Sundaland/Southeast Asia, particularly due to the presence of peatlands. These fires release massive amounts of carbon and cause severe regional air pollution.']
forests_rainforest_sundaland_stressors["Wildfires"]["Impact on Biodiversity"] = 'Mortality.\nHabitat loss.\nSevere air pollution (haze).\n**Influenced By (Stressors):**\nDeforestation.\nTemperature Increase.\nChanges in Precipitation.\nPeatland Drainage.\nHuman Activities (land clearing).\n**Influences (Stressors):**\nDeforestation.\nPeatland Degradation.\nClimate Change (through massive carbon emissions).\n**Logic Description:** Wildfires, often intentionally set for land clearing (especially for palm oil), are a HUGE problem in Sundaland/Southeast Asia, particularly due to the presence of peatlands. These fires release massive amounts of carbon and cause severe regional air pollution.'
forests_rainforest_sundaland_stressors["Wildfires"]["Influenced By"] = ['Deforestation.', 'Temperature Increase.', 'Changes in Precipitation.', 'Peatland Drainage.', 'Human Activities (land clearing).', '**Influences (Stressors):**', 'Deforestation.', 'Peatland Degradation.', 'Climate Change (through massive carbon emissions).', '**Logic Description:** Wildfires, often intentionally set for land clearing (especially for palm oil), are a HUGE problem in Sundaland/Southeast Asia, particularly due to the presence of peatlands. These fires release massive amounts of carbon and cause severe regional air pollution.']
forests_rainforest_sundaland_stressors["Wildfires"]["Influences"] = ['Deforestation.', 'Peatland Degradation.', 'Climate Change (through massive carbon emissions).', '**Logic Description:** Wildfires, often intentionally set for land clearing (especially for palm oil), are a HUGE problem in Sundaland/Southeast Asia, particularly due to the presence of peatlands. These fires release massive amounts of carbon and cause severe regional air pollution.']
forests_rainforest_sundaland_stressors["Wildfires"]["Logic Description"] = '---'

# --- Peatland Degradation ---
forests_rainforest_sundaland_stressors["Peatland Degradation"]["Data Sources"] = ['Remote sensing (measuring subsidence, vegetation changes).', 'Field measurements of water table depth.', 'Reports from organizations specializing in peatland conservation.', '**Impact on Area:** Loss of peatland ecosystem (which is a distinct subset of the rainforest area).', '**Impact on Biodiversity:**', 'Loss of specialized peat swamp forest species.', 'Massive carbon emissions (peat is a huge carbon store).', 'Increased fire risk.', 'Subsidence (land sinking), leading to flooding and infrastructure damage.', '**Influenced By (Stressors):**', 'Infrastructure Development (drainage canals).', 'Deforestation (clearing of peat swamp forests).', 'Agricultural Expansion (primarily palm oil and pulpwood plantations).', 'Climate Change (changes in precipitation and temperature can exacerbate drying).', '**Influences (Stressors):**', 'Wildfires (drained peat is highly flammable).', 'Climate Change (through carbon emissions).', 'Flooding (due to subsidence).', '**Logic Description:** Peatlands are waterlogged ecosystems with thick layers of partially decayed organic matter. Drainage for agriculture (especially palm oil) and logging causes the peat to decompose, releasing massive amounts of carbon dioxide. Drained peat is also extremely vulnerable to fire. This is a critical stressor specific to Sundaland/Southeast Asia (and to a lesser extent, other areas with peat swamp forests).']
forests_rainforest_sundaland_stressors["Peatland Degradation"]["Impact on Area"] = 'Loss of peatland ecosystem (which is a distinct subset of the rainforest area).'
forests_rainforest_sundaland_stressors["Peatland Degradation"]["Impact on Biodiversity"] = 'Loss of specialized peat swamp forest species.\nMassive carbon emissions (peat is a huge carbon store).\nIncreased fire risk.\nSubsidence (land sinking), leading to flooding and infrastructure damage.\n**Influenced By (Stressors):**\nInfrastructure Development (drainage canals).\nDeforestation (clearing of peat swamp forests).\nAgricultural Expansion (primarily palm oil and pulpwood plantations).\nClimate Change (changes in precipitation and temperature can exacerbate drying).\n**Influences (Stressors):**\nWildfires (drained peat is highly flammable).\nClimate Change (through carbon emissions).\nFlooding (due to subsidence).\n**Logic Description:** Peatlands are waterlogged ecosystems with thick layers of partially decayed organic matter. Drainage for agriculture (especially palm oil) and logging causes the peat to decompose, releasing massive amounts of carbon dioxide. Drained peat is also extremely vulnerable to fire. This is a critical stressor specific to Sundaland/Southeast Asia (and to a lesser extent, other areas with peat swamp forests).'
forests_rainforest_sundaland_stressors["Peatland Degradation"]["Influenced By"] = ['Infrastructure Development (drainage canals).', 'Deforestation (clearing of peat swamp forests).', 'Agricultural Expansion (primarily palm oil and pulpwood plantations).', 'Climate Change (changes in precipitation and temperature can exacerbate drying).', '**Influences (Stressors):**', 'Wildfires (drained peat is highly flammable).', 'Climate Change (through carbon emissions).', 'Flooding (due to subsidence).', '**Logic Description:** Peatlands are waterlogged ecosystems with thick layers of partially decayed organic matter. Drainage for agriculture (especially palm oil) and logging causes the peat to decompose, releasing massive amounts of carbon dioxide. Drained peat is also extremely vulnerable to fire. This is a critical stressor specific to Sundaland/Southeast Asia (and to a lesser extent, other areas with peat swamp forests).']
forests_rainforest_sundaland_stressors["Peatland Degradation"]["Influences"] = ['Wildfires (drained peat is highly flammable).', 'Climate Change (through carbon emissions).', 'Flooding (due to subsidence).', '**Logic Description:** Peatlands are waterlogged ecosystems with thick layers of partially decayed organic matter. Drainage for agriculture (especially palm oil) and logging causes the peat to decompose, releasing massive amounts of carbon dioxide. Drained peat is also extremely vulnerable to fire. This is a critical stressor specific to Sundaland/Southeast Asia (and to a lesser extent, other areas with peat swamp forests).']
forests_rainforest_sundaland_stressors["Peatland Degradation"]["Logic Description"] = '---'

