from stressor_templates import *
import copy

forests_rainforest_amazon_stressors = {
    "Infrastructure Development": copy.deepcopy(infrastructure_development_template),
    "Deforestation": copy.deepcopy(deforestation_template),
    "Temperature Increase": copy.deepcopy(climate_change_template),
    "Changes in Precipitation": copy.deepcopy(climate_change_template),
    "Wildfires": copy.deepcopy(fire_regime_template),
}

# --- Infrastructure Development ---
forests_rainforest_amazon_stressors["Infrastructure Development"]["Metric"] = 'Length of new roads constructed per year (km/year) within the Amazon region, and/or area directly affected by other infrastructure projects (dams, pipelines, mining operations) (ha/year).'
forests_rainforest_amazon_stressors["Infrastructure Development"]["Data Sources"] = ['Projections of infrastructure development plans from governmental and industry sources.', 'Economic development scenarios and models that predict infrastructure needs.', 'Remote sensing data (satellite imagery) to track historical trends in infrastructure expansion.', '**Impact on Area:** Direct loss of rainforest area due to clearing for roads, dams, and other infrastructure. Increased fragmentation of remaining forest.', '**Impact on Biodiversity:**', 'Habitat loss and fragmentation, leading to reduced population sizes and increased risk of local extinctions.', 'Disruption of ecological corridors, limiting species movement and gene flow.', 'Increased human access to previously remote areas, leading to increased hunting, poaching, and illegal logging.', 'Alteration of hydrological regimes due to dams, affecting aquatic and terrestrial ecosystems.', '**Influenced By (Stressors):**', 'Economic Growth: Higher economic growth rates often lead to increased demand for infrastructure.', 'Population Growth: Increased population in the region can drive demand for new infrastructure.', 'Government Policies: Government policies and investment decisions can significantly influence the rate and type of infrastructure development.', 'Global Commodity Prices: High prices for commodities like soy, beef, timber, and minerals can incentivize expansion of infrastructure to facilitate extraction and export.', 'Technological advancements: improvements in construction materials, building techniques', '**Influences (Stressors):**', 'Deforestation: New roads provide access for logging and agricultural expansion, accelerating deforestation.', 'Wildfires: Roads can act as firebreaks, but they also increase the risk of human-caused fires.', 'Pollution (potentially, if we include industrial infrastructure): Mining operations, for example, can release pollutants into the environment.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Infrastructure Development"]["Impact on Area"] = 'Direct loss of rainforest area due to clearing for roads, dams, and other infrastructure. Increased fragmentation of remaining forest.'
forests_rainforest_amazon_stressors["Infrastructure Development"]["Impact on Biodiversity"] = 'Habitat loss and fragmentation, leading to reduced population sizes and increased risk of local extinctions.\nDisruption of ecological corridors, limiting species movement and gene flow.\nIncreased human access to previously remote areas, leading to increased hunting, poaching, and illegal logging.\nAlteration of hydrological regimes due to dams, affecting aquatic and terrestrial ecosystems.\n**Influenced By (Stressors):**\nEconomic Growth: Higher economic growth rates often lead to increased demand for infrastructure.\nPopulation Growth: Increased population in the region can drive demand for new infrastructure.\nGovernment Policies: Government policies and investment decisions can significantly influence the rate and type of infrastructure development.\nGlobal Commodity Prices: High prices for commodities like soy, beef, timber, and minerals can incentivize expansion of infrastructure to facilitate extraction and export.\nTechnological advancements: improvements in construction materials, building techniques\n**Influences (Stressors):**\nDeforestation: New roads provide access for logging and agricultural expansion, accelerating deforestation.\nWildfires: Roads can act as firebreaks, but they also increase the risk of human-caused fires.\nPollution (potentially, if we include industrial infrastructure): Mining operations, for example, can release pollutants into the environment.\n**Logic Description:**'
forests_rainforest_amazon_stressors["Infrastructure Development"]["Influenced By"] = ['Economic Growth: Higher economic growth rates often lead to increased demand for infrastructure.', 'Population Growth: Increased population in the region can drive demand for new infrastructure.', 'Government Policies: Government policies and investment decisions can significantly influence the rate and type of infrastructure development.', 'Global Commodity Prices: High prices for commodities like soy, beef, timber, and minerals can incentivize expansion of infrastructure to facilitate extraction and export.', 'Technological advancements: improvements in construction materials, building techniques', '**Influences (Stressors):**', 'Deforestation: New roads provide access for logging and agricultural expansion, accelerating deforestation.', 'Wildfires: Roads can act as firebreaks, but they also increase the risk of human-caused fires.', 'Pollution (potentially, if we include industrial infrastructure): Mining operations, for example, can release pollutants into the environment.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Infrastructure Development"]["Influences"] = ['Deforestation: New roads provide access for logging and agricultural expansion, accelerating deforestation.', 'Wildfires: Roads can act as firebreaks, but they also increase the risk of human-caused fires.', 'Pollution (potentially, if we include industrial infrastructure): Mining operations, for example, can release pollutants into the environment.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Infrastructure Development"]["Logic Description"] = 'The construction of new infrastructure (primarily roads, but also dams, pipelines, and mining operations) results in a direct loss of rainforest area proportional to the length of roads built or the area affected by other projects. This loss of area reduces the total available habitat for rainforest species. Furthermore, infrastructure fragments the remaining forest, creating smaller, isolated patches.  This fragmentation reduces the effective habitat size for many species, disrupts ecological processes (like seed dispersal and animal movement), and increases edge effects (making the forest more vulnerable to external influences). Increased human access via roads leads to secondary impacts, such as increased hunting, poaching, and illegal logging, further reducing biodiversity. Dams significantly alter river flows, impacting both upstream and downstream ecosystems.\n\n---'

# --- Deforestation ---
forests_rainforest_amazon_stressors["Deforestation"]["Metric"] = 'Area of forest cleared per year (hectares/year or km²/year).'
forests_rainforest_amazon_stressors["Deforestation"]["Data Sources"] = ["Remote sensing data (satellite imagery) from sources like Brazil's National Institute for Space Research (INPE) (PRODES and DETER projects).", 'Land-use change models.', 'Reports from environmental NGOs and research institutions.', '**Impact on Area:** Direct reduction of rainforest area.', '**Impact on Biodiversity:**', 'Habitat loss and fragmentation, leading to population decline and increased extinction risk.', 'Loss of carbon storage, contributing to climate change.', 'Disruption of ecological processes (e.g., seed dispersal, pollination).', 'Increased edge effects.', '**Influenced By (Stressors):**', 'Infrastructure Development: Roads provide access for logging and agriculture.', 'Economic Growth: Demand for agricultural land and timber.', 'Global Commodity Prices: High prices for soy, beef, and timber incentivize expansion.', 'Population Growth: Increased demand for land and resources.', 'Government Policies: Weak environmental regulations and enforcement.', '**Influences (Stressors):**', 'Wildfires: Deforested areas are more susceptible to fire.', 'Changes in Precipitation (potentially): Large-scale deforestation can alter regional rainfall patterns.', 'Temperature increase: Loss of forest area reduces evapotranspiration, increasing the local temperature.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Deforestation"]["Impact on Area"] = 'Direct reduction of rainforest area.'
forests_rainforest_amazon_stressors["Deforestation"]["Impact on Biodiversity"] = 'Habitat loss and fragmentation, leading to population decline and increased extinction risk.\nLoss of carbon storage, contributing to climate change.\nDisruption of ecological processes (e.g., seed dispersal, pollination).\nIncreased edge effects.\n**Influenced By (Stressors):**\nInfrastructure Development: Roads provide access for logging and agriculture.\nEconomic Growth: Demand for agricultural land and timber.\nGlobal Commodity Prices: High prices for soy, beef, and timber incentivize expansion.\nPopulation Growth: Increased demand for land and resources.\nGovernment Policies: Weak environmental regulations and enforcement.\n**Influences (Stressors):**\nWildfires: Deforested areas are more susceptible to fire.\nChanges in Precipitation (potentially): Large-scale deforestation can alter regional rainfall patterns.\nTemperature increase: Loss of forest area reduces evapotranspiration, increasing the local temperature.\n**Logic Description:**'
forests_rainforest_amazon_stressors["Deforestation"]["Influenced By"] = ['Infrastructure Development: Roads provide access for logging and agriculture.', 'Economic Growth: Demand for agricultural land and timber.', 'Global Commodity Prices: High prices for soy, beef, and timber incentivize expansion.', 'Population Growth: Increased demand for land and resources.', 'Government Policies: Weak environmental regulations and enforcement.', '**Influences (Stressors):**', 'Wildfires: Deforested areas are more susceptible to fire.', 'Changes in Precipitation (potentially): Large-scale deforestation can alter regional rainfall patterns.', 'Temperature increase: Loss of forest area reduces evapotranspiration, increasing the local temperature.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Deforestation"]["Influences"] = ['Wildfires: Deforested areas are more susceptible to fire.', 'Changes in Precipitation (potentially): Large-scale deforestation can alter regional rainfall patterns.', 'Temperature increase: Loss of forest area reduces evapotranspiration, increasing the local temperature.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Deforestation"]["Logic Description"] = 'Deforestation is the direct removal of forest cover, primarily for agriculture (cattle ranching, soy farming), logging, and mining. The metric directly measures the area lost. This loss of area directly reduces habitat for species and fragments the remaining forest, leading to biodiversity loss.  The drivers of deforestation are interconnected, with economic factors and infrastructure development playing significant roles.  Deforestation contributes to other stressors, like wildfires and potentially regional climate change.\n\n---'

# --- Temperature Increase ---
forests_rainforest_amazon_stressors["Temperature Increase"]["Metric"] = 'Average annual temperature increase (°C) above a pre-industrial baseline.'
forests_rainforest_amazon_stressors["Temperature Increase"]["Data Sources"] = ['Global climate models (GCMs) projections (e.g., CMIP6).', 'Regional climate models downscaled for the Amazon basin.', 'Historical temperature records from weather stations in the region.', "**Impact on Area:** Indirect.  Temperature increase itself doesn't directly reduce area, but it exacerbates other stressors.", '**Impact on Biodiversity:**', 'Shifts in species distributions, as species move to track suitable climates.', 'Increased physiological stress on species, particularly those with narrow thermal tolerances.', 'Increased risk of exceeding thermal limits, leading to mortality.', 'Changes in phenology (timing of biological events).', 'Increased susceptibility to diseases and pests.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions: The primary driver of global temperature increase.', 'Deforestation: Reduced carbon sequestration and altered evapotranspiration.', '**Influences (Stressors):**', 'Wildfires: Higher temperatures increase fire risk and intensity.', 'Changes in Precipitation: Temperature changes can interact with precipitation patterns.', 'Species die-off events, leading to ecosystem changes.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Temperature Increase"]["Impact on Area"] = "Indirect.  Temperature increase itself doesn't directly reduce area, but it exacerbates other stressors."
forests_rainforest_amazon_stressors["Temperature Increase"]["Impact on Biodiversity"] = 'Shifts in species distributions, as species move to track suitable climates.\nIncreased physiological stress on species, particularly those with narrow thermal tolerances.\nIncreased risk of exceeding thermal limits, leading to mortality.\nChanges in phenology (timing of biological events).\nIncreased susceptibility to diseases and pests.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions: The primary driver of global temperature increase.\nDeforestation: Reduced carbon sequestration and altered evapotranspiration.\n**Influences (Stressors):**\nWildfires: Higher temperatures increase fire risk and intensity.\nChanges in Precipitation: Temperature changes can interact with precipitation patterns.\nSpecies die-off events, leading to ecosystem changes.\n**Logic Description:**'
forests_rainforest_amazon_stressors["Temperature Increase"]["Influenced By"] = ['Global Greenhouse Gas Emissions: The primary driver of global temperature increase.', 'Deforestation: Reduced carbon sequestration and altered evapotranspiration.', '**Influences (Stressors):**', 'Wildfires: Higher temperatures increase fire risk and intensity.', 'Changes in Precipitation: Temperature changes can interact with precipitation patterns.', 'Species die-off events, leading to ecosystem changes.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Temperature Increase"]["Influences"] = ['Wildfires: Higher temperatures increase fire risk and intensity.', 'Changes in Precipitation: Temperature changes can interact with precipitation patterns.', 'Species die-off events, leading to ecosystem changes.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Temperature Increase"]["Logic Description"] = 'Temperature increase is primarily driven by global greenhouse gas emissions, but deforestation within the Amazon also contributes locally.  While not directly reducing area, increased temperature acts as a stress multiplier. It pushes species beyond their thermal tolerance limits, alters ecological processes, and increases the risk and severity of other stressors like wildfires.\n\n---'

# --- Changes in Precipitation ---
forests_rainforest_amazon_stressors["Changes in Precipitation"]["Metric"] = 'Change in annual precipitation (mm/year) and changes in the length and severity of the dry season (number of months with rainfall below a threshold).'
forests_rainforest_amazon_stressors["Changes in Precipitation"]["Data Sources"] = ['Global climate models (GCMs) projections.', 'Regional climate models.', 'Historical rainfall records from weather stations.', '**Impact on Area:** Indirect, but can lead to changes in vegetation types over long time scales.', '**Impact on Biodiversity:**', 'Changes in species distributions as rainfall patterns shift.', 'Increased drought stress on plants, leading to mortality.', 'Altered river flow regimes, affecting aquatic ecosystems.', 'Changes in the frequency and intensity of flooding events.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions: Climate change alters atmospheric circulation patterns.', 'Deforestation: Large-scale deforestation can reduce regional rainfall.', "Temperature Increase: Warmer air can hold more moisture, but this doesn't guarantee increased rainfall; it can lead to more extreme events (droughts and floods).", '**Influences (Stressors):**', 'Wildfires: Longer and more severe dry seasons increase fire risk.', 'Species composition changes: favouring drought tolerant species.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Changes in Precipitation"]["Impact on Area"] = 'Indirect, but can lead to changes in vegetation types over long time scales.'
forests_rainforest_amazon_stressors["Changes in Precipitation"]["Impact on Biodiversity"] = "Changes in species distributions as rainfall patterns shift.\nIncreased drought stress on plants, leading to mortality.\nAltered river flow regimes, affecting aquatic ecosystems.\nChanges in the frequency and intensity of flooding events.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions: Climate change alters atmospheric circulation patterns.\nDeforestation: Large-scale deforestation can reduce regional rainfall.\nTemperature Increase: Warmer air can hold more moisture, but this doesn't guarantee increased rainfall; it can lead to more extreme events (droughts and floods).\n**Influences (Stressors):**\nWildfires: Longer and more severe dry seasons increase fire risk.\nSpecies composition changes: favouring drought tolerant species.\n**Logic Description:**"
forests_rainforest_amazon_stressors["Changes in Precipitation"]["Influenced By"] = ['Global Greenhouse Gas Emissions: Climate change alters atmospheric circulation patterns.', 'Deforestation: Large-scale deforestation can reduce regional rainfall.', "Temperature Increase: Warmer air can hold more moisture, but this doesn't guarantee increased rainfall; it can lead to more extreme events (droughts and floods).", '**Influences (Stressors):**', 'Wildfires: Longer and more severe dry seasons increase fire risk.', 'Species composition changes: favouring drought tolerant species.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Changes in Precipitation"]["Influences"] = ['Wildfires: Longer and more severe dry seasons increase fire risk.', 'Species composition changes: favouring drought tolerant species.', '**Logic Description:**']
forests_rainforest_amazon_stressors["Changes in Precipitation"]["Logic Description"] = 'Changes in precipitation are driven by global climate change and, regionally, by deforestation. The Amazon is particularly sensitive to changes in the length and intensity of the dry season.  Decreased rainfall or longer dry seasons lead to increased drought stress on plants, favoring drought-tolerant species and potentially leading to shifts in vegetation types over time.  Altered rainfall patterns also affect river systems and the frequency of flooding events.\n\n---'

# --- Wildfires ---
forests_rainforest_amazon_stressors["Wildfires"]["Metric"] = 'Number of wildfires per year and total area burned (hectares/year).'
forests_rainforest_amazon_stressors["Wildfires"]["Data Sources"] = ['Remote sensing data (satellite imagery) from fire detection systems (e.g., MODIS, VIIRS).', 'Reports from fire departments and environmental agencies.', '**Impact on Area:** Direct loss of forest area (although some fires may occur in already deforested areas).', '**Impact on Biodiversity:**', 'Direct mortality of plants and animals.', 'Habitat loss and fragmentation.', 'Air pollution, affecting both human and animal health.', 'Release of carbon dioxide, contributing to climate change.', '**Influenced By (Stressors):**', 'Deforestation: Deforested areas are more susceptible to fire.', 'Temperature Increase: Higher temperatures increase fire risk.', 'Changes in Precipitation: Longer dry seasons increase fire risk.', 'Infrastructure development: increases ignition sources and access', 'Human Activities: Accidental or intentional ignition of fires.', '**Influences (Stressors):**', 'Deforestation: Fires can contribute to further deforestation by creating edges that are more susceptible to future fires.', 'Temperature Increase: increased temperatures due to release of greenhouse gases', '**Logic Description:**']
forests_rainforest_amazon_stressors["Wildfires"]["Impact on Area"] = 'Direct loss of forest area (although some fires may occur in already deforested areas).'
forests_rainforest_amazon_stressors["Wildfires"]["Impact on Biodiversity"] = 'Direct mortality of plants and animals.\nHabitat loss and fragmentation.\nAir pollution, affecting both human and animal health.\nRelease of carbon dioxide, contributing to climate change.\n**Influenced By (Stressors):**\nDeforestation: Deforested areas are more susceptible to fire.\nTemperature Increase: Higher temperatures increase fire risk.\nChanges in Precipitation: Longer dry seasons increase fire risk.\nInfrastructure development: increases ignition sources and access\nHuman Activities: Accidental or intentional ignition of fires.\n**Influences (Stressors):**\nDeforestation: Fires can contribute to further deforestation by creating edges that are more susceptible to future fires.\nTemperature Increase: increased temperatures due to release of greenhouse gases\n**Logic Description:**'
forests_rainforest_amazon_stressors["Wildfires"]["Influenced By"] = ['Deforestation: Deforested areas are more susceptible to fire.', 'Temperature Increase: Higher temperatures increase fire risk.', 'Changes in Precipitation: Longer dry seasons increase fire risk.', 'Infrastructure development: increases ignition sources and access', 'Human Activities: Accidental or intentional ignition of fires.', '**Influences (Stressors):**', 'Deforestation: Fires can contribute to further deforestation by creating edges that are more susceptible to future fires.', 'Temperature Increase: increased temperatures due to release of greenhouse gases', '**Logic Description:**']
forests_rainforest_amazon_stressors["Wildfires"]["Influences"] = ['Deforestation: Fires can contribute to further deforestation by creating edges that are more susceptible to future fires.', 'Temperature Increase: increased temperatures due to release of greenhouse gases', '**Logic Description:**']
forests_rainforest_amazon_stressors["Wildfires"]["Logic Description"] = 'Wildfires are a major threat to the Amazon, and their frequency and intensity are increasing due to a combination of factors. Deforestation creates drier, more flammable edges, while climate change (increased temperature and drier conditions) provides the ideal conditions for fires to spread. Human activities are the primary source of ignition. Fires directly burn forest area, killing plants and animals, and release large amounts of carbon dioxide.\n\n---'

