from stressor_templates import *
import copy

forests_temperate_forests_pacific_northwest_stressors = {
    "Infrastructure Development": copy.deepcopy(infrastructure_development_template),
    "Deforestation": copy.deepcopy(deforestation_template),
    "Temperature Increase": copy.deepcopy(climate_change_template),
    "Changes in Precipitation": copy.deepcopy(climate_change_template),
    "Wildfires": copy.deepcopy(fire_regime_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
}

# --- Infrastructure Development ---
forests_temperate_forests_pacific_northwest_stressors["Infrastructure Development"]["Metric"] = 'Road density (km/km²); area affected by logging, dams (ha/year).'
forests_temperate_forests_pacific_northwest_stressors["Infrastructure Development"]["Data Sources"] = ['US Forest Service and Canadian government data.', 'Remote sensing.', '**Impact on Area:** Habitat fragmentation.', '**Impact on Biodiversity:**', 'Habitat loss and fragmentation.', 'Disruption of corridors.', 'Impacts on aquatic ecosystems from dams.', '**Influenced By (Stressors):**', 'Economic Growth: Resource extraction (timber).', 'Population Growth.', 'Government Policies.', '**Influences (Stressors):**', 'Deforestation (primarily through logging).', 'Water quality (dams)', '**Logic Description:** Infrastructure, primarily related to logging and dams, fragments habitat and impacts aquatic ecosystems.']
forests_temperate_forests_pacific_northwest_stressors["Infrastructure Development"]["Impact on Area"] = 'Habitat fragmentation.'
forests_temperate_forests_pacific_northwest_stressors["Infrastructure Development"]["Impact on Biodiversity"] = 'Habitat loss and fragmentation.\nDisruption of corridors.\nImpacts on aquatic ecosystems from dams.\n**Influenced By (Stressors):**\nEconomic Growth: Resource extraction (timber).\nPopulation Growth.\nGovernment Policies.\n**Influences (Stressors):**\nDeforestation (primarily through logging).\nWater quality (dams)\n**Logic Description:** Infrastructure, primarily related to logging and dams, fragments habitat and impacts aquatic ecosystems.'
forests_temperate_forests_pacific_northwest_stressors["Infrastructure Development"]["Influenced By"] = ['Economic Growth: Resource extraction (timber).', 'Population Growth.', 'Government Policies.', '**Influences (Stressors):**', 'Deforestation (primarily through logging).', 'Water quality (dams)', '**Logic Description:** Infrastructure, primarily related to logging and dams, fragments habitat and impacts aquatic ecosystems.']
forests_temperate_forests_pacific_northwest_stressors["Infrastructure Development"]["Influences"] = ['Deforestation (primarily through logging).', 'Water quality (dams)', '**Logic Description:** Infrastructure, primarily related to logging and dams, fragments habitat and impacts aquatic ecosystems.']
forests_temperate_forests_pacific_northwest_stressors["Infrastructure Development"]["Logic Description"] = '---'

# --- Deforestation ---
forests_temperate_forests_pacific_northwest_stressors["Deforestation"]["Metric"] = 'Area of forest cleared per year (ha/year) (often related to logging, but can also include conversion to other land uses).'
forests_temperate_forests_pacific_northwest_stressors["Deforestation"]["Data Sources"] = ['US Forest Service and Canadian government data.', 'Remote sensing.', '**Impact on Area:** Loss of old-growth forest; changes in forest age structure.', '**Impact on Biodiversity:**', 'Habitat loss (especially for old-growth dependent species).', 'Changes in species composition.', '**Influenced By (Stressors):**', 'Infrastructure Development (roads).', 'Economic Growth: Demand for timber.', 'Government Policies: Timber harvest regulations.', '**Influences (Stressors):**', '*  Carbon Sequestration', '**Logic Description:** Logging, particularly of old-growth forests, is a major driver of deforestation, impacting biodiversity and carbon storage.']
forests_temperate_forests_pacific_northwest_stressors["Deforestation"]["Impact on Area"] = 'Loss of old-growth forest; changes in forest age structure.'
forests_temperate_forests_pacific_northwest_stressors["Deforestation"]["Impact on Biodiversity"] = 'Habitat loss (especially for old-growth dependent species).\nChanges in species composition.\n**Influenced By (Stressors):**\nInfrastructure Development (roads).\nEconomic Growth: Demand for timber.\nGovernment Policies: Timber harvest regulations.\n**Influences (Stressors):**\n*  Carbon Sequestration\n**Logic Description:** Logging, particularly of old-growth forests, is a major driver of deforestation, impacting biodiversity and carbon storage.'
forests_temperate_forests_pacific_northwest_stressors["Deforestation"]["Influenced By"] = ['Infrastructure Development (roads).', 'Economic Growth: Demand for timber.', 'Government Policies: Timber harvest regulations.', '**Influences (Stressors):**', '*  Carbon Sequestration', '**Logic Description:** Logging, particularly of old-growth forests, is a major driver of deforestation, impacting biodiversity and carbon storage.']
forests_temperate_forests_pacific_northwest_stressors["Deforestation"]["Influences"] = ['*  Carbon Sequestration', '**Logic Description:** Logging, particularly of old-growth forests, is a major driver of deforestation, impacting biodiversity and carbon storage.']
forests_temperate_forests_pacific_northwest_stressors["Deforestation"]["Logic Description"] = '---'

# --- Temperature Increase ---
forests_temperate_forests_pacific_northwest_stressors["Temperature Increase"]["Metric"] = 'Average annual temperature increase (°C).'
forests_temperate_forests_pacific_northwest_stressors["Temperature Increase"]["Data Sources"] = ['Climate models.', 'Historical records.', '**Impact on Area:** Indirect.', '**Impact on Biodiversity:**', 'Species shifts.', 'Increased stress.', 'Changes in phenology.', 'Increased pest/disease outbreaks (e.g., mountain pine beetle).', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Wildfires.', 'Changes in Precipitation.', 'Pest outbreaks', '**Logic Description:** Climate change impacts, including increased risk of wildfires and insect outbreaks.']
forests_temperate_forests_pacific_northwest_stressors["Temperature Increase"]["Impact on Area"] = 'Indirect.'
forests_temperate_forests_pacific_northwest_stressors["Temperature Increase"]["Impact on Biodiversity"] = 'Species shifts.\nIncreased stress.\nChanges in phenology.\nIncreased pest/disease outbreaks (e.g., mountain pine beetle).\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nWildfires.\nChanges in Precipitation.\nPest outbreaks\n**Logic Description:** Climate change impacts, including increased risk of wildfires and insect outbreaks.'
forests_temperate_forests_pacific_northwest_stressors["Temperature Increase"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Wildfires.', 'Changes in Precipitation.', 'Pest outbreaks', '**Logic Description:** Climate change impacts, including increased risk of wildfires and insect outbreaks.']
forests_temperate_forests_pacific_northwest_stressors["Temperature Increase"]["Influences"] = ['Wildfires.', 'Changes in Precipitation.', 'Pest outbreaks', '**Logic Description:** Climate change impacts, including increased risk of wildfires and insect outbreaks.']
forests_temperate_forests_pacific_northwest_stressors["Temperature Increase"]["Logic Description"] = '---'

# --- Changes in Precipitation ---
forests_temperate_forests_pacific_northwest_stressors["Changes in Precipitation"]["Metric"] = 'Change in annual precipitation (mm/year); changes in snowpack (snow water equivalent - SWE).'
forests_temperate_forests_pacific_northwest_stressors["Changes in Precipitation"]["Data Sources"] = ['Climate models.', 'Historical records.', '**Impact on Area:** Indirect; changes in water availability.', '**Impact on Biodiversity:**', 'Changes in species composition.', 'Altered streamflow.', 'Increased drought stress (in some areas).', '* Reduced snowpack impacts summer water availability', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Wildfires.', '* Water availability', '**Logic Description:** Changes in precipitation patterns, including reduced snowpack, impact water availability and species composition.']
forests_temperate_forests_pacific_northwest_stressors["Changes in Precipitation"]["Impact on Area"] = 'Indirect; changes in water availability.'
forests_temperate_forests_pacific_northwest_stressors["Changes in Precipitation"]["Impact on Biodiversity"] = 'Changes in species composition.\nAltered streamflow.\nIncreased drought stress (in some areas).\n* Reduced snowpack impacts summer water availability\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nWildfires.\n* Water availability\n**Logic Description:** Changes in precipitation patterns, including reduced snowpack, impact water availability and species composition.'
forests_temperate_forests_pacific_northwest_stressors["Changes in Precipitation"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Wildfires.', '* Water availability', '**Logic Description:** Changes in precipitation patterns, including reduced snowpack, impact water availability and species composition.']
forests_temperate_forests_pacific_northwest_stressors["Changes in Precipitation"]["Influences"] = ['Wildfires.', '* Water availability', '**Logic Description:** Changes in precipitation patterns, including reduced snowpack, impact water availability and species composition.']
forests_temperate_forests_pacific_northwest_stressors["Changes in Precipitation"]["Logic Description"] = '---'

# --- Wildfires ---
forests_temperate_forests_pacific_northwest_stressors["Wildfires"]["Metric"] = 'Number of fires; area burned (ha/year).'
forests_temperate_forests_pacific_northwest_stressors["Wildfires"]["Data Sources"] = ['US Forest Service and Canadian government data.', 'Remote sensing.', '**Impact on Area:** Direct loss of forest area; changes in forest structure.', '**Impact on Biodiversity:**', 'Mortality.', 'Habitat loss.', 'Changes in species composition.', '**Influenced By (Stressors):**', 'Temperature Increase.', 'Changes in Precipitation (reduced snowpack, longer dry seasons).', 'Forest Management Practices (fire suppression).', 'Insect outbreaks (creating dead trees).', '**Influences (Stressors):**', 'Future fire risk', '* air quality', '**Logic Description:** Wildfires, increasing in frequency and intensity due to climate change and past fire suppression, are a major threat.']
forests_temperate_forests_pacific_northwest_stressors["Wildfires"]["Impact on Area"] = 'Direct loss of forest area; changes in forest structure.'
forests_temperate_forests_pacific_northwest_stressors["Wildfires"]["Impact on Biodiversity"] = 'Mortality.\nHabitat loss.\nChanges in species composition.\n**Influenced By (Stressors):**\nTemperature Increase.\nChanges in Precipitation (reduced snowpack, longer dry seasons).\nForest Management Practices (fire suppression).\nInsect outbreaks (creating dead trees).\n**Influences (Stressors):**\nFuture fire risk\n* air quality\n**Logic Description:** Wildfires, increasing in frequency and intensity due to climate change and past fire suppression, are a major threat.'
forests_temperate_forests_pacific_northwest_stressors["Wildfires"]["Influenced By"] = ['Temperature Increase.', 'Changes in Precipitation (reduced snowpack, longer dry seasons).', 'Forest Management Practices (fire suppression).', 'Insect outbreaks (creating dead trees).', '**Influences (Stressors):**', 'Future fire risk', '* air quality', '**Logic Description:** Wildfires, increasing in frequency and intensity due to climate change and past fire suppression, are a major threat.']
forests_temperate_forests_pacific_northwest_stressors["Wildfires"]["Influences"] = ['Future fire risk', '* air quality', '**Logic Description:** Wildfires, increasing in frequency and intensity due to climate change and past fire suppression, are a major threat.']
forests_temperate_forests_pacific_northwest_stressors["Wildfires"]["Logic Description"] = '---'

# --- Invasive Species ---
forests_temperate_forests_pacific_northwest_stressors["Invasive Species"]["Metric"] = 'Abundance/distribution of key invasives (e.g., Scotch broom, Himalayan blackberry).'
forests_temperate_forests_pacific_northwest_stressors["Invasive Species"]["Data Sources"] = ['Forest health monitoring programs.', 'Research studies.', '**Impact on Area:** Changes in forest composition and structure.', '**Impact on Biodiversity:**', 'Competition with native plants.', 'Altered ecosystem processes.', '**Influenced By (Stressors):**', '* Disturbance (e.g., logging, roads).', '* Climate Change', '* Global trade', '**Influences (Stressors):**', '* Native plant communities', '**Logic Description:** Invasive plants can outcompete native species, altering forest structure and function.']
forests_temperate_forests_pacific_northwest_stressors["Invasive Species"]["Impact on Area"] = 'Changes in forest composition and structure.'
forests_temperate_forests_pacific_northwest_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Competition with native plants.\nAltered ecosystem processes.\n**Influenced By (Stressors):**\n* Disturbance (e.g., logging, roads).\n* Climate Change\n* Global trade\n**Influences (Stressors):**\n* Native plant communities\n**Logic Description:** Invasive plants can outcompete native species, altering forest structure and function.'
forests_temperate_forests_pacific_northwest_stressors["Invasive Species"]["Influenced By"] = ['* Disturbance (e.g., logging, roads).', '* Climate Change', '* Global trade', '**Influences (Stressors):**', '* Native plant communities', '**Logic Description:** Invasive plants can outcompete native species, altering forest structure and function.']
forests_temperate_forests_pacific_northwest_stressors["Invasive Species"]["Influences"] = ['* Native plant communities', '**Logic Description:** Invasive plants can outcompete native species, altering forest structure and function.']
forests_temperate_forests_pacific_northwest_stressors["Invasive Species"]["Logic Description"] = '---'

