from stressor_templates import *
import copy

forests_temperate_forests_european_stressors = {
    "Infrastructure Development": copy.deepcopy(infrastructure_development_template),
    "Deforestation": copy.deepcopy(deforestation_template),
    "Temperature Increase": copy.deepcopy(climate_change_template),
    "Changes in Precipitation": copy.deepcopy(climate_change_template),
    "Wildfires": copy.deepcopy(fire_regime_template),
    "Air Pollution": copy.deepcopy(pollution_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
}

# --- Infrastructure Development ---
forests_temperate_forests_european_stressors["Infrastructure Development"]["Metric"] = 'Road density (km/km²); area affected by development (ha/year).'
forests_temperate_forests_european_stressors["Infrastructure Development"]["Data Sources"] = ['European Environment Agency (EEA) data.', 'National government statistics.', 'Remote sensing.', '**Impact on Area:** Habitat fragmentation (historically high levels of fragmentation).', '**Impact on Biodiversity:**', 'Habitat loss and fragmentation.', 'Disruption of corridors.', 'Increased edge effects.', '**Influenced By (Stressors):**', 'Economic Growth.', 'Population Growth (and density).', 'Transportation planning.', '**Influences (Stressors):**', 'Deforestation (localized).', '* Increased Access', '**Logic Description:** Continued development further fragments an already highly fragmented landscape.']
forests_temperate_forests_european_stressors["Infrastructure Development"]["Impact on Area"] = 'Habitat fragmentation (historically high levels of fragmentation).'
forests_temperate_forests_european_stressors["Infrastructure Development"]["Impact on Biodiversity"] = 'Habitat loss and fragmentation.\nDisruption of corridors.\nIncreased edge effects.\n**Influenced By (Stressors):**\nEconomic Growth.\nPopulation Growth (and density).\nTransportation planning.\n**Influences (Stressors):**\nDeforestation (localized).\n* Increased Access\n**Logic Description:** Continued development further fragments an already highly fragmented landscape.'
forests_temperate_forests_european_stressors["Infrastructure Development"]["Influenced By"] = ['Economic Growth.', 'Population Growth (and density).', 'Transportation planning.', '**Influences (Stressors):**', 'Deforestation (localized).', '* Increased Access', '**Logic Description:** Continued development further fragments an already highly fragmented landscape.']
forests_temperate_forests_european_stressors["Infrastructure Development"]["Influences"] = ['Deforestation (localized).', '* Increased Access', '**Logic Description:** Continued development further fragments an already highly fragmented landscape.']
forests_temperate_forests_european_stressors["Infrastructure Development"]["Logic Description"] = '---'
forests_temperate_forests_european_stressors["Infrastructure Development"]["Impact Function"] = "impact_infrastructure_development_forests_temperate_forests_european"

# --- Deforestation ---
forests_temperate_forests_european_stressors["Deforestation"]["Metric"] = 'Area of forest cleared per year (ha/year) (often localized; overall forest cover may be increasing in some areas due to afforestation, but *loss* of *old-growth* or *natural* forest is still a concern).'
forests_temperate_forests_european_stressors["Deforestation"]["Data Sources"] = ['EEA data.', 'National forest inventories.', 'Remote sensing.', '**Impact on Area:** Localized forest loss; changes in forest age structure.', '**Impact on Biodiversity:**', 'Habitat loss (especially for old-growth dependent species).', 'Changes in species composition.', '**Influenced By (Stressors):**', 'Infrastructure Development.', 'Urban Sprawl.', 'Agricultural Expansion (limited, but can occur).', 'Timber Harvesting (depending on management practices).', '**Influences (Stressors):**', '* Forest Age and Structure', '**Logic Description:** While overall forest cover may be stable or increasing in some areas, localized deforestation and loss of old-growth forest continue to be stressors.']
forests_temperate_forests_european_stressors["Deforestation"]["Impact on Area"] = 'Localized forest loss; changes in forest age structure.'
forests_temperate_forests_european_stressors["Deforestation"]["Impact on Biodiversity"] = 'Habitat loss (especially for old-growth dependent species).\nChanges in species composition.\n**Influenced By (Stressors):**\nInfrastructure Development.\nUrban Sprawl.\nAgricultural Expansion (limited, but can occur).\nTimber Harvesting (depending on management practices).\n**Influences (Stressors):**\n* Forest Age and Structure\n**Logic Description:** While overall forest cover may be stable or increasing in some areas, localized deforestation and loss of old-growth forest continue to be stressors.'
forests_temperate_forests_european_stressors["Deforestation"]["Influenced By"] = ['Infrastructure Development.', 'Urban Sprawl.', 'Agricultural Expansion (limited, but can occur).', 'Timber Harvesting (depending on management practices).', '**Influences (Stressors):**', '* Forest Age and Structure', '**Logic Description:** While overall forest cover may be stable or increasing in some areas, localized deforestation and loss of old-growth forest continue to be stressors.']
forests_temperate_forests_european_stressors["Deforestation"]["Influences"] = ['* Forest Age and Structure', '**Logic Description:** While overall forest cover may be stable or increasing in some areas, localized deforestation and loss of old-growth forest continue to be stressors.']
forests_temperate_forests_european_stressors["Deforestation"]["Logic Description"] = '---'
forests_temperate_forests_european_stressors["Deforestation"]["Impact Function"] = "impact_deforestation_forests_temperate_forests_european"

# --- Temperature Increase ---
forests_temperate_forests_european_stressors["Temperature Increase"]["Metric"] = 'Average annual temperature increase (°C).'
forests_temperate_forests_european_stressors["Temperature Increase"]["Data Sources"] = ['Climate models.', 'Historical records.', '**Impact on Area:** Indirect.', '**Impact on Biodiversity:**', 'Species shifts (northward and upslope).', 'Increased stress.', 'Changes in phenology.', 'Increased pest/disease outbreaks.', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Wildfires.', 'Changes in Precipitation.', '* Pest and disease outbreaks', '**Logic Description:** Climate change impacts, including increased risk of drought and insect outbreaks.']
forests_temperate_forests_european_stressors["Temperature Increase"]["Impact on Area"] = 'Indirect.'
forests_temperate_forests_european_stressors["Temperature Increase"]["Impact on Biodiversity"] = 'Species shifts (northward and upslope).\nIncreased stress.\nChanges in phenology.\nIncreased pest/disease outbreaks.\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\nWildfires.\nChanges in Precipitation.\n* Pest and disease outbreaks\n**Logic Description:** Climate change impacts, including increased risk of drought and insect outbreaks.'
forests_temperate_forests_european_stressors["Temperature Increase"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', 'Wildfires.', 'Changes in Precipitation.', '* Pest and disease outbreaks', '**Logic Description:** Climate change impacts, including increased risk of drought and insect outbreaks.']
forests_temperate_forests_european_stressors["Temperature Increase"]["Influences"] = ['Wildfires.', 'Changes in Precipitation.', '* Pest and disease outbreaks', '**Logic Description:** Climate change impacts, including increased risk of drought and insect outbreaks.']
forests_temperate_forests_european_stressors["Temperature Increase"]["Logic Description"] = '---'
forests_temperate_forests_european_stressors["Temperature Increase"]["Impact Function"] = "impact_temperature_increase_forests_temperate_forests_european"

# --- Changes in Precipitation ---
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Metric"] = 'Change in annual precipitation (mm/year); changes in seasonality (e.g., drier summers, wetter winters).'
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Data Sources"] = ['Climate models.', 'Historical records.', '**Impact on Area:** Indirect; changes in water availability.', '**Impact on Biodiversity:**', 'Changes in species composition.', 'Altered streamflow.', 'Increased drought stress (in some areas).', '**Influenced By (Stressors):**', 'Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', '* Wildfires (in drier regions)', '* Water availability', '**Logic Description:** Changes in precipitation patterns, including increased drought risk in some regions, impact water availability and species composition.']
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Impact on Area"] = 'Indirect; changes in water availability.'
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Impact on Biodiversity"] = 'Changes in species composition.\nAltered streamflow.\nIncreased drought stress (in some areas).\n**Influenced By (Stressors):**\nGlobal Greenhouse Gas Emissions.\n**Influences (Stressors):**\n* Wildfires (in drier regions)\n* Water availability\n**Logic Description:** Changes in precipitation patterns, including increased drought risk in some regions, impact water availability and species composition.'
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Influenced By"] = ['Global Greenhouse Gas Emissions.', '**Influences (Stressors):**', '* Wildfires (in drier regions)', '* Water availability', '**Logic Description:** Changes in precipitation patterns, including increased drought risk in some regions, impact water availability and species composition.']
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Influences"] = ['* Wildfires (in drier regions)', '* Water availability', '**Logic Description:** Changes in precipitation patterns, including increased drought risk in some regions, impact water availability and species composition.']
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Logic Description"] = '---'
forests_temperate_forests_european_stressors["Changes in Precipitation"]["Impact Function"] = "impact_changes_in_precipitation_forests_temperate_forests_european"

# --- Wildfires ---
forests_temperate_forests_european_stressors["Wildfires"]["Metric"] = 'Number of fires; area burned (ha/year) (more significant in southern Europe).'
forests_temperate_forests_european_stressors["Wildfires"]["Data Sources"] = ['EEA data.', 'National fire statistics.', 'Remote sensing.', '**Impact on Area:** Direct loss of forest area (especially in Mediterranean regions).', '**Impact on Biodiversity:**', 'Mortality.', 'Habitat loss.', 'Changes in species composition.', '**Influenced By (Stressors):**', 'Temperature Increase.', 'Changes in Precipitation (drier summers).', 'Land Abandonment (leading to fuel buildup).', 'Human Activities (negligence, arson).', '**Influences (Stressors):**', '* Air quality', '* Future Fire Risk', '**Logic Description:** Wildfires, particularly in southern Europe, are increasing due to climate change and land management practices.']
forests_temperate_forests_european_stressors["Wildfires"]["Impact on Area"] = 'Direct loss of forest area (especially in Mediterranean regions).'
forests_temperate_forests_european_stressors["Wildfires"]["Impact on Biodiversity"] = 'Mortality.\nHabitat loss.\nChanges in species composition.\n**Influenced By (Stressors):**\nTemperature Increase.\nChanges in Precipitation (drier summers).\nLand Abandonment (leading to fuel buildup).\nHuman Activities (negligence, arson).\n**Influences (Stressors):**\n* Air quality\n* Future Fire Risk\n**Logic Description:** Wildfires, particularly in southern Europe, are increasing due to climate change and land management practices.'
forests_temperate_forests_european_stressors["Wildfires"]["Influenced By"] = ['Temperature Increase.', 'Changes in Precipitation (drier summers).', 'Land Abandonment (leading to fuel buildup).', 'Human Activities (negligence, arson).', '**Influences (Stressors):**', '* Air quality', '* Future Fire Risk', '**Logic Description:** Wildfires, particularly in southern Europe, are increasing due to climate change and land management practices.']
forests_temperate_forests_european_stressors["Wildfires"]["Influences"] = ['* Air quality', '* Future Fire Risk', '**Logic Description:** Wildfires, particularly in southern Europe, are increasing due to climate change and land management practices.']
forests_temperate_forests_european_stressors["Wildfires"]["Logic Description"] = '---'
forests_temperate_forests_european_stressors["Wildfires"]["Impact Function"] = "impact_wildfires_forests_temperate_forests_european"

# --- Air Pollution ---
forests_temperate_forests_european_stressors["Air Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., ozone, nitrogen oxides, sulfur dioxide).'
forests_temperate_forests_european_stressors["Air Pollution"]["Data Sources"] = ['EEA air quality data.', 'National monitoring networks.', '**Impact on Area:** Reduced forest health and productivity.', '**Impact on Biodiversity:**', 'Damage to foliage.', 'Increased susceptibility to pests/diseases.', 'Acidification of soils and water.', '**Influenced By (Stressors):**', 'Industrial Activity.', 'Fossil Fuel Combustion.', 'Agricultural Practices.', '**Influences (Stressors):**', '* Water Quality', '* Forest health', '**Logic Description:** Air pollution, from various sources, continues to be a stressor, particularly in industrialized areas.']
forests_temperate_forests_european_stressors["Air Pollution"]["Impact on Area"] = 'Reduced forest health and productivity.'
forests_temperate_forests_european_stressors["Air Pollution"]["Impact on Biodiversity"] = 'Damage to foliage.\nIncreased susceptibility to pests/diseases.\nAcidification of soils and water.\n**Influenced By (Stressors):**\nIndustrial Activity.\nFossil Fuel Combustion.\nAgricultural Practices.\n**Influences (Stressors):**\n* Water Quality\n* Forest health\n**Logic Description:** Air pollution, from various sources, continues to be a stressor, particularly in industrialized areas.'
forests_temperate_forests_european_stressors["Air Pollution"]["Influenced By"] = ['Industrial Activity.', 'Fossil Fuel Combustion.', 'Agricultural Practices.', '**Influences (Stressors):**', '* Water Quality', '* Forest health', '**Logic Description:** Air pollution, from various sources, continues to be a stressor, particularly in industrialized areas.']
forests_temperate_forests_european_stressors["Air Pollution"]["Influences"] = ['* Water Quality', '* Forest health', '**Logic Description:** Air pollution, from various sources, continues to be a stressor, particularly in industrialized areas.']
forests_temperate_forests_european_stressors["Air Pollution"]["Logic Description"] = '---'
forests_temperate_forests_european_stressors["Air Pollution"]["Impact Function"] = "impact_air_pollution_forests_temperate_forests_european"

# --- Invasive Species ---
forests_temperate_forests_european_stressors["Invasive Species"]["Metric"] = 'Abundance/Distribution of key invasive species.'
forests_temperate_forests_european_stressors["Invasive Species"]["Data Sources"] = ['* Forest health monitoring programs.', '* Research Studies', '**Impact on Area**: Changes in forest composition.', '**Impact on Biodiversity:**', '* Competition', '* Altered processes', '**Influenced By (Stressors):**', '* Disturbance', '* Climate Change', '* Global Trade', '**Influences (Stressors):**', '* Forest Composition', '**Logic Description:** Invasive species impacts.']
forests_temperate_forests_european_stressors["Invasive Species"]["Impact on Biodiversity"] = '* Competition\n* Altered processes\n**Influenced By (Stressors):**\n* Disturbance\n* Climate Change\n* Global Trade\n**Influences (Stressors):**\n* Forest Composition\n**Logic Description:** Invasive species impacts.'
forests_temperate_forests_european_stressors["Invasive Species"]["Influenced By"] = ['* Disturbance', '* Climate Change', '* Global Trade', '**Influences (Stressors):**', '* Forest Composition', '**Logic Description:** Invasive species impacts.']
forests_temperate_forests_european_stressors["Invasive Species"]["Influences"] = ['* Forest Composition', '**Logic Description:** Invasive species impacts.']
forests_temperate_forests_european_stressors["Invasive Species"]["Logic Description"] = '---'
forests_temperate_forests_european_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_forests_temperate_forests_european"

