from stressor_templates import *
import copy

grasslands_african_savannas_stressors = {
    "Land-Use Change": {},
    "Habitat Fragmentation": {},
    "Climate Change": copy.deepcopy(climate_change_template),
    "Wildfires": copy.deepcopy(fire_regime_template),
    "Poaching": {},
    "Overgrazing": {},
    "Invasive Species": copy.deepcopy(invasive_species_template),
}

# --- Land-Use Change ---
grasslands_african_savannas_stressors["Land-Use Change"]["Metric"] = 'Area converted to agriculture, settlements, or other land uses (ha/year).'
grasslands_african_savannas_stressors["Land-Use Change"]["Data Sources"] = ['Remote sensing data.', 'National government statistics.', 'Research publications.', '**Impact on Area:** Loss of savanna habitat; fragmentation.', '**Impact on Biodiversity:**', 'Habitat loss and fragmentation.', 'Disruption of migration routes (for large mammals).', 'Increased human-wildlife conflict.', '**Influenced By (Stressors):**', '* African Savannas - Agricultural Expansion', '* African Savannas - Population Growth', '* African Savannas - Government Policies', '**Influences (Stressors):**', '*  African Savannas - Habitat Fragmentation', '**Logic Description:** Conversion of savanna to agriculture and settlements is a major threat, leading to habitat loss, fragmentation, and increased conflict between humans and wildlife.']
grasslands_african_savannas_stressors["Land-Use Change"]["Impact on Area"] = 'Loss of savanna habitat; fragmentation.'
grasslands_african_savannas_stressors["Land-Use Change"]["Impact on Biodiversity"] = 'Habitat loss and fragmentation.\nDisruption of migration routes (for large mammals).\nIncreased human-wildlife conflict.\n**Influenced By (Stressors):**\n* African Savannas - Agricultural Expansion\n* African Savannas - Population Growth\n* African Savannas - Government Policies\n**Influences (Stressors):**\n*  African Savannas - Habitat Fragmentation\n**Logic Description:** Conversion of savanna to agriculture and settlements is a major threat, leading to habitat loss, fragmentation, and increased conflict between humans and wildlife.'
grasslands_african_savannas_stressors["Land-Use Change"]["Influenced By"] = ['* African Savannas - Agricultural Expansion', '* African Savannas - Population Growth', '* African Savannas - Government Policies', '**Influences (Stressors):**', '*  African Savannas - Habitat Fragmentation', '**Logic Description:** Conversion of savanna to agriculture and settlements is a major threat, leading to habitat loss, fragmentation, and increased conflict between humans and wildlife.']
grasslands_african_savannas_stressors["Land-Use Change"]["Influences"] = ['*  African Savannas - Habitat Fragmentation', '**Logic Description:** Conversion of savanna to agriculture and settlements is a major threat, leading to habitat loss, fragmentation, and increased conflict between humans and wildlife.']
grasslands_african_savannas_stressors["Land-Use Change"]["Logic Description"] = '---'
grasslands_african_savannas_stressors["Land-Use Change"]["Impact Function"] = "impact_land_use_change_grasslands_african_savannas"

# --- Habitat Fragmentation ---
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Metric"] = 'Patch size distribution; edge density; connectivity indices.'
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Data Sources"] = ['Land cover data (from remote sensing).', 'GIS analysis.', '**Impact on Area:** Remaining savanna exists in increasingly isolated patches.', '**Impact on Biodiversity:**', 'Reduced gene flow.', 'Increased edge effects.', 'Limited dispersal ability.', 'Increased vulnerability to stochastic events.', '**Influenced By (Stressors):**', '*  African Savannas - Land-Use Change', '**Influences (Stressors):**', '* Exacerbates other stressor impacts', '**Logic Description:** Fragmentation isolates savanna patches, reducing their ecological viability and increasing the vulnerability of wildlife populations.']
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Impact on Area"] = 'Remaining savanna exists in increasingly isolated patches.'
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Impact on Biodiversity"] = 'Reduced gene flow.\nIncreased edge effects.\nLimited dispersal ability.\nIncreased vulnerability to stochastic events.\n**Influenced By (Stressors):**\n*  African Savannas - Land-Use Change\n**Influences (Stressors):**\n* Exacerbates other stressor impacts\n**Logic Description:** Fragmentation isolates savanna patches, reducing their ecological viability and increasing the vulnerability of wildlife populations.'
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Influenced By"] = ['*  African Savannas - Land-Use Change', '**Influences (Stressors):**', '* Exacerbates other stressor impacts', '**Logic Description:** Fragmentation isolates savanna patches, reducing their ecological viability and increasing the vulnerability of wildlife populations.']
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Influences"] = ['* Exacerbates other stressor impacts', '**Logic Description:** Fragmentation isolates savanna patches, reducing their ecological viability and increasing the vulnerability of wildlife populations.']
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Logic Description"] = '---'
grasslands_african_savannas_stressors["Habitat Fragmentation"]["Impact Function"] = "impact_habitat_fragmentation_grasslands_african_savannas"

# --- Climate Change ---
grasslands_african_savannas_stressors["Climate Change"]["Metric"] = 'Temperature increase (°C); changes in precipitation (mm/year, seasonality); increased frequency and severity of drought.'
grasslands_african_savannas_stressors["Climate Change"]["Data Sources"] = ['* Climate models.', '* Historical records', '**Impact on Area:** Indirect; changes in growing conditions.', '**Impact on Biodiversity:**', 'Shifts in species distributions.', 'Increased stress on savanna species.', 'Changes in phenology.', 'Increased fire risk (in some areas).', 'Changes in water availability.', '**Influenced By (Stressors):**', '* Global GHG', '**Influences (Stressors):**', '*  African Savannas - Fire Regimes', '*  African Savannas - Water Availability', '**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing stress on savanna ecosystems and impacting water resources.']
grasslands_african_savannas_stressors["Climate Change"]["Impact on Area"] = 'Indirect; changes in growing conditions.'
grasslands_african_savannas_stressors["Climate Change"]["Impact on Biodiversity"] = 'Shifts in species distributions.\nIncreased stress on savanna species.\nChanges in phenology.\nIncreased fire risk (in some areas).\nChanges in water availability.\n**Influenced By (Stressors):**\n* Global GHG\n**Influences (Stressors):**\n*  African Savannas - Fire Regimes\n*  African Savannas - Water Availability\n**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing stress on savanna ecosystems and impacting water resources.'
grasslands_african_savannas_stressors["Climate Change"]["Influenced By"] = ['* Global GHG', '**Influences (Stressors):**', '*  African Savannas - Fire Regimes', '*  African Savannas - Water Availability', '**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing stress on savanna ecosystems and impacting water resources.']
grasslands_african_savannas_stressors["Climate Change"]["Influences"] = ['*  African Savannas - Fire Regimes', '*  African Savannas - Water Availability', '**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing stress on savanna ecosystems and impacting water resources.']
grasslands_african_savannas_stressors["Climate Change"]["Logic Description"] = '---'
grasslands_african_savannas_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_grasslands_african_savannas"

# --- Wildfires ---
grasslands_african_savannas_stressors["Wildfires"]["Metric"] = 'Fire frequency (return interval); area burned (ha/year); fire intensity.'
grasslands_african_savannas_stressors["Wildfires"]["Data Sources"] = ['Remote sensing data (fire detection).', 'Research studies.', 'Local community knowledge.', '**Impact on Area:** Changes in vegetation structure and composition (can be both beneficial and detrimental, depending on fire regime).', '**Impact on Biodiversity:**', 'Many savanna species are adapted to fire, and fire is a natural and important process.', 'However, changes in fire frequency, intensity, or timing (due to climate change or human activities) can have negative impacts.', 'Too frequent or intense fires can damage trees and favor grasses.', 'Too infrequent fires can lead to woody encroachment.', '**Influenced By (Stressors):**', '*  African Savannas - Climate Change', '*  African Savannas - Human Activities', '*  African Savannas - Land-Use Change', '**Influences (Stressors):**', '*  African Savannas - Vegetation Structure', '**Logic Description:** Fire is a natural and important process in savannas, but changes in fire regimes due to climate change and human activities can have significant ecological impacts.']
grasslands_african_savannas_stressors["Wildfires"]["Impact on Area"] = 'Changes in vegetation structure and composition (can be both beneficial and detrimental, depending on fire regime).'
grasslands_african_savannas_stressors["Wildfires"]["Impact on Biodiversity"] = 'Many savanna species are adapted to fire, and fire is a natural and important process.\nHowever, changes in fire frequency, intensity, or timing (due to climate change or human activities) can have negative impacts.\nToo frequent or intense fires can damage trees and favor grasses.\nToo infrequent fires can lead to woody encroachment.\n**Influenced By (Stressors):**\n*  African Savannas - Climate Change\n*  African Savannas - Human Activities\n*  African Savannas - Land-Use Change\n**Influences (Stressors):**\n*  African Savannas - Vegetation Structure\n**Logic Description:** Fire is a natural and important process in savannas, but changes in fire regimes due to climate change and human activities can have significant ecological impacts.'
grasslands_african_savannas_stressors["Wildfires"]["Influenced By"] = ['*  African Savannas - Climate Change', '*  African Savannas - Human Activities', '*  African Savannas - Land-Use Change', '**Influences (Stressors):**', '*  African Savannas - Vegetation Structure', '**Logic Description:** Fire is a natural and important process in savannas, but changes in fire regimes due to climate change and human activities can have significant ecological impacts.']
grasslands_african_savannas_stressors["Wildfires"]["Influences"] = ['*  African Savannas - Vegetation Structure', '**Logic Description:** Fire is a natural and important process in savannas, but changes in fire regimes due to climate change and human activities can have significant ecological impacts.']
grasslands_african_savannas_stressors["Wildfires"]["Logic Description"] = '---'
grasslands_african_savannas_stressors["Wildfires"]["Impact Function"] = "impact_wildfires_grasslands_african_savannas"

# --- Poaching ---
grasslands_african_savannas_stressors["Poaching"]["Metric"] = 'Number of illegally killed animals (for key species, e.g., elephants, rhinos); poaching incidents.'
grasslands_african_savannas_stressors["Poaching"]["Data Sources"] = ['Law enforcement data.', 'Wildlife monitoring programs.', 'Reports from conservation organizations.', '**Impact on Area:** Indirect (through impacts on wildlife populations).', '**Impact on Biodiversity:**', 'Decline of key species (e.g., elephants, rhinos, lions).', 'Cascading effects on the ecosystem (e.g., loss of keystone herbivores can alter vegetation structure).', 'Loss of genetic diversity.', '**Influenced By (Stressors):**', '* African Savannas - Demand for Wildlife Products', '* African Savannas - Poverty', '* African Savannas - Weak Governance', '* African Savannas - Organized Crime', '**Influences (Stressors):**', '*  African Savannas - Wildlife Populations', '*  African Savannas - Ecosystem Function', '**Logic Description:** Poaching, driven by demand for wildlife products and other factors, is a major threat to many savanna species, with cascading effects on the ecosystem.']
grasslands_african_savannas_stressors["Poaching"]["Impact on Area"] = 'Indirect (through impacts on wildlife populations).'
grasslands_african_savannas_stressors["Poaching"]["Impact on Biodiversity"] = 'Decline of key species (e.g., elephants, rhinos, lions).\nCascading effects on the ecosystem (e.g., loss of keystone herbivores can alter vegetation structure).\nLoss of genetic diversity.\n**Influenced By (Stressors):**\n* African Savannas - Demand for Wildlife Products\n* African Savannas - Poverty\n* African Savannas - Weak Governance\n* African Savannas - Organized Crime\n**Influences (Stressors):**\n*  African Savannas - Wildlife Populations\n*  African Savannas - Ecosystem Function\n**Logic Description:** Poaching, driven by demand for wildlife products and other factors, is a major threat to many savanna species, with cascading effects on the ecosystem.'
grasslands_african_savannas_stressors["Poaching"]["Influenced By"] = ['* African Savannas - Demand for Wildlife Products', '* African Savannas - Poverty', '* African Savannas - Weak Governance', '* African Savannas - Organized Crime', '**Influences (Stressors):**', '*  African Savannas - Wildlife Populations', '*  African Savannas - Ecosystem Function', '**Logic Description:** Poaching, driven by demand for wildlife products and other factors, is a major threat to many savanna species, with cascading effects on the ecosystem.']
grasslands_african_savannas_stressors["Poaching"]["Influences"] = ['*  African Savannas - Wildlife Populations', '*  African Savannas - Ecosystem Function', '**Logic Description:** Poaching, driven by demand for wildlife products and other factors, is a major threat to many savanna species, with cascading effects on the ecosystem.']
grasslands_african_savannas_stressors["Poaching"]["Logic Description"] = '---'
grasslands_african_savannas_stressors["Poaching"]["Impact Function"] = "impact_poaching_grasslands_african_savannas"

# --- Overgrazing ---
grasslands_african_savannas_stressors["Overgrazing"]["Metric"] = 'Livestock density; vegetation cover and composition; soil erosion.'
grasslands_african_savannas_stressors["Overgrazing"]["Data Sources"] = ['* Agricultural statistics', '* Vegetation surveys.', '* Remote sensing', '**Impact on Area:** Changes in vegetation structure; soil degradation.', '**Impact on Biodiversity:**', 'Loss of palatable plant species.', 'Spread of unpalatable or invasive species.', '* Soil compaction and erosion.', '* Competition with wild herbivores.', '**Influenced By (Stressors):**', '*  African Savannas - Livestock Management', 'African Savannas - Population Growth: Increased demand for livestock products.', '**Influences (Stressors):**', '*  African Savannas - Vegetation Structure', '**Logic Description:** Overgrazing by livestock can degrade savanna vegetation, leading to soil erosion and competition with wild herbivores.']
grasslands_african_savannas_stressors["Overgrazing"]["Impact on Area"] = 'Changes in vegetation structure; soil degradation.'
grasslands_african_savannas_stressors["Overgrazing"]["Impact on Biodiversity"] = 'Loss of palatable plant species.\nSpread of unpalatable or invasive species.\n* Soil compaction and erosion.\n* Competition with wild herbivores.\n**Influenced By (Stressors):**\n*  African Savannas - Livestock Management\nAfrican Savannas - Population Growth: Increased demand for livestock products.\n**Influences (Stressors):**\n*  African Savannas - Vegetation Structure\n**Logic Description:** Overgrazing by livestock can degrade savanna vegetation, leading to soil erosion and competition with wild herbivores.'
grasslands_african_savannas_stressors["Overgrazing"]["Influenced By"] = ['*  African Savannas - Livestock Management', 'African Savannas - Population Growth: Increased demand for livestock products.', '**Influences (Stressors):**', '*  African Savannas - Vegetation Structure', '**Logic Description:** Overgrazing by livestock can degrade savanna vegetation, leading to soil erosion and competition with wild herbivores.']
grasslands_african_savannas_stressors["Overgrazing"]["Influences"] = ['*  African Savannas - Vegetation Structure', '**Logic Description:** Overgrazing by livestock can degrade savanna vegetation, leading to soil erosion and competition with wild herbivores.']
grasslands_african_savannas_stressors["Overgrazing"]["Logic Description"] = '---'
grasslands_african_savannas_stressors["Overgrazing"]["Impact Function"] = "impact_overgrazing_grasslands_african_savannas"

# --- Invasive Species ---
grasslands_african_savannas_stressors["Invasive Species"]["Metric"] = 'Abundance/Distribution of key invasive species.'
grasslands_african_savannas_stressors["Invasive Species"]["Data Sources"] = ['* Vegetation surveys.', '* Research.', '**Impact on Area:** Changes in vegetation composition.', '**Impact on Biodiversity:**', '* Competition with native species.', '* Altered fire regimes.', '**Influenced By (Stressors):**', '*  African Savannas - Disturbance', '*  African Savannas - Climate Change', '**Influences (Stressors):**', '*  African Savannas - Native plant communities', '**Logic Description:** Invasive species can outcompete native plants and alter ecosystem processes.']
grasslands_african_savannas_stressors["Invasive Species"]["Impact on Area"] = 'Changes in vegetation composition.'
grasslands_african_savannas_stressors["Invasive Species"]["Impact on Biodiversity"] = '* Competition with native species.\n* Altered fire regimes.\n**Influenced By (Stressors):**\n*  African Savannas - Disturbance\n*  African Savannas - Climate Change\n**Influences (Stressors):**\n*  African Savannas - Native plant communities\n**Logic Description:** Invasive species can outcompete native plants and alter ecosystem processes.'
grasslands_african_savannas_stressors["Invasive Species"]["Influenced By"] = ['*  African Savannas - Disturbance', '*  African Savannas - Climate Change', '**Influences (Stressors):**', '*  African Savannas - Native plant communities', '**Logic Description:** Invasive species can outcompete native plants and alter ecosystem processes.']
grasslands_african_savannas_stressors["Invasive Species"]["Influences"] = ['*  African Savannas - Native plant communities', '**Logic Description:** Invasive species can outcompete native plants and alter ecosystem processes.']
grasslands_african_savannas_stressors["Invasive Species"]["Logic Description"] = '---'
grasslands_african_savannas_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_grasslands_african_savannas"

