from stressor_templates import *
import copy

grasslands_australian_grasslands_stressors = {
    "Land-Use Change": {},
    "Habitat Fragmentation": {},
    "Climate Change": copy.deepcopy(climate_change_template),
    "Overgrazing": {},
    "Wildfires": copy.deepcopy(fire_regime_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
}

# --- Land-Use Change ---
grasslands_australian_grasslands_stressors["Land-Use Change"]["Metric"] = 'Area converted to agriculture, pasture, or other land uses (ha/year).'
grasslands_australian_grasslands_stressors["Land-Use Change"]["Data Sources"] = ['Remote sensing data.', 'Australian government data (e.g., Department of Agriculture, Water and the Environment).', 'Research publications.', '**Impact on Area:** Loss of grassland habitat; fragmentation.', '**Impact on Biodiversity:**', 'Habitat loss and fragmentation.', 'Decline of grassland-dependent species.', '**Influenced By (Stressors):**', 'Australian Grasslands - Agricultural Expansion: Demand for cropland and pasture.', 'Australian Grasslands - Population Growth.', '*  Australian Grasslands - Government Policies.', '**Influences (Stressors):**', '*  Australian Grasslands - Habitat Fragmentation', '**Logic Description:** Conversion of grasslands to agriculture and pasture is a major threat.']
grasslands_australian_grasslands_stressors["Land-Use Change"]["Impact on Area"] = 'Loss of grassland habitat; fragmentation.'
grasslands_australian_grasslands_stressors["Land-Use Change"]["Impact on Biodiversity"] = 'Habitat loss and fragmentation.\nDecline of grassland-dependent species.\n**Influenced By (Stressors):**\nAustralian Grasslands - Agricultural Expansion: Demand for cropland and pasture.\nAustralian Grasslands - Population Growth.\n*  Australian Grasslands - Government Policies.\n**Influences (Stressors):**\n*  Australian Grasslands - Habitat Fragmentation\n**Logic Description:** Conversion of grasslands to agriculture and pasture is a major threat.'
grasslands_australian_grasslands_stressors["Land-Use Change"]["Influenced By"] = ['Australian Grasslands - Agricultural Expansion: Demand for cropland and pasture.', 'Australian Grasslands - Population Growth.', '*  Australian Grasslands - Government Policies.', '**Influences (Stressors):**', '*  Australian Grasslands - Habitat Fragmentation', '**Logic Description:** Conversion of grasslands to agriculture and pasture is a major threat.']
grasslands_australian_grasslands_stressors["Land-Use Change"]["Influences"] = ['*  Australian Grasslands - Habitat Fragmentation', '**Logic Description:** Conversion of grasslands to agriculture and pasture is a major threat.']
grasslands_australian_grasslands_stressors["Land-Use Change"]["Logic Description"] = '---'
grasslands_australian_grasslands_stressors["Land-Use Change"]["Impact Function"] = "impact_land_use_change_grasslands_australian_grasslands"

# --- Habitat Fragmentation ---
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Metric"] = 'Patch size distribution; edge density; connectivity indices.'
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Data Sources"] = ['Land cover data.', 'GIS analysis.', '**Impact on Area:** Remaining grasslands exist in isolated patches.', '**Impact on Biodiversity:**', '* Reduced gene flow.', 'Increased edge effects.', '*  Limited dispersal', '* Increased vulnerability', '**Influenced By (Stressors):**', '*  Australian Grasslands - Land-Use Change.', '**Influences (Stressors):**', '* Exacerbates other stressors', '**Logic Description:** Fragmentation isolates grassland patches.']
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Impact on Area"] = 'Remaining grasslands exist in isolated patches.'
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Impact on Biodiversity"] = '* Reduced gene flow.\nIncreased edge effects.\n*  Limited dispersal\n* Increased vulnerability\n**Influenced By (Stressors):**\n*  Australian Grasslands - Land-Use Change.\n**Influences (Stressors):**\n* Exacerbates other stressors\n**Logic Description:** Fragmentation isolates grassland patches.'
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Influenced By"] = ['*  Australian Grasslands - Land-Use Change.', '**Influences (Stressors):**', '* Exacerbates other stressors', '**Logic Description:** Fragmentation isolates grassland patches.']
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Influences"] = ['* Exacerbates other stressors', '**Logic Description:** Fragmentation isolates grassland patches.']
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Logic Description"] = '---'
grasslands_australian_grasslands_stressors["Habitat Fragmentation"]["Impact Function"] = "impact_habitat_fragmentation_grasslands_australian_grasslands"

# --- Climate Change ---
grasslands_australian_grasslands_stressors["Climate Change"]["Metric"] = 'Temperature increase (°C); changes in precipitation (mm/year, seasonality); increased frequency and severity of drought.'
grasslands_australian_grasslands_stressors["Climate Change"]["Data Sources"] = ['Climate models.', 'Historical records (Bureau of Meteorology).', '**Impact on Area:** Indirect; changes in growing conditions.', '**Impact on Biodiversity:**', 'Shifts in species distributions.', 'Increased stress on grassland species.', 'Changes in phenology.', 'Increased fire risk (in some areas).', '**Influenced By (Stressors):**', '* Global GHG', '**Influences (Stressors):**', '*  Australian Grasslands - Fire Regimes.', '*  Australian Grasslands - Water Availability', '**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing aridity and fire risk in many areas.']
grasslands_australian_grasslands_stressors["Climate Change"]["Impact on Area"] = 'Indirect; changes in growing conditions.'
grasslands_australian_grasslands_stressors["Climate Change"]["Impact on Biodiversity"] = 'Shifts in species distributions.\nIncreased stress on grassland species.\nChanges in phenology.\nIncreased fire risk (in some areas).\n**Influenced By (Stressors):**\n* Global GHG\n**Influences (Stressors):**\n*  Australian Grasslands - Fire Regimes.\n*  Australian Grasslands - Water Availability\n**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing aridity and fire risk in many areas.'
grasslands_australian_grasslands_stressors["Climate Change"]["Influenced By"] = ['* Global GHG', '**Influences (Stressors):**', '*  Australian Grasslands - Fire Regimes.', '*  Australian Grasslands - Water Availability', '**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing aridity and fire risk in many areas.']
grasslands_australian_grasslands_stressors["Climate Change"]["Influences"] = ['*  Australian Grasslands - Fire Regimes.', '*  Australian Grasslands - Water Availability', '**Logic Description:** Climate change is altering temperature and precipitation patterns, increasing aridity and fire risk in many areas.']
grasslands_australian_grasslands_stressors["Climate Change"]["Logic Description"] = '---'
grasslands_australian_grasslands_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_grasslands_australian_grasslands"

# --- Overgrazing ---
grasslands_australian_grasslands_stressors["Overgrazing"]["Metric"] = 'Livestock density; vegetation cover and composition; soil erosion.'
grasslands_australian_grasslands_stressors["Overgrazing"]["Data Sources"] = ['* Agricultural statistics', '* Vegetation Surveys', '**Impact on Area:** Changes in vegetation; soil degradation.', '**Impact on Biodiversity:**', '* Loss of palatable species', '* Spread of unpalatable species and weeds.', '* Soil compaction and erosion.', '* Competition with native herbivores.', '**Influenced By (Stressors):**', '*  Australian Grasslands - Livestock Management.', '*  Australian Grasslands - Feral Herbivores', '**Influences (Stressors):**', '*  Australian Grasslands - Vegetation Structure', '* Desertification', '**Logic Description:** Overgrazing by livestock and feral herbivores is a widespread problem, leading to vegetation degradation and soil erosion.']
grasslands_australian_grasslands_stressors["Overgrazing"]["Impact on Area"] = 'Changes in vegetation; soil degradation.'
grasslands_australian_grasslands_stressors["Overgrazing"]["Impact on Biodiversity"] = '* Loss of palatable species\n* Spread of unpalatable species and weeds.\n* Soil compaction and erosion.\n* Competition with native herbivores.\n**Influenced By (Stressors):**\n*  Australian Grasslands - Livestock Management.\n*  Australian Grasslands - Feral Herbivores\n**Influences (Stressors):**\n*  Australian Grasslands - Vegetation Structure\n* Desertification\n**Logic Description:** Overgrazing by livestock and feral herbivores is a widespread problem, leading to vegetation degradation and soil erosion.'
grasslands_australian_grasslands_stressors["Overgrazing"]["Influenced By"] = ['*  Australian Grasslands - Livestock Management.', '*  Australian Grasslands - Feral Herbivores', '**Influences (Stressors):**', '*  Australian Grasslands - Vegetation Structure', '* Desertification', '**Logic Description:** Overgrazing by livestock and feral herbivores is a widespread problem, leading to vegetation degradation and soil erosion.']
grasslands_australian_grasslands_stressors["Overgrazing"]["Influences"] = ['*  Australian Grasslands - Vegetation Structure', '* Desertification', '**Logic Description:** Overgrazing by livestock and feral herbivores is a widespread problem, leading to vegetation degradation and soil erosion.']
grasslands_australian_grasslands_stressors["Overgrazing"]["Logic Description"] = '---'
grasslands_australian_grasslands_stressors["Overgrazing"]["Impact Function"] = "impact_overgrazing_grasslands_australian_grasslands"

# --- Wildfires ---
grasslands_australian_grasslands_stressors["Wildfires"]["Metric"] = 'Fire frequency; area burned (ha/year); fire intensity.'
grasslands_australian_grasslands_stressors["Wildfires"]["Data Sources"] = ['Remote sensing data.', 'Government fire agency data.', '**Impact on Area:** Changes in vegetation structure and composition.', '**Impact on Biodiversity:**', '* Can be beneficial or detrimental, depending on fire regime. Many Australian grassland species are adapted to fire, but changes in fire frequency or intensity can have negative impacts.', '**Influenced By (Stressors):**', 'Australian Grasslands - Climate Change', 'Australian Grasslands - Land Management Practices', '*  Australian Grasslands - Human Activities', '**Influences (Stressors):**', '*  Australian Grasslands - Vegetation Structure', '**Logic Description:** Changes in fire regimes, often linked to climate change and land management, can impact grassland ecosystems.']
grasslands_australian_grasslands_stressors["Wildfires"]["Impact on Area"] = 'Changes in vegetation structure and composition.'
grasslands_australian_grasslands_stressors["Wildfires"]["Impact on Biodiversity"] = '* Can be beneficial or detrimental, depending on fire regime. Many Australian grassland species are adapted to fire, but changes in fire frequency or intensity can have negative impacts.\n**Influenced By (Stressors):**\nAustralian Grasslands - Climate Change\nAustralian Grasslands - Land Management Practices\n*  Australian Grasslands - Human Activities\n**Influences (Stressors):**\n*  Australian Grasslands - Vegetation Structure\n**Logic Description:** Changes in fire regimes, often linked to climate change and land management, can impact grassland ecosystems.'
grasslands_australian_grasslands_stressors["Wildfires"]["Influenced By"] = ['Australian Grasslands - Climate Change', 'Australian Grasslands - Land Management Practices', '*  Australian Grasslands - Human Activities', '**Influences (Stressors):**', '*  Australian Grasslands - Vegetation Structure', '**Logic Description:** Changes in fire regimes, often linked to climate change and land management, can impact grassland ecosystems.']
grasslands_australian_grasslands_stressors["Wildfires"]["Influences"] = ['*  Australian Grasslands - Vegetation Structure', '**Logic Description:** Changes in fire regimes, often linked to climate change and land management, can impact grassland ecosystems.']
grasslands_australian_grasslands_stressors["Wildfires"]["Logic Description"] = '---'
grasslands_australian_grasslands_stressors["Wildfires"]["Impact Function"] = "impact_wildfires_grasslands_australian_grasslands"

# --- Invasive Species ---
grasslands_australian_grasslands_stressors["Invasive Species"]["Metric"] = 'Abundance/Distribution, e.g., Buffel grass'
grasslands_australian_grasslands_stressors["Invasive Species"]["Data Sources"] = ['* Vegetation surveys', '* Research', '**Impact on Area:** Vegetation changes.', '**Impact on Biodiversity:**', '* Competition.', '* Altered fire regimes (some invasives increase fire intensity).', '**Influenced By (Stressors):**', '*  Australian Grasslands - Disturbance', '*  Australian Grasslands - Climate Change', '**Influences (Stressors):**', '*  Australian Grasslands - Native Plant Communities', '*  Australian Grasslands - Fire Regimes', '**Logic Description:** Invasive species, particularly some grasses (e.g., buffel grass), can outcompete native plants and alter fire regimes.']
grasslands_australian_grasslands_stressors["Invasive Species"]["Impact on Area"] = 'Vegetation changes.'
grasslands_australian_grasslands_stressors["Invasive Species"]["Impact on Biodiversity"] = '* Competition.\n* Altered fire regimes (some invasives increase fire intensity).\n**Influenced By (Stressors):**\n*  Australian Grasslands - Disturbance\n*  Australian Grasslands - Climate Change\n**Influences (Stressors):**\n*  Australian Grasslands - Native Plant Communities\n*  Australian Grasslands - Fire Regimes\n**Logic Description:** Invasive species, particularly some grasses (e.g., buffel grass), can outcompete native plants and alter fire regimes.'
grasslands_australian_grasslands_stressors["Invasive Species"]["Influenced By"] = ['*  Australian Grasslands - Disturbance', '*  Australian Grasslands - Climate Change', '**Influences (Stressors):**', '*  Australian Grasslands - Native Plant Communities', '*  Australian Grasslands - Fire Regimes', '**Logic Description:** Invasive species, particularly some grasses (e.g., buffel grass), can outcompete native plants and alter fire regimes.']
grasslands_australian_grasslands_stressors["Invasive Species"]["Influences"] = ['*  Australian Grasslands - Native Plant Communities', '*  Australian Grasslands - Fire Regimes', '**Logic Description:** Invasive species, particularly some grasses (e.g., buffel grass), can outcompete native plants and alter fire regimes.']
grasslands_australian_grasslands_stressors["Invasive Species"]["Logic Description"] = '---'
grasslands_australian_grasslands_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_grasslands_australian_grasslands"

