from stressor_templates import *
import copy

mountains_ethiopian_highlands_stressors = {
    "Soil Erosion": {},
    "Invasive Species": copy.deepcopy(invasive_species_template),
}

# --- Soil Erosion ---
mountains_ethiopian_highlands_stressors["Soil Erosion"]["Metric"] = 'Soil loss rate (tonnes/ha/year); gully formation; sediment load in rivers.'
mountains_ethiopian_highlands_stressors["Soil Erosion"]["Data Sources"] = ['Field measurements (e.g., using erosion pins).', 'Remote sensing data.', 'Research publications.', '**Impact on Area:** Loss of topsoil; reduced land productivity; sedimentation of rivers and reservoirs.', '**Impact on Biodiversity:**', 'Loss of soil fertility, impacting plant communities.', 'Degradation of water quality.', '**Influenced By (Stressors):**', 'Deforestation: Loss of vegetation cover leaves soil exposed.', 'Overgrazing: Reduces vegetation cover.', 'Intensive Agriculture: On steep slopes without proper soil conservation practices.', 'Population Pressure: Leads to cultivation of marginal lands.', '**Influences (Stressors):**', 'Agricultural Productivity: Reduces crop yields.', 'Water Quality: Increased sediment load in rivers.', 'Reservoir Siltation: Reduces the lifespan of reservoirs.', '**Logic Description:** Soil erosion is a *severe* and widespread problem in the Ethiopian Highlands, driven by deforestation, overgrazing, intensive agriculture, and population pressure. This loss of topsoil reduces land productivity and impacts water quality.']
mountains_ethiopian_highlands_stressors["Soil Erosion"]["Impact on Area"] = 'Loss of topsoil; reduced land productivity; sedimentation of rivers and reservoirs.'
mountains_ethiopian_highlands_stressors["Soil Erosion"]["Impact on Biodiversity"] = 'Loss of soil fertility, impacting plant communities.\nDegradation of water quality.\n**Influenced By (Stressors):**\nDeforestation: Loss of vegetation cover leaves soil exposed.\nOvergrazing: Reduces vegetation cover.\nIntensive Agriculture: On steep slopes without proper soil conservation practices.\nPopulation Pressure: Leads to cultivation of marginal lands.\n**Influences (Stressors):**\nAgricultural Productivity: Reduces crop yields.\nWater Quality: Increased sediment load in rivers.\nReservoir Siltation: Reduces the lifespan of reservoirs.\n**Logic Description:** Soil erosion is a *severe* and widespread problem in the Ethiopian Highlands, driven by deforestation, overgrazing, intensive agriculture, and population pressure. This loss of topsoil reduces land productivity and impacts water quality.'
mountains_ethiopian_highlands_stressors["Soil Erosion"]["Influenced By"] = ['Deforestation: Loss of vegetation cover leaves soil exposed.', 'Overgrazing: Reduces vegetation cover.', 'Intensive Agriculture: On steep slopes without proper soil conservation practices.', 'Population Pressure: Leads to cultivation of marginal lands.', '**Influences (Stressors):**', 'Agricultural Productivity: Reduces crop yields.', 'Water Quality: Increased sediment load in rivers.', 'Reservoir Siltation: Reduces the lifespan of reservoirs.', '**Logic Description:** Soil erosion is a *severe* and widespread problem in the Ethiopian Highlands, driven by deforestation, overgrazing, intensive agriculture, and population pressure. This loss of topsoil reduces land productivity and impacts water quality.']
mountains_ethiopian_highlands_stressors["Soil Erosion"]["Influences"] = ['Agricultural Productivity: Reduces crop yields.', 'Water Quality: Increased sediment load in rivers.', 'Reservoir Siltation: Reduces the lifespan of reservoirs.', '**Logic Description:** Soil erosion is a *severe* and widespread problem in the Ethiopian Highlands, driven by deforestation, overgrazing, intensive agriculture, and population pressure. This loss of topsoil reduces land productivity and impacts water quality.']
mountains_ethiopian_highlands_stressors["Soil Erosion"]["Logic Description"] = '---'

# --- Invasive Species ---
mountains_ethiopian_highlands_stressors["Invasive Species"]["Metric"] = 'Distribution and abundance'
mountains_ethiopian_highlands_stressors["Invasive Species"]["Data Sources"] = ['* Field Surveys', '* Research', '**Impact on Area:** Changes in plant communities.', '**Impact on Biodiversity:**', '* Competition with native species.', '**Influenced By (Stressors):**', '* Human activities.', '* Disturbance.', '**Influences (Stressors):**', '* Native plant communities.', '**Logic Description**: Invasive plants can impact.']
mountains_ethiopian_highlands_stressors["Invasive Species"]["Impact on Area"] = 'Changes in plant communities.'
mountains_ethiopian_highlands_stressors["Invasive Species"]["Impact on Biodiversity"] = '* Competition with native species.\n**Influenced By (Stressors):**\n* Human activities.\n* Disturbance.\n**Influences (Stressors):**\n* Native plant communities.\n**Logic Description**: Invasive plants can impact.'
mountains_ethiopian_highlands_stressors["Invasive Species"]["Influenced By"] = ['* Human activities.', '* Disturbance.', '**Influences (Stressors):**', '* Native plant communities.', '**Logic Description**: Invasive plants can impact.']
mountains_ethiopian_highlands_stressors["Invasive Species"]["Influences"] = ['* Native plant communities.', '**Logic Description**: Invasive plants can impact.']

