from stressor_templates import *
import copy

reefs_red_sea_reefs_stressors = {
    "Overfishing": copy.deepcopy(overfishing_template),
    "Water Pollution": copy.deepcopy(pollution_template),
    "Coastal Development": {},
    "Coral Disease": {},
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Climate Change": copy.deepcopy(climate_change_template),
}

# --- Overfishing ---
reefs_red_sea_reefs_stressors["Overfishing"]["Metric"] = 'Fish biomass, size structure, and abundance of key species (e.g., groupers, snappers, parrotfish).'
reefs_red_sea_reefs_stressors["Overfishing"]["Data Sources"] = ['Fisheries data (often limited and unreliable).', 'Underwater surveys (conducted by research organizations and conservation groups).', 'Research publications.', '**Impact on Area:** Not directly applicable, but affects ecosystem structure.', '**Impact on Biodiversity:**', 'Decline of important fish species, especially large predators and herbivores.', 'Disruption of the food web (e.g., loss of herbivores can lead to algal overgrowth).', 'Loss of top predators.', '**Influenced By (Stressors):**', 'High Fishing Pressure: Due to local dependence on fishing and tourism.', 'Weak Enforcement of Fisheries Regulations.', 'Lack of Alternative Livelihoods.', '**Influences (Stressors):**', 'Algal Overgrowth (if herbivores are removed).', 'Coral Reef Health.', '**Logic Description:** Overfishing is a widespread and chronic problem across the Caribbean, depleting populations of important reef fish and disrupting the ecological balance of reef ecosystems. This is often a *more* severe problem than in, say, the Great Barrier Reef.']
reefs_red_sea_reefs_stressors["Overfishing"]["Impact on Area"] = 'Not directly applicable, but affects ecosystem structure.'
reefs_red_sea_reefs_stressors["Overfishing"]["Impact on Biodiversity"] = 'Decline of important fish species, especially large predators and herbivores.\nDisruption of the food web (e.g., loss of herbivores can lead to algal overgrowth).\nLoss of top predators.\n**Influenced By (Stressors):**\nHigh Fishing Pressure: Due to local dependence on fishing and tourism.\nWeak Enforcement of Fisheries Regulations.\nLack of Alternative Livelihoods.\n**Influences (Stressors):**\nAlgal Overgrowth (if herbivores are removed).\nCoral Reef Health.\n**Logic Description:** Overfishing is a widespread and chronic problem across the Caribbean, depleting populations of important reef fish and disrupting the ecological balance of reef ecosystems. This is often a *more* severe problem than in, say, the Great Barrier Reef.'
reefs_red_sea_reefs_stressors["Overfishing"]["Influenced By"] = ['High Fishing Pressure: Due to local dependence on fishing and tourism.', 'Weak Enforcement of Fisheries Regulations.', 'Lack of Alternative Livelihoods.', '**Influences (Stressors):**', 'Algal Overgrowth (if herbivores are removed).', 'Coral Reef Health.', '**Logic Description:** Overfishing is a widespread and chronic problem across the Caribbean, depleting populations of important reef fish and disrupting the ecological balance of reef ecosystems. This is often a *more* severe problem than in, say, the Great Barrier Reef.']
reefs_red_sea_reefs_stressors["Overfishing"]["Influences"] = ['Algal Overgrowth (if herbivores are removed).', 'Coral Reef Health.', '**Logic Description:** Overfishing is a widespread and chronic problem across the Caribbean, depleting populations of important reef fish and disrupting the ecological balance of reef ecosystems. This is often a *more* severe problem than in, say, the Great Barrier Reef.']
reefs_red_sea_reefs_stressors["Overfishing"]["Logic Description"] = '---'
reefs_red_sea_reefs_stressors["Overfishing"]["Impact Function"] = "impact_overfishing_reefs_red_sea_reefs"

# --- Water Pollution ---
reefs_red_sea_reefs_stressors["Water Pollution"]["Metric"] = 'Concentrations of nutrients (nitrogen, phosphorus), sediments, and other pollutants in coastal waters.'
reefs_red_sea_reefs_stressors["Water Pollution"]["Data Sources"] = ['Water quality monitoring programs (often limited).', 'Research studies.', '**Impact on Area:** Reduced water quality; increased turbidity.', '**Impact on Biodiversity:**', 'Algal overgrowth, smothering corals.', 'Reduced light penetration.', 'Direct harm to corals and other organisms.', 'Increased susceptibility to disease.', '**Influenced By (Stressors):**', 'Agricultural Runoff: Fertilizers and pesticides.', 'Deforestation: Increased sediment runoff.', 'Urban Runoff: Sewage, stormwater, and industrial effluent.', 'Inadequate Wastewater Treatment: Common in many Caribbean islands.', '**Influences (Stressors):**', 'Coral Reef Health.', 'Algal Blooms.', 'Coral Disease.', '**Logic Description:** Pollution from various sources (agriculture, deforestation, urban runoff, and inadequate wastewater treatment) degrades water quality and impacts coral reefs throughout the Caribbean.']
reefs_red_sea_reefs_stressors["Water Pollution"]["Impact on Area"] = 'Reduced water quality; increased turbidity.'
reefs_red_sea_reefs_stressors["Water Pollution"]["Impact on Biodiversity"] = 'Algal overgrowth, smothering corals.\nReduced light penetration.\nDirect harm to corals and other organisms.\nIncreased susceptibility to disease.\n**Influenced By (Stressors):**\nAgricultural Runoff: Fertilizers and pesticides.\nDeforestation: Increased sediment runoff.\nUrban Runoff: Sewage, stormwater, and industrial effluent.\nInadequate Wastewater Treatment: Common in many Caribbean islands.\n**Influences (Stressors):**\nCoral Reef Health.\nAlgal Blooms.\nCoral Disease.\n**Logic Description:** Pollution from various sources (agriculture, deforestation, urban runoff, and inadequate wastewater treatment) degrades water quality and impacts coral reefs throughout the Caribbean.'
reefs_red_sea_reefs_stressors["Water Pollution"]["Influenced By"] = ['Agricultural Runoff: Fertilizers and pesticides.', 'Deforestation: Increased sediment runoff.', 'Urban Runoff: Sewage, stormwater, and industrial effluent.', 'Inadequate Wastewater Treatment: Common in many Caribbean islands.', '**Influences (Stressors):**', 'Coral Reef Health.', 'Algal Blooms.', 'Coral Disease.', '**Logic Description:** Pollution from various sources (agriculture, deforestation, urban runoff, and inadequate wastewater treatment) degrades water quality and impacts coral reefs throughout the Caribbean.']
reefs_red_sea_reefs_stressors["Water Pollution"]["Influences"] = ['Coral Reef Health.', 'Algal Blooms.', 'Coral Disease.', '**Logic Description:** Pollution from various sources (agriculture, deforestation, urban runoff, and inadequate wastewater treatment) degrades water quality and impacts coral reefs throughout the Caribbean.']
reefs_red_sea_reefs_stressors["Water Pollution"]["Logic Description"] = '---'
reefs_red_sea_reefs_stressors["Water Pollution"]["Impact Function"] = "impact_water_pollution_reefs_red_sea_reefs"

# --- Coastal Development ---
reefs_red_sea_reefs_stressors["Coastal Development"]["Metric"] = 'Area of coastline developed; tourism intensity (number of visitors); infrastructure development.'
reefs_red_sea_reefs_stressors["Coastal Development"]["Data Sources"] = ['Government statistics.', 'Remote sensing data.', 'Reports from conservation organizations.', '**Impact on Area:** Habitat loss (mangroves, seagrass beds); increased sedimentation and pollution.', '**Impact on Biodiversity:**', 'Loss of critical habitats (nursery grounds for fish).', 'Reduced water quality.', 'Physical damage to reefs (construction, anchors).', '**Influenced By (Stressors):**', 'Tourism Development: A major driver in many Caribbean islands.', 'Population Growth.', 'Lack of Effective Coastal Zone Management.', '**Influences (Stressors):**', 'Water Quality.', 'Sedimentation.', 'Habitat Loss.', '**Logic Description:** Rapid coastal development, often driven by tourism, is leading to habitat loss, increased sedimentation, and pollution, impacting coral reefs across the Caribbean.']
reefs_red_sea_reefs_stressors["Coastal Development"]["Impact on Area"] = 'Habitat loss (mangroves, seagrass beds); increased sedimentation and pollution.'
reefs_red_sea_reefs_stressors["Coastal Development"]["Impact on Biodiversity"] = 'Loss of critical habitats (nursery grounds for fish).\nReduced water quality.\nPhysical damage to reefs (construction, anchors).\n**Influenced By (Stressors):**\nTourism Development: A major driver in many Caribbean islands.\nPopulation Growth.\nLack of Effective Coastal Zone Management.\n**Influences (Stressors):**\nWater Quality.\nSedimentation.\nHabitat Loss.\n**Logic Description:** Rapid coastal development, often driven by tourism, is leading to habitat loss, increased sedimentation, and pollution, impacting coral reefs across the Caribbean.'
reefs_red_sea_reefs_stressors["Coastal Development"]["Influenced By"] = ['Tourism Development: A major driver in many Caribbean islands.', 'Population Growth.', 'Lack of Effective Coastal Zone Management.', '**Influences (Stressors):**', 'Water Quality.', 'Sedimentation.', 'Habitat Loss.', '**Logic Description:** Rapid coastal development, often driven by tourism, is leading to habitat loss, increased sedimentation, and pollution, impacting coral reefs across the Caribbean.']
reefs_red_sea_reefs_stressors["Coastal Development"]["Influences"] = ['Water Quality.', 'Sedimentation.', 'Habitat Loss.', '**Logic Description:** Rapid coastal development, often driven by tourism, is leading to habitat loss, increased sedimentation, and pollution, impacting coral reefs across the Caribbean.']
reefs_red_sea_reefs_stressors["Coastal Development"]["Logic Description"] = '---'
reefs_red_sea_reefs_stressors["Coastal Development"]["Impact Function"] = "impact_coastal_development_reefs_red_sea_reefs"

# --- Coral Disease ---
reefs_red_sea_reefs_stressors["Coral Disease"]["Metric"] = 'Prevalence and severity of coral diseases (e.g., white band disease, black band disease, stony coral tissue loss disease).'
reefs_red_sea_reefs_stressors["Coral Disease"]["Data Sources"] = ['Underwater surveys.', 'Research studies.', '**Impact on Area:** Coral mortality; changes in coral community structure.', '**Impact on Biodiversity:**', 'Significant coral mortality (especially for key reef-building species).', 'Loss of coral cover.', 'Shifts in coral species composition.', '**Influenced By (Stressors):**', 'Water Pollution: Can increase coral susceptibility to disease.', 'Ocean Warming: Can exacerbate disease outbreaks.', 'Other Stressors: That weaken corals.', '**Influences (Stressors):**', 'Coral Cover.', 'Reef Resilience.', '**Logic Description:** Coral diseases have caused widespread and devastating coral mortality throughout the Caribbean, contributing significantly to the overall decline of reef ecosystems.']
reefs_red_sea_reefs_stressors["Coral Disease"]["Impact on Area"] = 'Coral mortality; changes in coral community structure.'
reefs_red_sea_reefs_stressors["Coral Disease"]["Impact on Biodiversity"] = 'Significant coral mortality (especially for key reef-building species).\nLoss of coral cover.\nShifts in coral species composition.\n**Influenced By (Stressors):**\nWater Pollution: Can increase coral susceptibility to disease.\nOcean Warming: Can exacerbate disease outbreaks.\nOther Stressors: That weaken corals.\n**Influences (Stressors):**\nCoral Cover.\nReef Resilience.\n**Logic Description:** Coral diseases have caused widespread and devastating coral mortality throughout the Caribbean, contributing significantly to the overall decline of reef ecosystems.'
reefs_red_sea_reefs_stressors["Coral Disease"]["Influenced By"] = ['Water Pollution: Can increase coral susceptibility to disease.', 'Ocean Warming: Can exacerbate disease outbreaks.', 'Other Stressors: That weaken corals.', '**Influences (Stressors):**', 'Coral Cover.', 'Reef Resilience.', '**Logic Description:** Coral diseases have caused widespread and devastating coral mortality throughout the Caribbean, contributing significantly to the overall decline of reef ecosystems.']
reefs_red_sea_reefs_stressors["Coral Disease"]["Influences"] = ['Coral Cover.', 'Reef Resilience.', '**Logic Description:** Coral diseases have caused widespread and devastating coral mortality throughout the Caribbean, contributing significantly to the overall decline of reef ecosystems.']
reefs_red_sea_reefs_stressors["Coral Disease"]["Logic Description"] = '---'
reefs_red_sea_reefs_stressors["Coral Disease"]["Impact Function"] = "impact_coral_disease_reefs_red_sea_reefs"

# --- Invasive Species ---
reefs_red_sea_reefs_stressors["Invasive Species"]["Metric"] = 'Abundance and distribution of lionfish.'
reefs_red_sea_reefs_stressors["Invasive Species"]["Data Sources"] = ['Underwater surveys.', 'Lionfish removal programs.', 'Research studies.', '**Impact on Area:** Primarily affects fish populations (indirect impact on area).', '**Impact on Biodiversity:**', 'Predation on native fish and invertebrates.', 'Competition with native predators.', 'Significant reduction in recruitment of native fish.', '**Influenced By (Stressors):**', 'Introduction through the aquarium trade (likely initial introduction).', 'Lack of Natural Predators: In the Caribbean.', '**Influences (Stressors):**', 'Native Fish Populations.', 'Reef Ecosystem Structure.', '**Logic Description:** The invasive lionfish, a voracious predator with no natural predators in the Caribbean, is a significant threat to native reef fish populations and the overall health of Caribbean reefs.']
reefs_red_sea_reefs_stressors["Invasive Species"]["Impact on Area"] = 'Primarily affects fish populations (indirect impact on area).'
reefs_red_sea_reefs_stressors["Invasive Species"]["Impact on Biodiversity"] = 'Predation on native fish and invertebrates.\nCompetition with native predators.\nSignificant reduction in recruitment of native fish.\n**Influenced By (Stressors):**\nIntroduction through the aquarium trade (likely initial introduction).\nLack of Natural Predators: In the Caribbean.\n**Influences (Stressors):**\nNative Fish Populations.\nReef Ecosystem Structure.\n**Logic Description:** The invasive lionfish, a voracious predator with no natural predators in the Caribbean, is a significant threat to native reef fish populations and the overall health of Caribbean reefs.'
reefs_red_sea_reefs_stressors["Invasive Species"]["Influenced By"] = ['Introduction through the aquarium trade (likely initial introduction).', 'Lack of Natural Predators: In the Caribbean.', '**Influences (Stressors):**', 'Native Fish Populations.', 'Reef Ecosystem Structure.', '**Logic Description:** The invasive lionfish, a voracious predator with no natural predators in the Caribbean, is a significant threat to native reef fish populations and the overall health of Caribbean reefs.']
reefs_red_sea_reefs_stressors["Invasive Species"]["Influences"] = ['Native Fish Populations.', 'Reef Ecosystem Structure.', '**Logic Description:** The invasive lionfish, a voracious predator with no natural predators in the Caribbean, is a significant threat to native reef fish populations and the overall health of Caribbean reefs.']
reefs_red_sea_reefs_stressors["Invasive Species"]["Logic Description"] = '---'
reefs_red_sea_reefs_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_reefs_red_sea_reefs"

# --- Climate Change ---
reefs_red_sea_reefs_stressors["Climate Change"]["Metric"] = 'SST; Ocean acidification; hurricane frequency and intensity.'
reefs_red_sea_reefs_stressors["Climate Change"]["Data Sources"] = ['* Climate Models.', '* Oceanographic data.', '**Impact on Area:** Coral Bleaching; reduced calcification', '**Impact on Biodiversity:**', '* Coral mortality', '* Species shifts', '* Acidification.', '**Influenced By (Stressors):**', '* Global emissions', '**Influences (Stressors):**', '* Bleaching, Acidification, Storm damage.', '**Logic Description:**  Warming, acidification, and potentially stronger storms all have negative effects.']
reefs_red_sea_reefs_stressors["Climate Change"]["Impact on Area"] = 'Coral Bleaching; reduced calcification'
reefs_red_sea_reefs_stressors["Climate Change"]["Impact on Biodiversity"] = '* Coral mortality\n* Species shifts\n* Acidification.\n**Influenced By (Stressors):**\n* Global emissions\n**Influences (Stressors):**\n* Bleaching, Acidification, Storm damage.\n**Logic Description:**  Warming, acidification, and potentially stronger storms all have negative effects.'
reefs_red_sea_reefs_stressors["Climate Change"]["Influenced By"] = ['* Global emissions', '**Influences (Stressors):**', '* Bleaching, Acidification, Storm damage.', '**Logic Description:**  Warming, acidification, and potentially stronger storms all have negative effects.']
reefs_red_sea_reefs_stressors["Climate Change"]["Influences"] = ['* Bleaching, Acidification, Storm damage.', '**Logic Description:**  Warming, acidification, and potentially stronger storms all have negative effects.']
reefs_red_sea_reefs_stressors["Climate Change"]["Logic Description"] = '---'
reefs_red_sea_reefs_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_reefs_red_sea_reefs"

