from stressor_templates import *
import copy

wetlands_mesopotamian_marshes_stressors = {
    "Water Diversion": {},
    "Pollution": copy.deepcopy(pollution_template),
    "Climate Change": copy.deepcopy(climate_change_template),
    "Salinization": {},
}

# --- Water Diversion ---
wetlands_mesopotamian_marshes_stressors["Water Diversion"]["Metric"] = 'Water flow rates in the Tigris and Euphrates rivers; water levels in the marshes; area of inundated marshland.'
wetlands_mesopotamian_marshes_stressors["Water Diversion"]["Data Sources"] = ['Iraqi and Iranian government agencies (water resources ministries).', 'Remote sensing data (satellite imagery).', 'Research publications.', 'United Nations reports (e.g., UNEP).', '**Impact on Area:** *Drastic* reduction in the extent of the marshes (historically, the *major* stressor).', '**Impact on Biodiversity:**', 'Massive habitat loss for marsh-dependent species (fish, birds, mammals).', 'Near-collapse of the traditional Marsh Arab way of life (which is intimately tied to the marshes).', 'Loss of biodiversity.', '**Influenced By (Stressors):**', 'Upstream Dam Construction: *Extensive* dam construction on the Tigris and Euphrates rivers in Turkey, Syria, Iraq, and Iran. This is the *primary* driver.', "Water Management Practices: Drainage of the marshes for agriculture and oil exploration (especially under Saddam Hussein's regime).", 'Irrigation Projects: Upstream water use for agriculture.', '**Influences (Stressors):**', 'Habitat Availability.', 'Water Quality (increased salinity due to reduced freshwater inflow).', '**Logic Description:** The Mesopotamian Marshes have been dramatically reduced in size due to massive water diversions from the Tigris and Euphrates rivers, primarily for upstream dam construction and irrigation. Intentional drainage of the marshes also played a significant role. This is arguably the most impactful example of large-scale wetland destruction in modern history.']
wetlands_mesopotamian_marshes_stressors["Water Diversion"]["Impact on Area"] = '*Drastic* reduction in the extent of the marshes (historically, the *major* stressor).'
wetlands_mesopotamian_marshes_stressors["Water Diversion"]["Impact on Biodiversity"] = "Massive habitat loss for marsh-dependent species (fish, birds, mammals).\nNear-collapse of the traditional Marsh Arab way of life (which is intimately tied to the marshes).\nLoss of biodiversity.\n**Influenced By (Stressors):**\nUpstream Dam Construction: *Extensive* dam construction on the Tigris and Euphrates rivers in Turkey, Syria, Iraq, and Iran. This is the *primary* driver.\nWater Management Practices: Drainage of the marshes for agriculture and oil exploration (especially under Saddam Hussein's regime).\nIrrigation Projects: Upstream water use for agriculture.\n**Influences (Stressors):**\nHabitat Availability.\nWater Quality (increased salinity due to reduced freshwater inflow).\n**Logic Description:** The Mesopotamian Marshes have been dramatically reduced in size due to massive water diversions from the Tigris and Euphrates rivers, primarily for upstream dam construction and irrigation. Intentional drainage of the marshes also played a significant role. This is arguably the most impactful example of large-scale wetland destruction in modern history."
wetlands_mesopotamian_marshes_stressors["Water Diversion"]["Influenced By"] = ['Upstream Dam Construction: *Extensive* dam construction on the Tigris and Euphrates rivers in Turkey, Syria, Iraq, and Iran. This is the *primary* driver.', "Water Management Practices: Drainage of the marshes for agriculture and oil exploration (especially under Saddam Hussein's regime).", 'Irrigation Projects: Upstream water use for agriculture.', '**Influences (Stressors):**', 'Habitat Availability.', 'Water Quality (increased salinity due to reduced freshwater inflow).', '**Logic Description:** The Mesopotamian Marshes have been dramatically reduced in size due to massive water diversions from the Tigris and Euphrates rivers, primarily for upstream dam construction and irrigation. Intentional drainage of the marshes also played a significant role. This is arguably the most impactful example of large-scale wetland destruction in modern history.']
wetlands_mesopotamian_marshes_stressors["Water Diversion"]["Influences"] = ['Habitat Availability.', 'Water Quality (increased salinity due to reduced freshwater inflow).', '**Logic Description:** The Mesopotamian Marshes have been dramatically reduced in size due to massive water diversions from the Tigris and Euphrates rivers, primarily for upstream dam construction and irrigation. Intentional drainage of the marshes also played a significant role. This is arguably the most impactful example of large-scale wetland destruction in modern history.']
wetlands_mesopotamian_marshes_stressors["Water Diversion"]["Logic Description"] = '---'

# --- Pollution ---
wetlands_mesopotamian_marshes_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., salts, heavy metals, pesticides, oil) in water and sediment.'
wetlands_mesopotamian_marshes_stressors["Pollution"]["Data Sources"] = ['Water quality monitoring data (limited availability, but some data exists).', 'Research studies.', '**Impact on Area:** Degradation of water quality.', '**Impact on Biodiversity:**', 'Toxic effects on wildlife.', 'Impacts on human health (for Marsh Arabs who rely on the marshes).', '**Influenced By (Stressors):**', 'Agricultural Runoff: From upstream agriculture.', 'Industrial Discharge: (potentially, from industries along the rivers).', 'Oil Industry Activities: Spills and leaks.', 'Untreated Sewage: From cities and towns.', 'Military Activities: Past conflicts have left pollutants.', '**Influences (Stressors):**', 'Water Quality.', 'Wildlife Health.', '**Logic Description:** Pollution from various sources degrades water quality, impacting both wildlife and human populations.']
wetlands_mesopotamian_marshes_stressors["Pollution"]["Impact on Area"] = 'Degradation of water quality.'
wetlands_mesopotamian_marshes_stressors["Pollution"]["Impact on Biodiversity"] = 'Toxic effects on wildlife.\nImpacts on human health (for Marsh Arabs who rely on the marshes).\n**Influenced By (Stressors):**\nAgricultural Runoff: From upstream agriculture.\nIndustrial Discharge: (potentially, from industries along the rivers).\nOil Industry Activities: Spills and leaks.\nUntreated Sewage: From cities and towns.\nMilitary Activities: Past conflicts have left pollutants.\n**Influences (Stressors):**\nWater Quality.\nWildlife Health.\n**Logic Description:** Pollution from various sources degrades water quality, impacting both wildlife and human populations.'
wetlands_mesopotamian_marshes_stressors["Pollution"]["Influenced By"] = ['Agricultural Runoff: From upstream agriculture.', 'Industrial Discharge: (potentially, from industries along the rivers).', 'Oil Industry Activities: Spills and leaks.', 'Untreated Sewage: From cities and towns.', 'Military Activities: Past conflicts have left pollutants.', '**Influences (Stressors):**', 'Water Quality.', 'Wildlife Health.', '**Logic Description:** Pollution from various sources degrades water quality, impacting both wildlife and human populations.']
wetlands_mesopotamian_marshes_stressors["Pollution"]["Influences"] = ['Water Quality.', 'Wildlife Health.', '**Logic Description:** Pollution from various sources degrades water quality, impacting both wildlife and human populations.']
wetlands_mesopotamian_marshes_stressors["Pollution"]["Logic Description"] = '---'

# --- Climate Change ---
wetlands_mesopotamian_marshes_stressors["Climate Change"]["Metric"] = 'Temperature increase (°C); changes in precipitation (mm/year, seasonality); increased frequency of drought.'
wetlands_mesopotamian_marshes_stressors["Climate Change"]["Data Sources"] = ['* Climate Models', '* Historical records', '**Impact on Area:**', 'Increased evaporation rates.', 'Reduced water availability (exacerbating the effects of water diversion).', '**Impact on Biodiversity:**', 'Increased stress on marsh ecosystems.', 'Shifts in species distributions.', '**Influenced By (Stressors):**', '* Global GHG', '**Influences (Stressors):**', '* Water Availability', '**Logic Description:** Climate change is expected to exacerbate existing water stress in the region, further impacting the marshes.']
wetlands_mesopotamian_marshes_stressors["Climate Change"]["Impact on Area"] = ''
wetlands_mesopotamian_marshes_stressors["Climate Change"]["Impact on Biodiversity"] = 'Increased stress on marsh ecosystems.\nShifts in species distributions.\n**Influenced By (Stressors):**\n* Global GHG\n**Influences (Stressors):**\n* Water Availability\n**Logic Description:** Climate change is expected to exacerbate existing water stress in the region, further impacting the marshes.'
wetlands_mesopotamian_marshes_stressors["Climate Change"]["Influenced By"] = ['* Global GHG', '**Influences (Stressors):**', '* Water Availability', '**Logic Description:** Climate change is expected to exacerbate existing water stress in the region, further impacting the marshes.']
wetlands_mesopotamian_marshes_stressors["Climate Change"]["Influences"] = ['* Water Availability', '**Logic Description:** Climate change is expected to exacerbate existing water stress in the region, further impacting the marshes.']
wetlands_mesopotamian_marshes_stressors["Climate Change"]["Logic Description"] = '---'

# --- Salinization ---
wetlands_mesopotamian_marshes_stressors["Salinization"]["Metric"] = 'Salinity levels'
wetlands_mesopotamian_marshes_stressors["Salinization"]["Data Sources"] = ['* Water quality monitoring', '**Impact on Area**: Increased salt content', '**Impact on Biodiversity:**', '* Impacts on freshwater species', '**Influenced By (Stressors):**', '* Mesopotamian Marshes - Water Diversion', '**Influences (Stressors):**', '* Water quality', '**Logic Description:** Reduced freshwater inflow leads to increased salinity.']
wetlands_mesopotamian_marshes_stressors["Salinization"]["Impact on Biodiversity"] = '* Impacts on freshwater species\n**Influenced By (Stressors):**\n* Mesopotamian Marshes - Water Diversion\n**Influences (Stressors):**\n* Water quality\n**Logic Description:** Reduced freshwater inflow leads to increased salinity.'
wetlands_mesopotamian_marshes_stressors["Salinization"]["Influenced By"] = ['* Mesopotamian Marshes - Water Diversion', '**Influences (Stressors):**', '* Water quality', '**Logic Description:** Reduced freshwater inflow leads to increased salinity.']
wetlands_mesopotamian_marshes_stressors["Salinization"]["Influences"] = ['* Water quality', '**Logic Description:** Reduced freshwater inflow leads to increased salinity.']
wetlands_mesopotamian_marshes_stressors["Salinization"]["Logic Description"] = '---'

