from stressor_templates import *
import copy

wetlands_camargue_stressors = {
    "Altered Hydrology": copy.deepcopy(altered_hydrology_template),
    "Pollution": copy.deepcopy(pollution_template),
    "Climate Change": copy.deepcopy(climate_change_template),
    "Invasive Species": copy.deepcopy(invasive_species_template),
    "Tourism": {},
}

# --- Altered Hydrology ---
wetlands_camargue_stressors["Altered Hydrology"]["Metric"] = "Water levels in the Rhone River and in the Camargue's lagoons and marshes; salinity levels; water flow rates."
wetlands_camargue_stressors["Altered Hydrology"]["Data Sources"] = ["French government agencies (e.g., Agence de l'eau Rhône Méditerranée Corse).", 'Research institutions (e.g., Tour du Valat research center).', 'Remote sensing data.', '**Impact on Area:** Changes in the extent and distribution of different wetland habitats (freshwater marshes, brackish lagoons, salt marshes).', '**Impact on Biodiversity:**', 'Impacts on bird populations (breeding, feeding, migration - the Camargue is a *major* bird area).', 'Changes in plant communities (due to altered salinity).', 'Impacts on fish and invertebrate communities.', '**Influenced By (Stressors):**', 'Water Management Practices: The Camargue is heavily managed for water, with a complex system of canals, sluices, and pumping stations.', 'Upstream Water Use: Agriculture, industry, and urban areas along the Rhone River.', 'Rice Cultivation: A major water user within the Camargue itself.', 'Climate Change: Changes in precipitation and sea level.', '* Sea level rise', '**Influences (Stressors):**', 'Salinity Levels.', 'Habitat Availability.', 'Water Quality.', "**Logic Description:** The Camargue's hydrology is heavily managed, and changes in water management practices, upstream water use, and climate change can significantly alter water levels, salinity, and the distribution of different wetland habitats. This is a constant balancing act between human needs and ecological needs."]
wetlands_camargue_stressors["Altered Hydrology"]["Impact on Area"] = 'Changes in the extent and distribution of different wetland habitats (freshwater marshes, brackish lagoons, salt marshes).'
wetlands_camargue_stressors["Altered Hydrology"]["Impact on Biodiversity"] = "Impacts on bird populations (breeding, feeding, migration - the Camargue is a *major* bird area).\nChanges in plant communities (due to altered salinity).\nImpacts on fish and invertebrate communities.\n**Influenced By (Stressors):**\nWater Management Practices: The Camargue is heavily managed for water, with a complex system of canals, sluices, and pumping stations.\nUpstream Water Use: Agriculture, industry, and urban areas along the Rhone River.\nRice Cultivation: A major water user within the Camargue itself.\nClimate Change: Changes in precipitation and sea level.\n* Sea level rise\n**Influences (Stressors):**\nSalinity Levels.\nHabitat Availability.\nWater Quality.\n**Logic Description:** The Camargue's hydrology is heavily managed, and changes in water management practices, upstream water use, and climate change can significantly alter water levels, salinity, and the distribution of different wetland habitats. This is a constant balancing act between human needs and ecological needs."
wetlands_camargue_stressors["Altered Hydrology"]["Influenced By"] = ['Water Management Practices: The Camargue is heavily managed for water, with a complex system of canals, sluices, and pumping stations.', 'Upstream Water Use: Agriculture, industry, and urban areas along the Rhone River.', 'Rice Cultivation: A major water user within the Camargue itself.', 'Climate Change: Changes in precipitation and sea level.', '* Sea level rise', '**Influences (Stressors):**', 'Salinity Levels.', 'Habitat Availability.', 'Water Quality.', "**Logic Description:** The Camargue's hydrology is heavily managed, and changes in water management practices, upstream water use, and climate change can significantly alter water levels, salinity, and the distribution of different wetland habitats. This is a constant balancing act between human needs and ecological needs."]
wetlands_camargue_stressors["Altered Hydrology"]["Influences"] = ['Salinity Levels.', 'Habitat Availability.', 'Water Quality.', "**Logic Description:** The Camargue's hydrology is heavily managed, and changes in water management practices, upstream water use, and climate change can significantly alter water levels, salinity, and the distribution of different wetland habitats. This is a constant balancing act between human needs and ecological needs."]
wetlands_camargue_stressors["Altered Hydrology"]["Logic Description"] = '---'
wetlands_camargue_stressors["Altered Hydrology"]["Impact Function"] = "impact_altered_hydrology_wetlands_camargue"

# --- Pollution ---
wetlands_camargue_stressors["Pollution"]["Metric"] = 'Concentrations of pollutants (e.g., nutrients, pesticides, heavy metals) in water, sediment, and biota.'
wetlands_camargue_stressors["Pollution"]["Data Sources"] = ['Water quality monitoring programs (French government agencies, research institutions).', 'Research studies.', '**Impact on Area:** Degradation of water quality.', '**Impact on Biodiversity:**', 'Eutrophication (nutrient enrichment).', 'Toxic effects on wildlife.', 'Impacts on food webs.', '**Influenced By (Stressors):**', 'Agricultural Runoff: From rice cultivation and other agriculture in the region.', 'Industrial Discharge: (potentially, from industries upstream).', 'Urban Runoff: From nearby towns and cities.', '**Influences (Stressors):**', 'Water Quality.', 'Wildlife Health.', "**Logic Description:** Pollution from agriculture, industry, and urban areas can degrade water quality and impact the Camargue's ecosystems."]
wetlands_camargue_stressors["Pollution"]["Impact on Area"] = 'Degradation of water quality.'
wetlands_camargue_stressors["Pollution"]["Impact on Biodiversity"] = "Eutrophication (nutrient enrichment).\nToxic effects on wildlife.\nImpacts on food webs.\n**Influenced By (Stressors):**\nAgricultural Runoff: From rice cultivation and other agriculture in the region.\nIndustrial Discharge: (potentially, from industries upstream).\nUrban Runoff: From nearby towns and cities.\n**Influences (Stressors):**\nWater Quality.\nWildlife Health.\n**Logic Description:** Pollution from agriculture, industry, and urban areas can degrade water quality and impact the Camargue's ecosystems."
wetlands_camargue_stressors["Pollution"]["Influenced By"] = ['Agricultural Runoff: From rice cultivation and other agriculture in the region.', 'Industrial Discharge: (potentially, from industries upstream).', 'Urban Runoff: From nearby towns and cities.', '**Influences (Stressors):**', 'Water Quality.', 'Wildlife Health.', "**Logic Description:** Pollution from agriculture, industry, and urban areas can degrade water quality and impact the Camargue's ecosystems."]
wetlands_camargue_stressors["Pollution"]["Influences"] = ['Water Quality.', 'Wildlife Health.', "**Logic Description:** Pollution from agriculture, industry, and urban areas can degrade water quality and impact the Camargue's ecosystems."]
wetlands_camargue_stressors["Pollution"]["Logic Description"] = '---'
wetlands_camargue_stressors["Pollution"]["Impact Function"] = "impact_pollution_wetlands_camargue"

# --- Climate Change ---
wetlands_camargue_stressors["Climate Change"]["Metric"] = 'Temperature increase (°C); changes in precipitation (mm/year, seasonality); sea level rise (mm/year).'
wetlands_camargue_stressors["Climate Change"]["Data Sources"] = ['*  Climate Models', '* Historical Records', '**Impact on Area:**', 'Coastal erosion and inundation due to sea level rise.', 'Changes in salinity.', 'Increased risk of drought.', '**Impact on Biodiversity:**', 'Shifts in species distributions.', 'Increased stress on wildlife.', 'Changes in phenology.', '**Influenced By (Stressors):**', '* Global GHG', '**Influences (Stressors):**', '* Sea Level Rise', '* Hydrology', '**Logic Description:** Climate change is impacting the Camargue through sea level rise, altered precipitation patterns, and increased temperatures.']
wetlands_camargue_stressors["Climate Change"]["Impact on Area"] = ''
wetlands_camargue_stressors["Climate Change"]["Impact on Biodiversity"] = 'Shifts in species distributions.\nIncreased stress on wildlife.\nChanges in phenology.\n**Influenced By (Stressors):**\n* Global GHG\n**Influences (Stressors):**\n* Sea Level Rise\n* Hydrology\n**Logic Description:** Climate change is impacting the Camargue through sea level rise, altered precipitation patterns, and increased temperatures.'
wetlands_camargue_stressors["Climate Change"]["Influenced By"] = ['* Global GHG', '**Influences (Stressors):**', '* Sea Level Rise', '* Hydrology', '**Logic Description:** Climate change is impacting the Camargue through sea level rise, altered precipitation patterns, and increased temperatures.']
wetlands_camargue_stressors["Climate Change"]["Influences"] = ['* Sea Level Rise', '* Hydrology', '**Logic Description:** Climate change is impacting the Camargue through sea level rise, altered precipitation patterns, and increased temperatures.']
wetlands_camargue_stressors["Climate Change"]["Logic Description"] = '---'
wetlands_camargue_stressors["Climate Change"]["Impact Function"] = "impact_climate_change_wetlands_camargue"

# --- Invasive Species ---
wetlands_camargue_stressors["Invasive Species"]["Metric"] = 'Distribution and abundance'
wetlands_camargue_stressors["Invasive Species"]["Data Sources"] = ['* Research and monitoring', '**Impact on Area**: Ecosystem changes', '**Impact on Biodiversity:**', '* Competition, altered habitats', '**Influenced By (Stressors):**', '* Human activities', '**Influences (Stressors):**', '* Native species', '**Logic Description:** Invasive species can disrupt the ecosystem.']
wetlands_camargue_stressors["Invasive Species"]["Impact on Biodiversity"] = '* Competition, altered habitats\n**Influenced By (Stressors):**\n* Human activities\n**Influences (Stressors):**\n* Native species\n**Logic Description:** Invasive species can disrupt the ecosystem.'
wetlands_camargue_stressors["Invasive Species"]["Influenced By"] = ['* Human activities', '**Influences (Stressors):**', '* Native species', '**Logic Description:** Invasive species can disrupt the ecosystem.']
wetlands_camargue_stressors["Invasive Species"]["Influences"] = ['* Native species', '**Logic Description:** Invasive species can disrupt the ecosystem.']
wetlands_camargue_stressors["Invasive Species"]["Logic Description"] = '---'
wetlands_camargue_stressors["Invasive Species"]["Impact Function"] = "impact_invasive_species_wetlands_camargue"

# --- Tourism ---
wetlands_camargue_stressors["Tourism"]["Data Sources"] = ['* Tourism Statistics', '**Impact on Area**: Localized disturbance', '**Impact on Biodiversity:**', '* Disturbance of wildlife, especially birds.', '**Influenced By (Stressors):**', '* Popularity of the region', '**Influences (Stressors):**', '* Wildlife Behavior', '**Logic Description:** Tourism, while economically important, can disturb wildlife.']
wetlands_camargue_stressors["Tourism"]["Impact on Biodiversity"] = '* Disturbance of wildlife, especially birds.\n**Influenced By (Stressors):**\n* Popularity of the region\n**Influences (Stressors):**\n* Wildlife Behavior\n**Logic Description:** Tourism, while economically important, can disturb wildlife.'
wetlands_camargue_stressors["Tourism"]["Influenced By"] = ['* Popularity of the region', '**Influences (Stressors):**', '* Wildlife Behavior', '**Logic Description:** Tourism, while economically important, can disturb wildlife.']
wetlands_camargue_stressors["Tourism"]["Influences"] = ['* Wildlife Behavior', '**Logic Description:** Tourism, while economically important, can disturb wildlife.']
wetlands_camargue_stressors["Tourism"]["Logic Description"] = '---'
wetlands_camargue_stressors["Tourism"]["Impact Function"] = "impact_tourism_wetlands_camargue"

